Lad os sige, at vi har spurgt 10 personer, om de ved, hvad \"skibidi toilet\" betyder.
De 7 svarede \"Ja\", og de 3 svarede \"Nej\". Vi sætter targetværdien $t=1$ for \"Ja\" og $t=0$ for \"Nej\".

Vi skal så ud fra en eller flere feature variable for hver person træne en kunstig neuron til at kunne klassificere, om en ny person ved, hvad \"skibidi toilet\" betyder.

Vi vil dog ikke fokusere på netværket, men på mulige værdier af tabsfunktionen, idet vi bruger *squared error* som tabsfunktion:
$$
E = \frac{1}{2} \sum \left (t-o \right)^2
$$ {#eq-tabsfunktion}
hvor der summeres over alle træningsdata. Husk, at $t$ kun kan værdierne $0$ og $1$, mens $o$ er et reelt tal mellem $0$ og $1$.


::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 2: Udregn værdi af tabsfunktionen i eksemplet
* Hvad er den absolut mindste værdi, som tabsfunktionen kan få?
* Hvad skal outputværdien $o$ sættes til for hver af de $10$ personer for at få minimum?

* Hvad er den absolut største værdi, som tabsfunktionen kan få?
* Hvad skal outputværdien $o$ sættes til for hver af de $10$ personer for at få maksimum?

* Hvilken værdi giver tabsfunktionen, hvis outputværdien sættes til $o=0.5$ for alle input?

:::

Så $o=0.5$ giver os et udgangspunkt, som værdien af tabsfunktionen i hvert fald bør komme under, men mon ikke det kan blive bedre end det? Vi kigger således på en meget simpel model, hvor værdien af $o$ er ens for alle input. 

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 3: Udregn E for andre værdien end $o=0.5$
* Overvej, om $o=0$ eller $o=1$ for alle input vil give den laveste værdi af tabsfunktionen.
* Udregn værdien af $E$ i begge tilfælde.
* Overvej, hvilken fast værdi $o=p$, der vil give den mindste værdi af tabsfunktionen.
* Beregn værdien af $E$ for forskellige værdier af $p$.

:::

Normalt vil outputværdien $o$ afhænge af vores feature variable. Men som vi gjorde det i opgave 3, vil vi nu prøve at undersøge nærmere, hvad der sker, hvis vi fastholder outputværdien på en fast værdi $o=p$ for alle input. Det vil sige, at vi vil se på tabsfunktionen som en funktion af $p$ alene: $E(p)$.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 4: Tabsfunktionen som funktion af p
* Opskriv forskriften for $E(p)$ (i eksemplet hvor 7 personer har en targetværdi på 1, og 3 har en targetværdi på 0).
* Bestem minimum for $E$ ved hjælp af differentialregning.
* Stemmer svaret her med det, du fandt ud af i opgave 3?

:::
