---
title: 'Facit til forløbet \"Skibidi toilet\"'
description: ''
image: ""
categories:
---

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 1

* $E=40.55$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 2

* Minimum: $E=0$.

* Maksimum: $E=5$.

* Med $o=0.5$ er $E=1.25$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 3

* Med $o=0$ er $E=3.5$.

* Med $o=1$ er $E=1.5$.

* Med $o=0.7$ er $E=1.05$ og $o=0.7$ er bedst.


:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 4

* $E(p)= \frac{1}{2}\cdot (10p^2 -14p+7)$.

* Minimum i $p=0.7$.
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 5

* $E(p) = \frac{n}{2}\cdot(p^2+q-2pq)$.

* Minimumsværdien for tabsfunktionen $E(q) = \frac{n}{2}\cdot (q-q^2)$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 6

* Andelen, som har svaret \"Ja\", er $q=0.85$.

* Da $E(q)=12.75$ er mindre end værdien fra opgave 1 på $40.55$, kan det helt sikkert gøres bedre, og sikkert også noget bedre end $12.75$.

* Med brug af app'en kan værdien af $E$ let komme under $3$, og det er også muligt, at få den under $2.5$ (og måske lavere endnu). 
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 7

* I opgave 1 er CA på $0.59$.

* Med $o=0$ for alle input er CA på $0.15$.

* Med $o=1$ for alle input er CA på $0.85$.

* CA under $0.85$ er derfor ikke godt nok.

* Med app'en har du nok CA på omkring $0.97$ eller større.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 8

* Med konstant $o=1$ bliver $\text{CA}=0.85$ og $E=15$.

* Med $o=0.55$ for $t=1$ og $o=0.45$ for $t=0$ bliver $\text{CA}=1$ og $E=20.25$.
Så CA og $E$ følges ikke nødvendigvis ad.

:::
