Med disse overvejelser skal vi tilbage til datasættet med de 200 person om \"skibidi toilet\". Vi skal se, om den model, vi trænede med appen, ser ud til måske at være trænet godt nok.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 6: Vurder på den trænede model
* Bestem værdien $q$ ud fra datasættet ved at tælle, hvor mange dom har svaret \"Ja\" og dividere med det samlede antal. 
* Udregn værdien af $E$ ud fra $n$ og $q$.
* Sammenlign med den værdi af tabsfunktionen, som træningen i opgave 1 gav. Hvad fortæller det om den trænede model?
* Brug app'en med andre værdier på start-vægtene, learning-rate og/eller antal iterationer for at få værdien af tabsfunktionen så lav som mulig.
:::

I opgave 6 har du nok set, at du ved hjælp af app'en kan træne en model, hvor værdien af tabsfunktionen er væsentligt mindre end den mindste værdi af tabsfunktionen, som du kan få, hvis $p$ er sat til en fast værdi for alle input. Det skyldes selvfølgelig, at den nye model også tager højde for de to feature variable alder ($x_1$) og tid ($x_2$), så $p$ nu ikke længere er et fast tal, men afhænger af alder og tid.
