::: {.callout-note collapse="true" appearance="minimal"}
### Diagnosticering af sygdomme

Redegørelse for hvordan et kunstigt neuralt netværk kan trænes, så det kan anvendes i forbindelse med diagnosticering af sygdomme.


#### Materialer
[Meet the computer diagnosing cancer](https://www.youtube.com/watch?v=aLSzh_tqwxw&t=140s). 
:::

::: {.callout-note collapse="true" appearance="minimal"}
### Diabetes type II og logistisk regression

I biologi arbejdes der med diabetes type II og oral glukosetolerancetest (OGTT) som screeningstest.

I matematik redegøres der for [logistisk regression](../materialer/logistisk/log-reg.qmd) -- herunder hvordan denne metode kan benyttes til at prædiktere sygdom ved en person ud fra information fra et større datasæt. Desuden forklares idéen bag maksimum likelihood, og hvordan parametrene i modellen estimeres.

Der kan eventuelt konstrueres et OGTT-datasæt, hvorpå der udføres logistisk regression -- herunder kan der redegøres for betydningen af odds, og der kan foretages en prædiktion for diabetes på en fiktiv person, der er testet.


#### Materialer

[Dansk studie: 3 dages motion om ugen booster diabetes-patienters behandling](https://videnskab.dk/krop-sundhed/3-dages-motion-om-ugen-kan-give-et-godt-boost-til-diabetes-patienters-behandling/). 

:::
