::: {.callout-note collapse="true" appearance="minimal"}
### Genkendelse af håndskrevne tal

Implementering af et kunstig neuralt netværk, som kan kende forskel på for eksempel håndskrevne 2- og 9-taller.

#### Problemformulering [innovativ opgave]

Udarbejd et løsningsforslag til hvordan man oversætter håndskrevne tal, så de kan genkendes af en computer. I den forbindelse skal du:

+ Redegør for hvad der forstås ved et kunstigt neuralt netværk, hvor du tager udgangspunkt i et netværk med ét skjult lag. Kom herunder ind på feedforward og backpropagation.
+ Implementer et kunstig neuralt netværk med ét skjult lag, som kan bruges til at kende forskel på 2- og 9-taller (brug en passende delmængde af MNIST train-datasættet).
+ Vurder dit løsningsforslag i forhold til styrker og svagheder samt graden af innovation. Inddrag i den forbindelse en passende delmængde af MNIST test-datasættet.


#### Materialer
Netværket kan trænes på en passende delmængde af [MNIST datasættet](https://www.kaggle.com/datasets/oddrationale/mnist-in-csv?resource=download). 
:::


::: {.callout-note collapse="true" appearance="minimal"}
### Kunstig intelligens - muligheder og begrænsninger

Redegørelse for hvordan et kunstigt neuralt netværk trænes. Diskussion af de etiske problemstillinger, som kan opstå i forbindelse med anvendelsen af kunstig intelligens og/eller diskussion af de muligheder og begrænsninger, der er ved brugen kunstig intelligens. 


#### Materialer

[Advantages and disadvantages of Machine Learning Language](https://medium.com/@hussain.tibacademy/advantages-and-disadvantages-of-machine-learning-language-ad11badda9e5)

:::

