::: {.callout-note collapse="true" appearance="minimal"}
### Kandidattest

Eleven udarbejder en kandidattest i forbindelse med valg, som kan bruges til at prædiktere politisk tilhørsforhold. Hvordan selve kandidattesten kan laves, giver vi et eksempel på i noten om [perceptroner](../materialer/perceptron/perceptron.qmd). Noten om [kunstige neuroner](../materialer/kunstige_neuroner/kunstige_neuroner.qmd) vil også være oplagt at bruge som teoretisk udgangspunkt i matematik.

Se også forslaget om \"Ulighed\" herunder.

:::

::: {.callout-note collapse="true" appearance="minimal"}
### Overvågning

Brugen af kunstig intelligens i forbindelse med ansigtsgenkendelse. Herunder kan emner som persondataloven, retssikkerhed og/eller partiernes holdning til overvågning behandles. 

:::

::: {.callout-note collapse="true" appearance="minimal"}
### Ulighed

Der tages afsæt i følgende holdninger til ulighed uden at sætte partier på:

+ ”Blå blok”:  Øget ulighed er en drivkraft for øget vækst, som giver øget velstand for alle.
+ ”Rød blok”:  Større lighed er et kendetegn ved de bedst fungerende demokratier og lykkeligste samfund. Det giver samtidig de bedste muligheder for alle og samlet set de bedste rammevilkår for virksomheder.

#### Problemformulering

Hvad er ulighed, og er det et problem i Danmark?

+ Redegør kort for begrebet ulighed - herunder holdninger til ulighed.
+ Forklar, hvordan kunstig intelligens kan bruges ved kandidattests i forbindelse med valg og lav en simpel kandidattest ud fra nogle få velvalgte spørgsmål om aspekter af ulighed, som skal give en anbefaling om at stemme på enten rød eller blå blok.
+ Kom desuden ind på forskellige matematiske mål for ulighed herunder Gini-koefficienten.
+ Forslag til diskussionsspørgsmål: Skal uligheden begrænses? Hvordan kan den begrænses? Fordele og ulemper ved ulighed og så videre.

#### Materialer

[Jensby, Jakob & Brøndum, Peter (2020): *Ulighedens mange ansigter*](https://ulighedensmangeansigter.ibog.forlagetcolumbus.dk/).

:::

::: {.callout-note collapse="true" appearance="minimal"}
### Anbefalingssystemer og målrettede politiske kampagner

Eleven redegør for, hvordan en af anbefalingsalgoritmerne i [noten om anbefalingssystemer](/materialer/anbefalinger/anbefalinger.qmd) virker. I samfundsfag arbejdes der med, hvordan personlige data ikke kun kan bruges til målrettede filmanbefalinger, men også til målrettede politiske kampagner.
:::
