---
title: "Del 6: Andre tabsfunktioner"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

::: {.estimeret_tid}

Forventet tid ca. 1 x 90 min.

Hele denne del er en fortsĂŠttelse af eksemplet om \"slow learning\" og kan derfor springes over. Alternativt kan man nĂžjes med at springe opgave 3 over.

::: 

{{< include ../space.qmd >}}

## Aktivitet 1 - Cross-entropy tabsfunktionen {.aimat}

I [del 3](kunstige_neuroner_del3.qmd) sĂ„ vi, at der kan opstĂ„ problemer med slow learning. Det opstĂ„r pĂ„ grund af opdateringsreglerne:

$$
\begin{aligned}
w_0^{(\textrm{ny})} \leftarrow & w_0 + \eta \cdot \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right) \cdot o^{(m)}\cdot (1-o^{(m)}) \\
w_1^{(\textrm{ny})} \leftarrow & w_1 + \eta \cdot \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right) \cdot o^{(m)}\cdot (1-o^{(m)}) \cdot x^{(m)}
\end{aligned}
$$ {#eq-opdatering}

hvor man kan vĂŠre i den uheldige situation, at man har fĂ„et startet gradientnedstigning i en $(w_0, w_1)$ vĂŠrdi, hvor neuronen fejlagtigt er \"mĂŠttet\". Det betyder, at den prĂŠdikterer en outputvĂŠrdi $o$ tĂŠt pĂ„ $0$, selvom target er $1$ og omvendt, nĂ„r target er $0$. I begge tilfĂŠlde vil opdateringsleddet i (@eq-opdatering) vĂŠre tĂŠt pĂ„ $0$ -- enten fordi $o^{(m)}$ er tĂŠt pĂ„ $0$ eller fordi $1-o^{(m)}$ er tĂŠt pĂ„ $0$.

Vi skal i denne del se pĂ„, at det skyldes valget af *squared error* tabsfunktionen. I det simple tilfĂŠlde med kun Ă©n inputvariabel, sĂ„ vi i [del 3](kunstige_neuroner_del3.qmd), at *squared error* tabsfunktionen var defineret ved:

$$
E = \frac{1}{2} \sum_{m=1}^M (t^{(m)}-\sigma(w_0 + w_1 \cdot x^{(m)}))^2
$$
hvor det $m$'te trĂŠningseksempel bestĂ„r af inputvĂŠrdien $x^{(m)}$ (den $m$'te kundes alder) med tilhĂžrende targetvĂŠrdi $t^{(m)}$ (som er $1$, hvis den $m$'te kunde aktiverer tilbuddet og $0$ ellers).

Holder vi det helt simpelt og betragter Ă©t trĂŠningseksempel ad gangen, sĂ„ er *squared error* tabsfunktionen pĂ„ formen

$$
E = \frac{1}{2} (t-o)^2= \frac{1}{2} (t-\sigma(w_0 + w_1 \cdot x))^2
$$ {#eq-squared_error}


Nu er der dog ingen almen gyldig naturlov, som siger, at vi absolut skal bruge *squared error* tabsfunktionen. Til gengĂŠld stiller vi nogle generelle krav til en tabsfunktion, som afspejler, at den netop skal bruges til at mĂ„le et *tab* eller en *fejl* ved en AI model. Derfor skal en tabsfunktion $E$ overordnet set have fĂžlgende egenskaber:

::: {.callout-caution collapse="false" appearance="minimal"}
### Egenskaber ved en tabsfunktion $E$

* Tabsfunktionen skal vĂŠre positiv eller $0$: $E \geq 0$ (vi vil ikke operere med negative fejl). 

* Hvis AI modellen er god til at prĂŠdiktere, skal $E$ vĂŠre tĂŠt pĂ„ $0$, mens hvis AI modellen er dĂ„rlig til at prĂŠdiktere, skal $E$ vĂŠre langt vĂŠk fra $0$.

:::


::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 1: Egenskaber ved *squared error* tabsfunktionen

* GĂžr rede for at *squared error* tabsfunktionen i (@eq-squared_error) opfylder de egenskaber, som en tabsfunktion skal have.


:::


En anden ofte anvendt tabsfunktion er *cross-entropy* tabsfunktionen. Generelt er den defineret sĂ„dan her:

$$
\begin{aligned}
E = - \sum_{m=1}^{M} \left (t^{(m)} \cdot \ln(o^{(m)}) + (1-t^{(m)}) \cdot \ln(1-o^{(m)})  \right)
\end{aligned}
$$

Ser vi igen kun pĂ„ Ă©t trĂŠningseksempel ad gangen fĂ„r vi det lidt simplere udtryk:

$$
\begin{aligned}
E = - \left (t \cdot \ln(o) + (1-t) \cdot \ln(1-o)  \right),
\end{aligned}
$$ {#eq-cross_entropy}

hvor outputvĂŠrdien $o$ er

$$
o = \sigma(w_0+w_1 \cdot x)
$$

i det tilfĂŠlde, hvor der kun er Ă©n inputvariabel.

Vi skal nu se, at *cross-entropy* tabsfunktionen rent faktisk opfylder kravene til en tabsfunktion.


::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 2: Egenskaber ved *cross-entropy* tabsfunktionen

* Opskriv et udtryk for tabsfunktionen i (@eq-cross_entropy) i det tilfĂŠlde, hvor $t=0$.

* Opskriv et udtryk for tabsfunktionen i (@eq-cross_entropy) i det tilfĂŠlde, hvor $t=1$.

* Tegn grafen for $\ln(x)$ og for $-\ln(x)$. Hvad er sammenhĂŠngen mellem de to grafer?

* Vi ved, at $0<o<1$. Argumenter for, at det mĂ„ betyde, at $0<1-o<1$. 

* Brug grafen for $-\ln(x)$ til at argumentere for, at *cross-entropy* tabsfunktionen er positiv.


Vi skal nu se, at hvis den kunstige neuron er god til at prĂŠdiktere, sĂ„ er vĂŠrdien af $E$ tĂŠt pĂ„ $0$. At vĂŠre god til at prĂŠdiktere betyder, at

::: {.centertext}

Hvis $t=0$, sĂ„ er $o$ tĂŠt pĂ„ $0$.

Hvis $t=1$, sĂ„ er $o$ tĂŠt pĂ„ $1$.

:::

* Brug udtrykket for tabsfunktionen, nĂ„r $t$ er henholdsvis $0$ og $1$ til at argumentere for, at *cross-entropy* tabsfunktionen er tĂŠt pĂ„ $0$, nĂ„r den kunstige neuron er god til at prĂŠdiktere.


:::

{{< include ../space.qmd >}}

## Aktivitet 2 - Nye opdateringsregler {.aimat}

Vi skal nu have bestemt opdateringsreglerne for vĂŠgtene, nĂ„r vi bruger *cross-entropy* tabsfunktionen.

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 3: Partielle afledede og opdateringsregler (valgfri)

- Bestem de partielle afledede $\frac{\partial E}{\partial w_0}$ og $\frac{\partial E}{\partial w_1}$ af tabsfunktionen i (@eq-cross_entropy), hvor

   $$
   o = \sigma(w_0+w_1 \cdot x)
   $$

   Husk pĂ„, at du fra [del 1](kunstige_neuroner_del1.qmd) ved, at

   $$
   \sigma'(x) = \sigma(x) \cdot (1-\sigma(x))=o \cdot (1-o)
   $$
   da outputvĂŠrdien $o=\sigma(x)$.

- Brug de partielle afledede til at opskrive opdateringsreglerne:

   $$
   \begin{aligned}
   w_0^{\mathrm{(ny)}} &\leftarrow w_0 - \eta \cdot \frac{\partial E}{\partial w_0} \\
   w_1^{\mathrm{(ny)}} &\leftarrow w_1 - \eta \cdot \frac{\partial E}{\partial w_1}
   \end{aligned}
   $$
   
[Valgfri udfordring]{.fremhaev}

- Udled opdateringsreglerne i det tilfĂŠlde, hvor vi bruger den generelle tabsfunktion:

   $$
   E = \frac{1}{2} \sum_{m=1}^M (t^{(m)}-\sigma(w_0 + w_1 \cdot x^{(m)}))^2 
   $$
   hvor $M$ er antallet af trĂŠningseksempler.


:::

{{< include ../space.qmd >}}

## Aktivitet 3 - VĂŠk med slow learning! {.aimat}

Hvis du har lavet opgave 3 rigtig, skulle du gerne ende med fĂžlgende opdateringsregler:

::: {.callout-note collapse="false" appearance="minimal"} 
### Opdateringsregler baseret pĂ„ *cross-entropy*

$$
\begin{aligned}
w_0^{(\textrm{ny})} \leftarrow & w_0 + \eta \cdot (t-o) \\
w_1^{(\textrm{ny})} \leftarrow & w_1 + \eta \cdot (t-o) \cdot x
\end{aligned}
$$ {#eq-opdatering_simple_cross}

:::


Til sammenligning vil opdateringsreglerne for *squared error* tabsfunktionen i (@eq-opdatering), i det tilfĂŠlde
hvor vi kun opdaterer vĂŠgtene for Ă©t trĂŠningseksempel ad gangen, se sĂ„dan her ud:

::: {.callout-note collapse="false" appearance="minimal"} 
### Opdateringsregler baseret pĂ„ *squared error*

$$
\begin{aligned}
w_0^{(\textrm{ny})} \leftarrow & w_0 + \eta \cdot (t-o) \cdot o\cdot (1-o) \\
w_1^{(\textrm{ny})} \leftarrow & w_1 + \eta \cdot (t-o) \cdot o\cdot (1-o) \cdot x
\end{aligned}
$$ {#eq-opdatering_simple_squared}

:::

Det er nu tydeligt, at faktoren $o \cdot (1-o)$ -- som var den stĂžrrelse, der gav anledning til *slow learning* -- er forsvundet fra opdateringsreglerne baseret pĂ„ *cross-entropy*. Det betyder, at hvis man er i en situation, hvor $t=1$ og $o$ er tĂŠt pĂ„ $0$ eller omvendt, sĂ„ vil vĂŠgtene baseret pĂ„ *cross-entropy* tabsfunktionen hurtigt blive opdateret. Hvorimod det ikke er tilfĂŠldet, hvis opdateringen af vĂŠgtene er baseret pĂ„ *squared error* tabsfunktionen. Det skyldes simpelthen, at valget af sigmoid-funktionen som aktiveringsfunktion passer meget bedre sammen med *cross-entropy* tabsfunktionen, end den gĂžr med *squared error* tabsfunktionen.

Lad os se hvordan det virker i praksis.

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 4: TrĂŠning af kunstig neuron med forskellige tabsfunktioner

- Ăbn [neuron app'en](https://apps01.math.aau.dk/ai/neuron){target="blank"}.

- Under fanen \"Data\" uploader du [datasĂŠttet](data/goodfood.xlsx) (tryk pĂ„ \"Browse...\") og tryk derefter pĂ„ \"NĂŠste\".

- Under fanen \"Variable\" gĂžr du fĂžlgende:
  
  + VĂŠlg \"Aktiveret\" som target-variabel.
  
  + VĂŠlg \"Ja\" som target-vĂŠrdi.
  
  + VĂŠlg \"Alder\", \"Forbrug\" og \"Kon\" som feature-variable (det vil sige inputvariable). Og sĂžrg for at indtaste dem i den rĂŠkkefĂžlge.
  
  + Tryk pĂ„ \"NĂŠste\".
  
- Under fanen \"TrĂŠning\" gĂžr du fĂžlgende:

   + SĂŠt startvĂŠgtene til $0$.
  
  + Behold en learning rate ($\eta$) pĂ„ $0.001$.
  
  + Behold antal iterationer pĂ„ $1000$.
  
  + Behold \"Squared" som tabsfunktion.
  
  + Tryk pĂ„ \"TrĂŠn model\".
  
- Ser det ud som om, at vi har fundet et minimum for tabsfunktionen (se pĂ„ grafen for tabsfunktionen til hĂžjre)?

- Under fanen \"Evaluering & PrĂŠdiktion\" vĂŠlger du \"Evaluering pĂ„ trĂŠningsdata\". NotĂ©r [klassifikationsnĂžjagtigheden (CA)](/noter/vurdering_model/vurdering_model.qmd#klassifikationsnĂžjagtighed){target="_blank"}. 

Vi vil nu undersĂžge, om der er nogen forskel, hvis vi bruger *cross entropy* som tabsfunktion.

- Gentag ovenstĂ„ende men vĂŠlg i stedet \"Cross-entropy\" som tabsfunktion. Er der nogen forskel?

*Obs! SlutvĂŠrdien af de to forskellige tabsfunktioner er [ikke]{.underline} sammenlignelige.*

:::

Vi har tidligere set, at vi fik problemer med *slow learning*, hvis vi valgte *squared error* som tabsfunktion og satte start-vĂŠgtene til $10$. Lad os se hvordan det gĂ„r, hvis vi i stedet bruger *cross-entropy*:


::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 5: TrĂŠning af kunstig neuron med forskellige tabsfunktioner

Brug igen [neuron app'en](https://apps01.math.aau.dk/ai/neuron){target="blank"} fra forrige opgave og vĂŠlg de samme indstillinger bortset fra, at du nu sĂŠtter:

- Alle startvĂŠgte til $10$.

- \"Antal iterationer\" til henholdsvis $1000$, $10000$ og $100000$ (den sidste tager lidt tid).

- \"Tabsfunktion\" til \"Squared\".

- Tryk pĂ„ \"TrĂŠn model\".

- NotĂ©r i alle tre tilfĂŠlde slutvĂŠrdien af tabsfunktionen og klassifikationsnĂžjagtigheden (CA) (findes under fanen \"Evaluering & PrĂŠdiktion\", nĂ„r du vĂŠlger \"Evaluering pĂ„ trĂŠningsdata\").

Du skulle gerne genfinde problemet med *slow learning* her. Lad os undersĂžge, om *cross-entropy* som tabsfunktion lĂžser problemet med *slow learning*.

- Gentag ovenstĂ„ende, men vĂŠlg \"Cross-entropy\" som tabsfunktion. 

- Hvor mange iterationer er nĂždvendige for at fĂ„ en klassifikationsnĂžjagtighed pĂ„ omkring $0.85$, hvis du bruger henholdsvis *sqaured error* og *cross-entropy* som tabsfunktion?


:::

Som du sikkert indsĂ„, er *cross-entropy* klart det bedste valg som tabsfunktion, nĂ„r der skal ske klassifikation. Vi startede blot med *squared error*, fordi den er meget lettere at forstĂ„. 


Hvis du vil vide mere om tabsfunktioner, kan du lĂŠse i [noten om tabsfunktioner](../../noter/tabsfunktioner/tabsfunktioner.qmd).



{{< include ../space.qmd >}}

[$\leftarrow$ Forrige](kunstige_neuroner_del5.qmd){.prev}
[NĂŠste $\rightarrow$](kunstige_neuroner_del7.qmd){.next}


