---
title: "Facit til del 5 -- forløbet om kunstige neuroner"
description: ''
image: ""
categories:
---



Facit til udvalgte dele af opgaverne.

::: {.callout-note collapse="true" appearance="minimal"}  

### Facit -- opgave 4
Hvis man fjerner en af de forklarende variable, så falder CA ved krydsvalideringen. Specielt ser \"Forbrug\" ud til at være vigtig for modellen. Det tyder på, at ingen af de forklarende variable kan undværes, og dermed at der ikke er sket overfitting.

:::
  
::: {.callout-note collapse="true" appearance="minimal"}  

### Facit -- opgave 5

Nedenstående er baseret på, at startvægtene er sat til $0$, og at antal iterationer er sat til $10000$.

- Ditte: $21\%$. Vis ikke tilbuddet.
- Helena: $95\%$. Vis tilbuddet.
- Susanne: $21\%$. Vis ikke tilbuddet.
- Helle: $85\%$. Vis tilbuddet.
- Rasmus: $3\%$. Vis ikke tilbuddet.
- Mikkel: $66\%$. Vis tilbuddet.
- Henrik: $3\%$. Vis ikke tilbuddet. 
- Jan: $36\%$. Vis ikke tilbuddet.

:::
  
::: {.callout-note collapse="true" appearance="minimal"}  

### Facit -- opgave 6
CA er lidt bedre for startværdien $0$, så de to modeller er ikke helt lige gode. Selvom den ene kun bruger $10000$ opdateringer, så fungerer den lidt bedre, fordi startværdien er valgt mere heldigt.

:::
