---
title: "Til læreren"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Dette forløb bygger på noten om [kunstige neuroner](../../materialer/kunstige_neuroner/kunstige_neuroner.qmd). Hver enkel del i forløbet består typisk af en video, som skal ses (eller alternativt kan det tilhørende afsnit i noten læses). Herefter følger en række opgaver, som støtter op om teorien.

Det meste af forløbet er tænkt, så eleverne selv kan arbejde med stoffet. 

Her følger en kort gennemgang af de enkelte dele:

I [del 1](neurale_net_del1.qmd) er det vigtigste at arbejde med sigmoid-funktionen som aktiveringsfunktion. Resten af materialet i denne del kan bruges til undervisningsdifferentiering.

[Del 2](neurale_net_del2.qmd) handler om at forstå gradientnedstigning, som en metode til at bestemme minimum for en funktion af flere variable. Her arbejdes der konkret med at bestemme minimum for en funktion af to variable i GeoGebra og som en del af opgaven visualiseres trinene, der anvendes i gradientnedstigning. 

I [del 3](neurale_net_del3.qmd) introduceres begrebet *tabsfunktion* og eleverne arbejder med, hvordan vægtene, der indgår i tabsfunktionen, bestemmes ved hjælp af gradientnedstigning. Helt konkret behandles *squared error* tabsfunktionen, fordi den er nemmeste at forstå. Vi slutter del 3 af med en aktivitet, som handler om en væsentlig ulempe ved *squared error* tabsfunktionen -- nemlig *slow learning*. Denne aktivitet kan bruges til de særligt dygtige og/eller interesserede elever.

I [del 4](neurale_net_del4.qmd) arbejdes der med at træne en kunstige neuron ved hjælp af en app. Den sidste aktivitet handler igen om *slow learning*, som kan springes over, hvis eleverne ikke tidligere har arbejdet med det. 

[Del 5](neurale_net_del5.qmd) handler om, hvordan man vælger hvilke inputvariable, der skal indgå i den endelige model. Eleverne komme her til at arbejde med *krydsvalidering*. Igen handler den sidste aktivitet om *slow learning*, som eventuelt kan springes over.

[Del 6](neurale_net_del6.qmd) handler om, hvordan man ved at vælge en anden tabsfunktion, kan løse problemet med *slow learning*. Hvis eleverne ikke tidligere har arbejdet med *slow learning* springes denne del over.