---
title: "Del 1: Aktiveringsfunktioner"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Forventet tid ca. 1-2 x 90 min.**

Vi anbefaler, at alle arbejder med aktivitet 1 og 2. De resterende aktiviteter kan enten udelades eller bruges som ekstra udfordringer.

## Aktivitet 1 - Hvad er AI? {.aimat}

Start med at se denne video, hvor vi fortæller lidt om, hvad AI er.

{{< video https://youtu.be/ivrBEopralQ >}}

I videoen omtales **aktiveringsfunktioner**, som bruges i forbindelse med kunstige neurale netværk. Du har også hørt, at for at træne et kunstigt neuralt netværk så skal man minimere en tabsfunktion. Når en funktion skal minimeres, har vi brug for at kunne differentiere. Da aktiveringsfunktionerne indgår i tabsfunktionen, får vi derfor brug for at kunne differentiere aktiveringsfunktioner. 

I det følgende skal vi se på en række forskellige aktiveringsfunktioner og finde ud af, hvordan vi differentierer dem.

## Aktivitet 2 - Sigmoid {.aimat}

{{< include ../aktiveringsfunktioner/sigmoid.qmd >}}


## Aktivitet 3 - Softsign {.aimat}

{{< include ../aktiveringsfunktioner/softsign.qmd >}}


## Aktivitet 4 - Hyperbolsk tangens {.aimat}

{{< include ../aktiveringsfunktioner/hyperbolsk_tangens.qmd >}}


## Aktivitet 5 - ReLU {.aimat}

{{< include ../aktiveringsfunktioner/ReLU.qmd >}}


