---
title: "Del 5: Fortolkning"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Forventet tid ca. 60 min.]{.estimeret_tid}

## Aktivitet 1 {.aimat}
Start med at se denne video (eller læs afsnittet [fortolkning af parametrene i den logistiske regressionsmodel](../../materialer/logistisk/log-reg.qmd#fortolkning-af-parametrene-i-den-logistiske-regressionsmodel) -- du behøver kun at læse indtil sætningen *Altså vokser odds med ca. 22%, når $x$ vokser med 1 i modellen.*):

{{< video https://www.youtube.com/embed/tmUCE2xBx80?si=vk693gfUsTsy9-G1 >}}

## Aktivitet 2 {.aimat}

I app'en herunder ser du grafen for $f(x)=\frac{1}{1+\mathrm{e}^{-(ax+b)}}$.
Hvis du trækker i skyderne for $a$ og $b$, kan du se, hvordan kurven ændrer form.
Den stiplede linje har ligning $x=\frac{-b}{a}$ og svarer altså til den vandrette forskydning af grafen for den standard logistiske funktion. På figuren er der desuden 9 punkter, som du kan få grafen til at passe bedst muligt med.

* Eksperimenter med $a$ og $b$ for at forstå deres betydning for grafen.


{{< include _geogebra/_geogebra.qmd >}}

::: {#fig-fortolk_a_og_b}
::: {#ggbApplet1}
:::
Eksperimenter med a og b for at forstå deres betydning for grafen. Når du har klikket på en skyder med musen, kan værdien også ændres med piletasterne, hvilket kan ske mere præcist.
:::


```{=html}

<script>
window.onload = function() {
  applet1.inject('ggbApplet1');
  }
</script>

```

## Aktivitet 3 {.aimat}

Lav nedenstående opgave.

::: {.callout-note collapse="false" appearance="minimal"}

## Opgave 1

I et (fiktivt) dataeksempel ser vi på sandsynligheden $p(x)$ for, at en kunde i et supermarked vælger at købe den økologiske mælk frem for den konventionelle som funktion af kundens årlige indtægt $x$ (i 100.000 kr).
Vi kommer frem til følgende logistiske regressionsmodel
$$
\text{logit}(p(x))= -1.3+0.5x.
$$

* Hvor mange procent stiger odds for at vælge økologisk, når årsindtægten stiger med 100.000 kr ($x$ vokser med 1)?

* Tegn grafen for $p(x)$. 

* Indse ved hjælp af @fig-fortolk_a_og_b, at grafen for den generelle logistiske funktion med forskrift
$$
f(x)=\frac{1}{1+\mathrm{e}^{-(ax+b)}}
$$
er stejlest, når funktionsværdien er $f(x)=1/2$. 

* Hvilken værdi af $x$ svarer til en funktionsværdi på $1/2$ (isoler $x$ udtrykt ved hjælp af $a$ og $b$)?

*Hint* til sidste spørgsmål: Start med at overveje, hvilken værdi $\mathrm{e}^{-a\cdot x+b}$ skal have, og derefter hvilken værdi $a\cdot x+b$ skal have, og til sidst $x$.

:::

