---
title: "Til læreren"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Dette forløb bygger på noten om [logistisk regression](../../noter/logistisk/log-reg.qmd). Hver enkel del i forløbet består typisk af en video, som skal ses (eller alternativt kan det tilhørende afsnit i noten læses). Herefter følger en række opgaver, som støtter op om teorien.

Det meste af forløbet er tænkt, så eleverne selv kan arbejde med stoffet. Enkelte gange er det tanken, at læreren gennemgår noget. Det er markeret på denne måde:

::: {.callout-important collapse="false" appearance="minimal"}

## Lærergennemgang

* Din lærer vil vise, at ...

:::


Her følger en række fif til de enkelte dele:

I [del 1](log_reg_del1.qmd) kan inddelingen i intervaller også laves i elevernes eget CAS værktøj, hvis det foretrækkes. Der kan dog eventuelt være en pointe i at lade eleverne stifte bekendtskab med begrebet pivottabel i Excel uanset.

I [del 2](log_reg_del2.qmd) i beviset for, at $O(p)= \frac{p}{1-p}$ er voksende, kan differentiationen laves på forskellige måder, som det nu passer bedst ind for det konkrete hold. Det kan for eksempel ske ved hjælp af: 

* Produktreglen og reglen for at differentiere sammensatte funktioner, idet kvotienten først omskrives til et produkt:

$$
\begin{aligned}
O'(p) &= p' \cdot {1 \over 1-p} + p \cdot ({1 \over 1-p})' \\& = 1 \cdot {1 \over 1-p} + p \cdot {-1 \over (1-p)^2} \cdot (-1) \\ &=  {1-p \over (1-p)^2} + {p \over (1-p)^2} \\ &= {1 \over (1-p)^2} > 0
\end{aligned}
$$

* Kvotientreglen (enten bevist eller blot gennemgået):
$$
\begin{aligned}
O'(p) &= {p' \cdot (1-p) - p \cdot (1-p)' \over (1-p)^2} \\ &= {1 \cdot (1-p) - p \cdot (-1) \over (1-p)^2} \\ &= {1 \over (1-p)^2} > 0
\end{aligned}
$$

I [del 4](log_reg_del4.qmd) kan det overvejes, om eleverne selv -- eventuelt i grupper -- skal læse udledningen, eller om den skal ske ved lærergennemgang.

I [del 5](log_reg_del5.qmd) er det ikke nødvendigt, at eleverne forstår alle detaljer, en rimelig forståelse af idéen kan være tilstrækkelig.

I [del 5](log_reg_del5.qmd) kan man godt lade eleverne læse hele afsnittet, men den sidste del er ikke så central, og ligner meget et kendt bevis fra eksponentielle udviklinger.

I [del 6](log_reg_del6.qmd) anvendes black-box, men der kan for eksempel sammenlignes med Newton-Raphsons metode til bestemmelse af nulpunkter.

[Del 7](log_reg_del7.qmd) kan eventuelt springes over.
