---
title: "Del 3: Den logistiske regressionsmodel"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Forventet tid ca. 45 min.]{.estimeret_tid}

## Aktivitet 1 {.aimat}
Start med at se denne video (eller læs afsnittet [den logistiske regressionsmodel](../../materialer/logistisk/log-reg.qmd#den-logistiske-regressionsmodel)):

{{< video https://www.youtube.com/embed/kh3Acg9M3P8?si=mdlZhPajrZHDDk7Q >}}

## Aktivitet 2 {.aimat}

Lav nedenstående opgave.

::: {.callout-note collapse="false" appearance="minimal"}

## Opgave 1

I denne opgave ser vi på sandsynligheden $p(x)$ for at lide af forhøjet blodtryk[^17]  som funktion af kolestreroltallet $x$.
Vi kigger derfor på datasættet nedenfor, som er en udvalgt del af et [virkeligt datasæt](https://biolincc.nhlbi.nih.gov/studies/framcohort/).
I tabellen angiver $y=1$ forhøjet blodtryk, mens $y=0$ angiver normalt blodtryk.   

* Lav en tabel, hvor du beregner sandsynligheden for forhøjet blodtryk, odds og ln(odds) inden for hvert interval. 

* Indtegn punkter i et koordinatsystem, hvor $x$-værdien er midtpunkterne for intervallerne, og $y$-værdien er de tilhørende ln(odds). 

* Ser sammenhængen lineær ud? 

* Vil det give mening at bruge en logistisk regression?

|  $x$ | $y=0$ | $y=1$   |
|    :----:   | :----:   | :----:   |
| ]100,150] | 27   | 6    | 
| ]150,200] | 693    | 202   |
| ]200,250] | 1354   |   571    |
| ]250,300] | 716    |  471   |
| ]300,350] | 156   |  132  |
| ]350,400] | 20    |   23   | 
| ]400,450] | 2   |  5    | 
            

[^17]: Forhøjet blodtryk er defineret som systolisk blodtryk højere end 140mmHg eller diastolisk blodtryk højere end 90mmHg.

:::