---
title: "Del 7: Multipel logistisk regression og prædiktion"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Forventet tid ca. 60 min.]{.estimeret_tid}

{{< include ../space.qmd >}}

## Aktivitet 1 {.aimat}
Læs afsnittet om [multipel logistisk regression](../../materialer/logistisk/log-reg.qmd#multipel-logistisk-regression).

{{< include ../space.qmd >}}

## Aktivitet 2 {.aimat}

Lav nedenstående opgave.

::: {.callout-note collapse="false" appearance="minimal"}

## Opgave 1

I en multipel regression har man fundet følgende model for odds $O(x_1,x_2)$ for, at en bruger af en hjemmeside klikker på en given reklame, hvor $x_1$ og $x_2$ er antal gange kunden har læst henholdsvis kulturnyheder og sportsnyheder inden for den sidste måned
$$
O(x_1,x_2) = \mathrm{e}^{-2+0.5x_1-0.1x_2 }.
$$

* En bruger har læst kulturnyheder 4 gange og sportsnyheder 7 gange inden for den sidste måned. Hvad er odds for, at brugeren klikker på reklamen?

* Hvad er odds ratioen for kulturnyheder?

* Er sandsynligheden for at klikke på reklamen højere eller lavere blandt brugere, der læser mange kulturnyheder?

:::

{{< include ../space.qmd >}}

## Aktivitet 3 {.aimat}
Læs afsnittet om [prædiktion](../../materialer/logistisk/log-reg.qmd#prædiktion).

{{< include ../space.qmd >}}

## Aktivitet 4 {.aimat}

Lav nedenstående opgave.

::: {.callout-note collapse="false" appearance="minimal"}

## Opgave 2

Vi kigger igen på en multipel regressionsmodel for odds $O(x_1,x_2)$ for, at en bruger af en hjemmeside klikker på en given reklame, hvor $x_1$ og $x_2$ er antal gange kunden har læst henholdsvis kulturnyheder og sportsnyheder inden for den sidste måned. Modellen for odds er fundet til
$$
O(x_1,x_2) = \mathrm{e}^{-2+0.5x_1-0.1x_2 }.
$$
Vi vil gerne prædiktere, om en bruger klikker på reklamen, så vi kan beslutte, om det er relevant at vise ham den.

* En bruger har læst kulturnyheder 5 gange og sportsnyheder 8 gange inden for den sidste måned.
Vil du prædiktere, at brugeren klikker på reklamen?

:::
