---
format:
    html: 
      toc: true
      toc-title: Indhold
      toc-location: left
# listing:
#   id: main-listing-content
#   fields: 
#     - title
#     - description
#   sort: false
#   contents:
#     - "undervisningsforlob.qmd"
#     - "materialer.qmd"
#     - "sro.qmd"
#     - "srp.qmd"
#     - "apps.qmd"
#     - "referencer.qmd"
#   type: grid
#   grid-columns: 2
---


Hvad er AI-matematik? Det er al den spændende matematik, som ligger bag
kunstig intelligens!

På denne side kan du lære, hvordan gymnasiematematikken bruges i en
masse former for kunstig intelligens. Til gengæld kan du *ikke* lære,
hvordan du får kunstig intelligens til at løse dine
matematikopgaver!


<!-- ::: {#main-listing-content .test} -->
<!-- ::: -->


::: {.quarto-listing .quarto-listing-container-grid}

::: {.list .grid .quarto-listing-cols-2}

 <!-- UNDERVISNINGSFORLØB : START -->

<div class="g-col-1" data-index="0"> 
<a href='undervisningsforlob.qmd' class="quarto-grid-link">

::: {.quarto-grid-item .card .h-100 .card-left .pink_morkblaa}

::: {.card-body .post-contents }

<h5 class="no-anchor card-title listing-title">
Undervisningsforløb
</h5>

::: {.card-text .listing-description}

Forskellige undervisningsforløb til matematik i gymnasiet, som inddrager AI. Der findes forløb til både A-, B- og C-niveau.

:::

:::

:::

</a>
</div>

 <!-- UNDERVISNINGSFORLØB : SLUT -->


<!-- MATERIALER : START -->

<div class="g-col-1" data-index="1"> 
<a href='materialer.qmd' class="quarto-grid-link">

::: {.quarto-grid-item .card .h-100 .card-left .gul_morkblaa}

::: {.card-body .post-contents }

<h5 class="no-anchor card-title listing-title">
Materialer
</h5>


::: {.card-text .listing-description}

Noter om diverse AI relaterede emner.
:::

:::

:::

</a>
</div>

 <!-- MATERIALER : SLUT -->


<!-- SRP : START -->

<div class="g-col-1" data-index="2"> 
<a href='srp.qmd' class="quarto-grid-link">

::: {.quarto-grid-item .card .h-100 .card-left .lysblaa_morkblaa}

::: {.card-body .post-contents }

<h5 class="no-anchor card-title listing-title">
SRP
</h5>


::: {.card-text .listing-description}

Idéer til hvordan AI kan inddrages i SRP.
:::

:::

:::

</a>
</div>

 <!-- SRP : SLUT -->
 
 <!-- SRO : START -->

<div class="g-col-1" data-index="3"> 
<a href='sro.qmd' class="quarto-grid-link">

::: {.quarto-grid-item .card .h-100 .card-left .morkblaa_lysblaa}

::: {.card-body .post-contents }

<h5 class="no-anchor card-title listing-title">
SRO
</h5>


::: {.card-text .listing-description}

Idéer til hvordan AI kan inddrages i SRO.
:::

:::

:::

</a>
</div>

 <!-- SRO : SLUT -->
 
  <!-- APPS : START -->

<div class="g-col-1" data-index="4"> 
<a href='apps.qmd' class="quarto-grid-link">

::: {.quarto-grid-item .card .h-100 .card-left .morkblaa_pink}

::: {.card-body .post-contents }

<h5 class="no-anchor card-title listing-title">
Apps
</h5>


::: {.card-text .listing-description}

Diverse apps til træning af kunstig intelligens.
:::

:::

:::

</a>
</div>

 <!-- APPS : SLUT -->


  <!-- REFERENCER : START -->

<div class="g-col-1" data-index="5"> 
<a href='referencer.qmd' class="quarto-grid-link">

::: {.quarto-grid-item .card .h-100 .card-left .pink_morkblaa}

::: {.card-body .post-contents }

<h5 class="no-anchor card-title listing-title">
Referencer
</h5>


::: {.card-text .listing-description}

Diverse referencer til andre AI materialer.
:::

:::

:::

</a>
</div>

 <!-- REFERENCER : SLUT -->
 

:::

:::

Projektet "AI - Aalborg Intelligence" er finansieret af Novo Nordisk Fonden og løber frem til 2026.


