Læs afsnittet [\"Betydning og kontekst\" ](/materialer/sprogmodeller/word2vec.qmd#betydning-og-kontekst) og [\"Træningsdata\"](/materialer/sprogmodeller/word2vec.qmd#træningsdata) i noten Word2Vec eller se videoen her:

{{< video https://www.youtube.com/embed/DVGvvXHI7wQ >}}

Vi gentager her en vigtig pointe:

::: {.highlight .centertext}
**Betydningen af et ord er bestemt af den kontekst, ordet indgår i.**
:::


::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 2: Betydning er kontekst

Ordet \"får\" har flere betydninger.

* Skriv mindst to sætninger, hvor man ud fra konteksten forstår to forskellige betydninger af \"får\".

* Find selv på et ord med flere betydninger og skriv mindst to sætninger, som afslører betydningen.

:::

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 3: Træningsdata

Betragt følgende tekstkorpus:

::: {.llm_saetninger}
Matematik er det sjoveste fag i verden
:::

* Udfyld med udgangspunkt i ovenstående tekstkorpus og et 3-ords vindue nedenstående tabel (se eventuelt [tabel 1 i noten om Word2vec](/materialer/sprogmodeller/word2vec.qmd#tbl-data)). Bemærk, at kontekstcellen skal være blank, hvis den tilsvarende plads i vinduet er tom.

   | Fokus | Kontekst |
   |:---:|:---:|
   | Matematik  |   |
   | Matematik  |   |
   | er  |   |
   | er  |   |
   | det  |   |
   | det  |   |
   | $\vdots$  | $\vdots$ |
   : {.bordered}

:::
