<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="I dette forløb vil vi se på en metode til at forudsige, hvilket parti man vil stemme på ud fra svar på en række spørgsmål.">

<title>Kandidattest – AI MAT - matematikken bag magien</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../logo/SVG/Bomaerke_05_AIMAT_2024.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6b43892a240587b998a1459dc14fee72.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-Y219BCPS45"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
 
  gtag('consent', 'default', {
    'ad_storage': 'denied',
    'analytics_storage': 'denied'
  });
gtag('config', 'G-Y219BCPS45', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="floating nav-fixed slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../logo/PNG/Logo_multi_AIMAT_RGB_2024.png" alt="" class="navbar-logo light-content">
    <img src="../logo/PNG/Logo_multi_AIMAT_RGB_2024.png" alt="" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../undervisningsforlob/index.html"> 
<span class="menu-text">Undervisningsforløb</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../noter/index.html"> 
<span class="menu-text">Noter</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../srp/index.html"> 
<span class="menu-text">SRP</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../apps/index.html"> 
<span class="menu-text">Apps</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../til_laererne.html"> 
<span class="menu-text">Til lærerne</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> <i class="bi bi-envelope" role="img" aria-label="Om os">
</i> 
<span class="menu-text">Om os</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.youtube.com/@ai-mat" target="_blank"> <i class="bi bi-youtube" role="img" aria-label="YouTube">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indhold</h2>
   
  <ul>
  <li><a href="#formål" id="toc-formål" class="nav-link active" data-scroll-target="#formål">Formål</a></li>
  <li><a href="#softmax-modellen" id="toc-softmax-modellen" class="nav-link" data-scroll-target="#softmax-modellen">Softmax modellen</a></li>
  <li><a href="#brug-af-app-til-træning-af-kunstig-neuron" id="toc-brug-af-app-til-træning-af-kunstig-neuron" class="nav-link" data-scroll-target="#brug-af-app-til-træning-af-kunstig-neuron">Brug af app til træning af kunstig neuron</a></li>
  <li><a href="#politiske-kandidaters-svar" id="toc-politiske-kandidaters-svar" class="nav-link" data-scroll-target="#politiske-kandidaters-svar">16 politiske kandidaters svar</a></li>
  <li><a href="#det-helt-store-eksempel-med-877-politikere" id="toc-det-helt-store-eksempel-med-877-politikere" class="nav-link" data-scroll-target="#det-helt-store-eksempel-med-877-politikere">Det helt store eksempel med 877 politikere</a></li>
  <li><a href="#delvis-facitliste" id="toc-delvis-facitliste" class="nav-link" data-scroll-target="#delvis-facitliste">Delvis facitliste</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Kandidattest</h1>
  <div class="quarto-categories">
    <div class="quarto-category">01_A-niveau</div>
    <div class="quarto-category">04_Kort</div>
    <div class="quarto-category">Samfundsfag</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Forudsætninger og tidsforbrug
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Eksponentialfunktioner, herunder <span class="math inline">\(\mathrm{e}^x\)</span>.</li>
<li>Sandsynlighedsfelter.</li>
<li>Linjens ligning i planen på formen <span class="math inline">\(a \cdot x + b \cdot y + c = 0\)</span>.</li>
<li>Planens ligning i rummet på formen <span class="math inline">\(a \cdot x + b \cdot y + c \cdot z+d= 0\)</span>.</li>
</ul>
<p>Hvis man forinden har arbejdet med det korte forløb <a href="https://aimat.dk/undervisningsforlob/sengetester.html">Sengetester i IKEA</a>, de første dele af det lange forløb om <a href="https://aimat.dk/undervisningsforlob/kunstige_neuroner_langt_forlob/kunstige_neuroner_forside.html">Kunstige neuroner</a> eller det korte forløb <a href="https://aimat.dk/undervisningsforlob/hvem_ligner_du_mest.html">Hvilken politiker er du mest enig med</a>, kan konteksten være mere tydelig, men det er ikke en forudsætning.</p>
<p><strong>Tidsforbrug:</strong> Ca. 150 minutter.</p>
</div>
</div>
</div>
<section id="formål" class="level3 purpose">
<h3 class="anchored" data-anchor-id="formål">Formål</h3>
<p>Formålet med dette forløb er</p>
<ul>
<li>at lære <strong>softmax</strong> at kende som et værktøj til <strong>multipel klassifikation</strong>.</li>
<li>at lære lidt om <strong>kunstige neuroner</strong>, samt at anvende en app til at træne en kunstig neuron.</li>
<li>at undersøge, hvordan en kunstig neuron til multipel klassifikation kan bruges til at forudsige, hvilket parti man vil stemme på ud fra svar på en række spørgsmål, som det for eksempel gøres i kandidattests.</li>
</ul>
</section>
<section id="softmax-modellen" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="softmax-modellen">Softmax modellen</h2>
<p>Vi vil gerne lave en model, som kan forudsige, hvilket parti man vil stemme på, baseret på svarene fra en række spørgsmål. Det er for eksempel noget lignende, der sker, når diverse medier laver kandidattests i forbindelse med valg. Testene fungerer som regel på den måde, at man bliver stillet en række forskellige spørgsmål, og så skal man svare på en skala fra "helt uenig" til "helt enig". Disse kategorier af svar kan for eksempel oversættes til matematik<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> på denne måde:</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;I nogle kandidattests kan man ikke vælge "Hverken/eller", men de resterende kategorier oversættes stadig til negative og positive værdier, som det er eksemplificeret i tabellen.</p></div></div><table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: center;">Helt uenig</th>
<th style="text-align: center;">Uenig</th>
<th style="text-align: center;">Hverken/eller</th>
<th style="text-align: center;">Enig</th>
<th style="text-align: center;">Helt enig</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(-2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
</tr>
</tbody>
</table>
<p>Vi starter med et meget lille fiktivt eksempel, hvor fire personer: Andy, Bella, Charlie og Doresa, har svaret på to spørgsmål samt angivet, hvilket parti de stemmer på.</p>
<p>Vi forestiller os, at de to spørgsmål er:</p>
<ul>
<li><p>Spørgsmål 1: Topskatten skal sættes op.</p></li>
<li><p>Spørgsmål 2: Danske virksomheder skal pålægges en CO2-afgift.</p></li>
</ul>
<p>Vi vil så indføre to variable <span class="math inline">\(x_1\)</span> og <span class="math inline">\(x_2\)</span>, hvor</p>
<ul>
<li><p><span class="math inline">\(x_1\)</span>: svaret på "Topskatten skal sættes op" angivet på en skala fra <span class="math inline">\(-2\)</span> til <span class="math inline">\(2\)</span>.</p></li>
<li><p><span class="math inline">\(x_2\)</span>: svaret på "Danske virksomheder skal pålægges en CO2-afgift" angivet på en skala fra <span class="math inline">\(-2\)</span> til <span class="math inline">\(2\)</span>.</p></li>
</ul>
<p>Vi lader som om, at partierne er <strong>S</strong> (Socialdemokratiet), <strong>E</strong> (Enhedslisten) og <strong>V</strong> (Venstre). Det parti, som en given person vil stemme på, vil vi kalde for <span class="math inline">\(t\)</span> (som står for <strong>targetværdi</strong>). Andy, Bella, Charlie og Doresa har nu svaret følgende:</p>
<table class="table-bordered table">
<colgroup>
<col style="width: 28%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Navn</th>
<th style="text-align: center;">Spørgsmål 1 <span class="math inline">\((x_1)\)</span></th>
<th style="text-align: center;">Spørgsmål 2 <span class="math inline">\((x_2)\)</span></th>
<th style="text-align: center;">Parti (<span class="math inline">\(t\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Andy</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textrm{Helt uenig } (-2)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textrm{ Helt uenig } (-2)}\)</span></td>
<td style="text-align: center;"><strong>V</strong></td>
</tr>
<tr class="even">
<td>Bella</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textrm{Uenig } (-1)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textrm{Enig } (1)}\)</span></td>
<td style="text-align: center;"><strong>S</strong></td>
</tr>
<tr class="odd">
<td>Charlie</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textrm{Uenig } (-1)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textrm{Uenig } (-1)}\)</span></td>
<td style="text-align: center;"><strong>S</strong></td>
</tr>
<tr class="even">
<td>Doresa</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textrm{Enig } (1)}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textrm{Helt enig } (2)}\)</span></td>
<td style="text-align: center;"><strong>E</strong></td>
</tr>
</tbody>
</table>
<p>Bemærk her, at svarene "Helt uenig" og "Uenig" er farvet lyseblå, mens "Helt enig" og "Enig" er farvet lyserøde.</p>
<p>Vi vil nu lave en model, hvor man ud fra de svar, man giver på de to spørgsmål, kan forudsige, hvor sandsynligt det er, at man stemmer på hvert af de tre partier. Vi vil træne modellen, så den passer godt til svarene fra de fire personer og derefter håbe, at den også vil passe godt til andre personer. Naturligvis er to spørgsmål og fire personer alt for lidt, men det gør vi noget ved senere.</p>
<p>Vi udregner så for enhver kombination af person og parti en score:</p>
<p><span class="math display">\[
\textrm{score}(\textrm{person, parti}) = w_0 + w_1 \cdot x_1+ w_2 \cdot x_2
\]</span></p>
<p>hvor <span class="math inline">\(w_0\)</span> kaldes for bias og <span class="math inline">\(w_1\)</span> og <span class="math inline">\(w_2\)</span> kaldes for vægte.</p>
<p>Bias og vægte kan være forskellige for hvert parti, så vi kalder dem for <span class="math inline">\(s_0, s_1, s_2\)</span> (Socialdemokratiet), <span class="math inline">\(e_0, e_1, e_2\)</span> (Enhedslisten) og <span class="math inline">\(v_0, v_1, v_2\)</span> (Venstre).</p>
<p>Vi sætter disse bias og vægte til nogle lidt tilfældige værdier til at starte med.</p>
<table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: center;">Parti</th>
<th style="text-align: center;"><span class="math inline">\(w_0\)</span></th>
<th style="text-align: center;"><span class="math inline">\(w_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(w_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>V</strong></td>
<td style="text-align: center;"><span class="math inline">\(v_0 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_1 = -1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_2 = 0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>S</strong></td>
<td style="text-align: center;"><span class="math inline">\(s_0 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(s_1 = 1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(s_2 = 0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>E</strong></td>
<td style="text-align: center;"><span class="math inline">\(e_0 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(e_1 = 0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(e_2 = 0\)</span></td>
</tr>
</tbody>
</table>
<p>For Andy kan vi så udregne:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\textrm{score}(\textrm{Andy, V}) = 0 + (-1) \cdot (-2) + 0 \cdot (-2) = 2 \\
&amp;\textrm{score}(\textrm{Andy, S}) = 0 + 1 \cdot (-2) + 0 \cdot (-2) = -2 \\
&amp;\textrm{score}(\textrm{Andy, E}) = 0 + 0 \cdot (-2) + 0 \cdot (-2) = 0
\end{aligned}
\]</span></p>
<p>Så lige nu er den højeste score for Andy for <strong>V</strong>, hvilket er godt, da han faktisk stemmer på Venstre.</p>
<p>Men modellen skulle jo ikke kun give en score, men faktisk give en sandsynlighed for hvert parti. Så vi skal have fundet en metode til at få sandsynligheder i stedet for scores. Om sandsynlighederne ved vi, at de skal være positive, ligge mellem <span class="math inline">\(0\)</span> og <span class="math inline">\(1\)</span> og tilsammen give <span class="math inline">\(1.\)</span></p>
<p>En simpel måde at få tallene positive på er at opløfte <span class="math inline">\(\mathrm{e}\)</span> i scoren:</p>
<p><span class="math display">\[
\begin{aligned}
\mathrm{e}^2 &amp; \approx  7.389 \\
\mathrm{e}^{-2} &amp; \approx 0.135 \\
\mathrm{e}^0 &amp;=1
\end{aligned}
\]</span></p>
<p>Så lægges de tre tal sammen og hvert af tallene divideres med summen:</p>
<p><span class="math display">\[
\textrm{sum}=7.389 + 0.135 + 1 = 8.524
\]</span></p>
<p>For Andy giver det følgende:</p>
<table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: center;">Parti</th>
<th style="text-align: center;">Score</th>
<th style="text-align: center;"><span class="math inline">\(\mathrm{e}^{\textrm{score}}\)</span></th>
<th style="text-align: center;">Sandsynlighed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>V</strong></td>
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(7.389\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{7.389}{8.524} \approx 86.68 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>S</strong></td>
<td style="text-align: center;"><span class="math inline">\(-2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.135\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{0.135}{8.524} \approx 1.59 \%\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>E</strong></td>
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{8.524} \approx 11.73 \%\)</span></td>
</tr>
</tbody>
</table>
<p>Så med de valgte værdier af bias og vægte, angiver modellen en sandsynlighed på <span class="math inline">\(86.68 \%\)</span> for <strong>V</strong>, <span class="math inline">\(1.59 \%\)</span> for <strong>S</strong> og <span class="math inline">\(11.73 \%\)</span> for <strong>E</strong> for Andy. Da han faktisk stemte på <strong>V</strong>, er det jo rigtigt fint, uden dog at være helt perfekt, da vi helst ville have endnu større sandsynlighed for Venstre for Andy.</p>
<p>Denne metode til at omregne fra scores til sandsynligheder kaldes for <strong>softmax</strong>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Lav de tilsvarende udregninger for Bella, Charlie og Doresa.</li>
<li>Overvej derefter, om de valgte vægte er fornuftige – i den betydning, at modellen giver størst sandsynlighed for det parti, som personen faktisk stemmer på.</li>
</ul>
</div>
</div>
</div>
<p>Det var åbenlyst ikke så godt for Bella, Charlie og Doresa, da modellen for alle tre peger på et forkert parti. Idéen er nu, at vi skal ændre bias og vægte, så modellen bliver bedre.</p>
<p>Lad os i første omgang se på <span class="math inline">\(w_1\)</span> og dermed <span class="math inline">\(x_1\)</span>. Bemærk, at <span class="math inline">\(x_1 = -2\)</span> for Andy, at <span class="math inline">\(x_1 = -1\)</span> for Bella og Charlie, og at <span class="math inline">\(x_1 = 1\)</span> for Doresa. Da vi gerne vil have Andy til at få en høj score, og dermed en høj sandsynlighed for Venstre, giver det mening at lade <span class="math inline">\(v_1\)</span> være en negativ værdi, så <span class="math inline">\(v_1 \cdot x_1\)</span> bliver positiv. Før havde vi sat <span class="math inline">\(v_1=-1\)</span>, men lad os forstærke effekten med <span class="math inline">\(v_1 = -3\)</span>, så scoren for Andy bliver højere.</p>
<p>Det giver Andy en høj score <span class="math inline">\(v_1 \cdot x_1 = -3 \cdot (-2) = 6\)</span> for Venstre sammenlignet med hans score for Socialdemokratiet og Enhedslisten, hvilket er godt, da vi gerne vil have, at modellen peger på Venstre for ham.</p>
<p>Det giver Doresa en lav score <span class="math inline">\(v_1 \cdot x_1 = -3 \cdot 1= -3\)</span> i forhold til hendes scores for de øvrige partier, hvilket også er godt, da vi gerne vil have, at modellen ikke peger på Venstre for hende.</p>
<p>Det giver så desværre både Bella og Charlie en høj score, da <span class="math inline">\(v_1 \cdot x_1 = -3 \cdot (-1) = 3\)</span>, hvilket ikke er så godt, da vi gerne vil have, at modellen ikke peger på Venstre for dem. Det venter vi lige med at gøre noget ved, da vi starter med at få modellen til at pege på Enhedslisten for Doresa.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Overvej hvilken værdi <span class="math inline">\(e_1\)</span> kan gives, så Doresa får en positiv score for Enhedslisten, mens de øvrige tre får en negativ score?</li>
<li>Vælg vægten, så scoren for Doresa for Enhedslisten bliver <span class="math inline">\(6\)</span>, som scoren for Andy blev for Venstre.</li>
<li>Beregn score og sandsynlighed for hver af de tre partier for Doresa med den værdi, du har valgt (husk, at vi har sat <span class="math inline">\(v_1=-3\)</span>).</li>
</ul>
</div>
</div>
</div>
<p>Samlet ser det nu således ud, hvor både (score) og sandsynlighed er angivet for hvert parti.</p>
<table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: center;">Person</th>
<th style="text-align: center;">Venstre</th>
<th style="text-align: center;">Socialdemokratiet</th>
<th style="text-align: center;">Enhedslisten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Andy</td>
<td style="text-align: center;">(<span class="math inline">\(6\)</span>) <span class="math inline">\(99.97 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-2\)</span>) <span class="math inline">\(0.03 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-12\)</span>) <span class="math inline">\(0.00 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Bella</td>
<td style="text-align: center;">(<span class="math inline">\(3\)</span>) <span class="math inline">\(98.19 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-1\)</span>) <span class="math inline">\(1.80 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-6\)</span>) <span class="math inline">\(0.01 \%\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Charlie</td>
<td style="text-align: center;">(<span class="math inline">\(3\)</span>) <span class="math inline">\(98.19 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-1\)</span>) <span class="math inline">\(1.80 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-6\)</span>) <span class="math inline">\(0.01 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Doresa</td>
<td style="text-align: center;">(<span class="math inline">\(-3\)</span>) <span class="math inline">\(0.01 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(1\)</span>) <span class="math inline">\(0.67 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(6\)</span>) <span class="math inline">\(99.32 \%\)</span></td>
</tr>
</tbody>
</table>
<p>Vi skal nu have modellen til at vælge Socialdemokratiet for Bella og Charlie, men uden at ødelægge, at modellen vælger Venstre til Andy og Enhedslisten til Doresa.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Overvej, hvilken værdi biaset <span class="math inline">\(s_0\)</span> kan gives, så Bella og Charlie scorer højst for Socialdemokratiet (scoren skal over <span class="math inline">\(3\)</span>, da de allerede har scoren <span class="math inline">\(3\)</span> for parti Venstre), men uden at scoren for Andy eller Doresa bliver højst for Socialdemokratiet (de har begge <span class="math inline">\(6\)</span> som højst score til henholdsvis Venstre og Enhedslisten).</li>
</ul>
</div>
</div>
</div>
<p>Med en fornuftig værdi af bias for Socialdemokratiet (for eksempel på <span class="math inline">\(4.5\)</span>) kan tabellen komme til at se således ud:</p>
<table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: center;">Person</th>
<th style="text-align: center;">Venstre</th>
<th style="text-align: center;">Socialdemokratiet</th>
<th style="text-align: center;">Enhedslisten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Andy</td>
<td style="text-align: center;">(<span class="math inline">\(6\)</span>) <span class="math inline">\(97.07 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(2.5\)</span>) <span class="math inline">\(2.93 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-12\)</span>) <span class="math inline">\(0.00 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Bella</td>
<td style="text-align: center;">(<span class="math inline">\(3\)</span>) <span class="math inline">\(37.75 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(3.5\)</span>) <span class="math inline">\(62.24 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-6\)</span>) <span class="math inline">\(0.00 \%\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Charlie</td>
<td style="text-align: center;">(<span class="math inline">\(3\)</span>) <span class="math inline">\(37.75 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(3.5\)</span>) <span class="math inline">\(62.24 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-6\)</span>) <span class="math inline">\(0.00 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Doresa</td>
<td style="text-align: center;">(<span class="math inline">\(-3\)</span>) <span class="math inline">\(0.01 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(5.5\)</span>) <span class="math inline">\(37.75 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(6\)</span>) <span class="math inline">\(62.24 \%\)</span></td>
</tr>
</tbody>
</table>
<p>Men det kan stadig gøres bedre, blandt andet ved også at tage <span class="math inline">\(w_2\)</span> i brug.</p>
</section>
<section id="brug-af-app-til-træning-af-kunstig-neuron" class="level2">
<h2 class="anchored" data-anchor-id="brug-af-app-til-træning-af-kunstig-neuron">Brug af app til træning af kunstig neuron</h2>
<p>Med det meget lille og simple eksempel kunne vi altså godt justere vægtene manuelt og få et nogenlunde resultat. Men hvis der bliver <span class="math inline">\(100\)</span>, <span class="math inline">\(1000\)</span> eller millioner af vægte, så er det næppe en god idé. Det kræver noget lidt mere avanceret matematik, som vi ikke vil gennemgå i dette forløb. Du kan læse mere om dette i noten om <a href="https://aimat.dk/noter/softmax/softmax.html">Kunstige neurale netværk til multipel klassifikation</a>.</p>
<p>I stedet vil vi bruge en app til formålet. Du finder app’en <a href="https://apps01.math.aau.dk/ai/multi-neuron/">her</a> og datasættet som Excel fil <a href="kandidattest/datasaet_4_personer.xlsx">her</a>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Åbn app’en og indlæs datasættet.</li>
<li>Vælg <span class="math inline">\(t\)</span> som target-variabel og både <span class="math inline">\(x_1\)</span> og <span class="math inline">\(x_2\)</span> som feature-variable.</li>
<li>Sæt learning rate til <span class="math inline">\(0.1\)</span> og antal iterationer til <span class="math inline">\(1000\)</span>.</li>
<li>Træn modellen.</li>
<li>Sammenlign de værdier til bias og vægte, som app’en er nået frem til, med de værdier, som vi manuelt nåede frem til. Meget ligner det, vi fandt manuelt, men noget er også lidt anderledes.</li>
</ul>
</div>
</div>
</div>
<p>Med app’ens værdier ser tabellen således ud, hvilket må siges at være et meget tilfredsstillende resultat:</p>
<table class="table-bordered table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Person</th>
<th style="text-align: center;">Venstre</th>
<th style="text-align: center;">Socialdemokratiet</th>
<th style="text-align: center;">Enhedslisten</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Andy</td>
<td style="text-align: center;">(<span class="math inline">\(6.56\)</span>) <span class="math inline">\(97.72 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(2.80\)</span>) <span class="math inline">\(2.28 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-9.36\)</span>) <span class="math inline">\(0.0 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Bella</td>
<td style="text-align: center;">(<span class="math inline">\(-4.06\)</span>) <span class="math inline">\(0.02 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(4.48\)</span>) <span class="math inline">\(99.23 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-0.41\)</span>) <span class="math inline">\(0.75 \%\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Charlie</td>
<td style="text-align: center;">(<span class="math inline">\(0.01\)</span>) <span class="math inline">\(3.21 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(3.42\)</span>) <span class="math inline">\(96.68 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(-3.43\)</span>) <span class="math inline">\(0.10 \%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Doresa</td>
<td style="text-align: center;">(<span class="math inline">\(-15.12\)</span>) <span class="math inline">\(0.00 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(5.18\)</span>) <span class="math inline">\(0.85 \%\)</span></td>
<td style="text-align: center;">(<span class="math inline">\(9.94\)</span>) <span class="math inline">\(99.15 \%\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="politiske-kandidaters-svar" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="politiske-kandidaters-svar">16 politiske kandidaters svar</h2>
<p>Lad os se på et lidt større eksempel, nu med autentiske data fra en kandidattest til folketingsvalget i 2026. Vi ser på 16 kandidater og deres svar på to spørgsmål.</p>
<table class="table-bordered table">
<colgroup>
<col style="width: 10%">
<col style="width: 50%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Parti</th>
<th style="text-align: left;">Navn</th>
<th style="text-align: center;">Spørgsmål 1</th>
<th style="text-align: center;">Spørgsmål 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Soc</td>
<td style="text-align: left;">Ane Halsboe-Jørgensen</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
</tr>
<tr class="even">
<td>Soc</td>
<td style="text-align: left;">Flemming Møller Mortensen</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
<tr class="odd">
<td>Soc</td>
<td style="text-align: left;">Kiki Bille Bach</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
</tr>
<tr class="even">
<td>Soc</td>
<td style="text-align: left;">Morten Ryom</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
</tr>
<tr class="odd">
<td>Ven</td>
<td style="text-align: left;">Anita Vivi Lilholt</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Meget uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
</tr>
<tr class="even">
<td>Ven</td>
<td style="text-align: left;">Anne Honoré Østergaard</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Meget uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
</tr>
<tr class="odd">
<td>Ven</td>
<td style="text-align: left;">Marie Bjerre</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
<tr class="even">
<td>Ven</td>
<td style="text-align: left;">Mikkel Bisgaard</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
<tr class="odd">
<td>Enh</td>
<td style="text-align: left;">Peder Hvelplund</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Meget enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Meget enig}}\)</span></td>
</tr>
<tr class="even">
<td>Enh</td>
<td style="text-align: left;">Runa Friis Hansen</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Meget enig}}\)</span></td>
</tr>
<tr class="odd">
<td>Enh</td>
<td style="text-align: left;">Lasse P. N. Olsen</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Meget enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Enig}}\)</span></td>
</tr>
<tr class="even">
<td>Enh</td>
<td style="text-align: left;">Filippa Emilie Vittrup</td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Meget enig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#F288B9}{\textbf{Meget enig}}\)</span></td>
</tr>
<tr class="odd">
<td>DD</td>
<td style="text-align: left;">Inger Støjberg</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Meget uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
<tr class="even">
<td>DD</td>
<td style="text-align: left;">Kristian Bøgsted</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
<tr class="odd">
<td>DD</td>
<td style="text-align: left;">Kim Edberg Andersen</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Meget uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
<tr class="even">
<td>DD</td>
<td style="text-align: left;">Liselotte Lynge</td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Meget uenig}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\color{#8086F2}{\textbf{Uenig}}\)</span></td>
</tr>
</tbody>
</table>
<p>De to spørgsmål er</p>
<ul>
<li><p>Spørgsmål 1: De boligejere, der tjener mest på prisstigninger, skal betale mere i skat.</p></li>
<li><p>Spørgsmål 2: Reglerne for dyrevelfærd skal strammes, selv om det kan gøre fødevarer fra Danmark dyrere.</p></li>
</ul>
<p>Datasættet som Excelfil med værdier fra <span class="math inline">\(-2\)</span> (helt uenig) til <span class="math inline">\(2\)</span> (helt enig) er <a href="../undervisningsforlob/kandidattest/datasaet_16_personer.xlsx">her</a>.</p>
<p>For at skabe lidt overblik, vil et punktplot med <span class="math inline">\(x_1\)</span> på førsteaksen og <span class="math inline">\(x_2\)</span> på andenaksen, hvor punkterne har forskellige farver efter parti, være en god idé. Det er dog en udfordring, at flere punkter er ens.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Overvej, hvordan du vil håndtere de punkter, som har samme koordinater, så alle punkterne alligevel bliver synlige.</li>
<li>Tegn punktplottet (farv punkterne for Socialdemokratiet røde, Venstre blå, Enhedslisten grønne og Danmarksdemokraterne orange).</li>
</ul>
<details>
<summary>
Sådan gør du i GeoGebra
</summary>
<p><br>
Åbn datasættet i Excel og kopier det hele over i et "Regneark" i GeoGebra (tryk på "Vis" <span class="math inline">\(\rightarrow\)</span> "Regneark").</p>
<ul>
<li>Du laver et punkt i regnearket ved at skrive <code>=(B2,C2)</code> (hvis punktets førstekoordinat står i celle <code>B2</code> og andenkoordinaten står i <code>C2</code>).</li>
<li>Markér cellen. Tag ved den lille firkant nederst til højre og træk ned, så du får punkter for alle 16 kandidater.</li>
<li>Markér alle punkterne. Højreklik og vælg "Egenskaber". Sæt flueben ved "Fast objekt" (det sikrer, at du ikke ved en fejl kan flytte på punkterne). <em>Hvis</em> der er vist et navn ved punkterne i tegneblokken, fjerner du også fluebenet ved "Vis navn".</li>
<li>Markér de fire punkter i regnearket, som hører til Socialdemokratiet. Højreklik og vælg "Egenskaber". Under fanen "Farve" vælger du rød.</li>
<li>Farv på tilsvarende måde de andre punkter.</li>
</ul>
</details>
</div>
</div>
</div>
<p>Det skulle gerne være tydeligt, at de fire partiers kandidater ligger delvist opdelt efter parti. Vi vil nu gerne bruge samme type model som tidligere i en kunstig neuron til at undersøge, hvordan vi kan inddele <span class="math inline">\(xy\)</span>-planen i områder til hvert parti. Først skal vi have trænet modellen på data for de 16 politikere, så vi kender bias og vægte.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Brug kunstig neuron app’en på datasættet med samme indstillinger som i opgave 4.</li>
<li>Noter værdierne for bias og vægte for hvert parti, så <span class="math inline">\(s_0, s_1, s_2\)</span> er for Socialdemokratiet, <span class="math inline">\(v_0, v_1, v_2\)</span> er for Venstre og så videre. Det er en fordel, hvis du med det samme definerer værdierne i GeoGebra. Skriv for eksempel i inputfeltet: <code>s0=5.869</code> for at definere <span class="math inline">\(s_0\)</span>.</li>
</ul>
</div>
</div>
</div>
<p>Vi vil i det følgende lave en visualisering, som viser betydningen af de <span class="math inline">\(12\)</span> vægte, som du lige har fundet i opgave 6.</p>
<p>Husk på, at hvis man for en given værdi af <span class="math inline">\(x_1\)</span> og <span class="math inline">\(x_2\)</span> skal udregne scoren for Socialdemokratiet, så gør vi det på denne måde:</p>
<p><span class="math display">\[
s_0 + s_1  \cdot x_1 + s_2 \cdot x_2
\]</span> Hvis vi omdøber svaret på spørgsmål 1 (<span class="math inline">\(x_1\)</span>) til <span class="math inline">\(x\)</span>, svaret på spørgsmål 2 (<span class="math inline">\(x_2\)</span>) til <span class="math inline">\(y\)</span> og kalder den beregnede score for <span class="math inline">\(z\)</span>, så får vi ligningen:</p>
<p><span class="math display">\[
z = s_0 + s_1  \cdot x + s_2 \cdot y
\]</span></p>
<p>hvilket kan omskrives til</p>
<p><span class="math display">\[
s_0 + s_1  \cdot x + s_2 \cdot y -z =0
\]</span> Sammenholder vi det med planens ligning <span class="math inline">\(a \cdot x + b \cdot y + c \cdot z + d=0\)</span>, kan vi se, at scoren for Socialdemokratiet udgør en plan i rummet. Noget helt tilsvarende gør sig selvfølgelig gældende for de øvrige tre partier.</p>
<p>Vi vil nu tegne de fire planer:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Tegn de fire planer hørende til hver af de fire partier samtidig med, at du begrænser både <span class="math inline">\(x\)</span> og <span class="math inline">\(y\)</span> til at ligge mellem <span class="math inline">\(-2\)</span> og <span class="math inline">\(2\)</span>.</li>
<li>Farv planen for Socialdemokratiet rød, Venstre blå, Enhedslisten grøn og Danmarksdemokraterne orange.</li>
<li>Sørg for, at man kan se nok af <span class="math inline">\(z-aksen\)</span> til, at man ser hele udsnittet af planen for alle fire partier.</li>
</ul>
<details>
<summary>
Sådan gør du i GeoGebra
</summary>
<ul>
<li>For bare at tegne planen for Socialdemokratiet i GeoGebra uden begræsninger på <span class="math inline">\(x\)</span> og <span class="math inline">\(y\)</span>, kan man i inputfeltet blot skrive: <code>z=s0+s1*x+s2*y</code>. Sørg for at vælge "Vis" <span class="math inline">\(\rightarrow\)</span> "3D Grafik" for at få planen vist i et 3-dimensionelt koordinatsystem.</li>
<li>Hvis man skal have begrænsning med, definerer man scoren for Socialdemokratiet som en funktion af to variable: <code>soc(x,y)=s0+s1*x+s2*y,-2&lt;=x&lt;=2,-2&lt;=y&lt;=2</code>.</li>
<li>For at farve planen skal man højreklikke på definitionen af planen i "Algebra vindue" og vælge "Egenskaber". Her vælger man fanen "Farve". Sæt eventuelt "Opaliseret" til <span class="math inline">\(100\)</span> (det betyder, at planen ikke bliver gennemsigtig).</li>
</ul>
</details>
<p>Vi har i de tidligere opgaver set, at for et givent svar på hvert af de to spørgsmål, så vil det parti med den højeste score også give den største sandsynlighed.</p>
<p>I ethvert punkt i <span class="math inline">\(xy\)</span>-planen (svarende til konkrete svar på de to spørgsmål), er vi derfor nu interesseret i at finde ud af, hvilket parti, der har den største score (og dermed også den største sandsynlighed).</p>
<ul>
<li><p>Drej rundt i dit 3D-plot og prøv blandt andet at se "ned på" planerne (på den måde at <span class="math inline">\(z\)</span>-aksen peger direkte op i dine øjne – det svarer til, at du kigger direkte ned på <span class="math inline">\(xy\)</span>-planen). Her kan du se, at <span class="math inline">\(xy\)</span>-planen bliver inddelt i fire områder svarende til hver af de fire partier. Det parti med den højeste score svarer til den farve, som du kan se.</p></li>
<li><p>Hvilke partier støder op til hinanden, når du ser ned på de fire områder, som <span class="math inline">\(xy\)</span>-planen bliver inddelt i? Notér de tre kombinationer af partier ned.</p></li>
</ul>
</div>
</div>
</div>
<p>Vi skal nu have fundet de linjer, som giver den inddeling af <span class="math inline">\(xy\)</span>-planen, som du har fundet i opgaven ovenfor. Du har blandt andet set, at Socialdemokratiet og Enhedslisten støder op til hinanden. Grænsen mellem de to partier opstår præcist, når de to partier har samme score. Det vil sige, når</p>
<p><span class="math display">\[
s_0 + s_1 \cdot x + s_2 \cdot y = e_0 + e_1 \cdot x + e_2 \cdot y
\]</span></p>
<p>hvor <span class="math inline">\(x=x_1\)</span> og <span class="math inline">\(y=x_2\)</span>.</p>
<p>Hvis vi samler alt på venstre side, giver det</p>
<p><span id="eq-sammenlignSE"><span class="math display">\[
(s_0 - e_0) + (s_1-e_1) \cdot x + (s_2-e_2) \cdot y=0
\tag{1}\]</span></span></p>
<p>Læg mærke til, at det svarer til ligningen for en ret linje i planen på formen</p>
<p><span class="math display">\[
a \cdot x + b \cdot y + c = 0
\]</span></p>
<p>Vi vil nu tegne de tre linjer, som giver inddelingen af <span class="math inline">\(xy\)</span>-planen.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li><p>Bestem ved hjælp af (<a href="#eq-sammenlignSE" class="quarto-xref">1</a>) ligningen for hver af de tre linjer, som giver inddelingen af <span class="math inline">\(xy\)</span>-planen, som du fandt i opgave 7.</p></li>
<li><p>Indtegn de tre linjer i samme koordinatsystem som punktplottet, du lavede i opgave 5.</p></li>
</ul>
</div>
</div>
</div>
<p>Når man svarer på de to spørgsmål, har man egentlig kun følgende svarmuligheder: <span class="math inline">\(-2\)</span> (helt uenig), <span class="math inline">\(-1\)</span> (uenig), <span class="math inline">\(0\)</span> (hverken/eller), <span class="math inline">\(1\)</span> (enig) eller <span class="math inline">\(2\)</span> (helt enig). Vi forestiller os nu, at man kan vælge en vilkårlig værdi i intervallet <span class="math inline">\([-2,2]\)</span>. Det kunne for eksempel ske, hvis man skulle angive sit svar på hvert spørgsmål ved hjælp af en skyder, som illustreret her:</p>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="kandidattest/skyder.png" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Skyder som bruges til at angive, hvor enig man er i et spørgsmål på en kontinuert skala fra <span class="math inline">\(-2\)</span> til <span class="math inline">\(2\)</span>.</figcaption>
</figure>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Antag, at en person har svaret <span class="math inline">\(x=1\)</span> på det første spørgsmål.</p>
<ul>
<li><p>Hvad skal værdien af <span class="math inline">\(y\)</span> (det vil sige svaret på det andet spørgsmål) være, så scoren for Socialdemokratiet og Enhedslisten bliver lige store (brug de linjer, som du fandt i opgave 8)?</p></li>
<li><p>Brug <span class="math inline">\(x=1\)</span> og den <span class="math inline">\(y\)</span>-værdi, som du lige har bestemt til først at finde scoren og dernæst sandsynligheden for hvert af de fire partier.</p></li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 10 - valgfri
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>I opgave 7 tegnede du planer, som for ethvert punkt <span class="math inline">\((x,y)\)</span> viser scoren for hvert af de fire partier.</p>
<ul>
<li>Lav et plot tilsvarende det, du lavede i opgave 7, men som i stedet for scoren viser sandsynlighedsfladen for hvert af de fire partier.</li>
</ul>
<details>
<summary>
Sådan gør du i GeoGebra
</summary>
<p>For at tegne sandsynlighedsfladen for Socialdemokratiet skriver man i inputfeltet:</p>
<p><code>exp(soc(x,y))/(exp(soc(x,y))+exp(enh(x,y))+exp(ven(x,y))+exp(dd(x,y)))</code></p>
<p>hvor <code>enh(x,y)</code> beregner scoren for Enhedslisten og så videre.</p>
</details>
<ul>
<li><p>Drej rundt i dit 3D-plot og prøv igen at se direkte ned på <span class="math inline">\(xy\)</span>-planen. Får du samme inddeling af <span class="math inline">\(xy\)</span>-planen, som du fik i opgave 7? Hvorfor/hvorfor ikke?</p></li>
<li><p>Betragt de fire inddelinger af <span class="math inline">\(xy\)</span>-planen svarende til hvert af de fire partier. Hvor i hver inddeling er sandsynligheden for det pågældende parti størst? Og hvorfor giver det god mening?</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="det-helt-store-eksempel-med-877-politikere" class="level2">
<h2 class="anchored" data-anchor-id="det-helt-store-eksempel-med-877-politikere">Det helt store eksempel med 877 politikere</h2>
<p>Til sidst vil vi tage et kig på et autentisk datasæt af en mere relevant størrelse. Vi har <span class="math inline">\(877\)</span> politikere fordelt på <span class="math inline">\(12\)</span> partier, som inden folketingsvalget i 2026 har svaret på <span class="math inline">\(24\)</span> spørgsmål til TV2’s kandidattest.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 11
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Beregn hvor mange bias og vægte modellen nu har.</li>
</ul>
</div>
</div>
</div>
<p>Datasættet kan downloades <a href="../undervisningsforlob/kandidattest/datasaet_877_personer.xlsx">her</a>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 12
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Brug app’en til at træne en kunstig neuron ud fra datasættet. Vælg partibogstav som target-variabel og alle 24 spørgsmål som feature-variable.</li>
<li>Se på <a href="../noter/vurdering_model/vurdering_model.html#confusion-matrix" target="_blank">"Confusion matrix"</a> og <a href="../noter/vurdering_model/vurdering_model.html#klassifikationsnøjagtighed" target="_blank">"Klassifikationsnøjagtigheden"</a> i app’en. Overvej, hvad det siger om den trænede model.</li>
<li>Prøv at ændre på antal iterationer og på learning rate. Vi vil gerne have klassifikationsnøjagtigheden så høj som mulig.</li>
</ul>
</div>
</div>
</div>
<p>Hvis du har haft om <a href="https://aimat.dk/noter/krydsvalidering/krydsvalidering.html" target="_blank">krydsvalidering</a>, kan du desuden lave opgave 13.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opgave 13
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Evaluer modellen med 5-folds krydsvalidering i app’en.</li>
<li>Tag en snak om, hvordan resultatet bliver sammenlignet med svarene i opgave 12, og hvorfor det er tilfældet.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="delvis-facitliste" class="level2">
<h2 class="anchored" data-anchor-id="delvis-facitliste">Delvis facitliste</h2>
<p><a href="../undervisningsforlob/kandidattest/kandidattest_facit.html" target="_blank">Facitliste</a>.</p>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><img src="../logo/SVG/Bomaerke_03_AIMAT_2024.svg" class="footer-logo"> aimat.dk er finansieret af Novo Nordisk Fonden</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script src="../scripts/navbar-tooltips.js"></script>
<script src="../scripts/trim-categories.js"></script>




</body></html>