---
title: "Inddeling af musik i grupper"
description: "Vi vil se, hvordan man kan inddele musiknumre i grupper, f.eks. til at give anbefalingen i en musiktjeneste"
image: ""
categories:
  - B-niveau
  - Kort
---


::: {.callout-caution collapse="true" appearance="minimal"}
### Forudsætninger og tidsforbrug

- Afstand mellem punkter. 

**Tidsforbrug:** 2-3 timer

:::

::: {.purpose}

### Formål

I dette forløb vil vi se på, hvordan en algoritme, der hedder *K-means*, kan anvendes til at inddele musiknumre i grupper, f.eks. for at en musiktjeneste kan give anbefalinger til ny musik, som man sikkert gerne vil høre.
:::

## K-means til inddeling af musiknumre i grupper

For at kunne opdele musiknumre i grupper er det nødvendigt at finde nogle informationer/features til hvert nummer. En oplagt information kunne umiddelbart være musikgenre : rock, pop, klassisk, country m.m.. 

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 1: Musikfeatures
Overvej hvilke andre features man kan bruge til at opdele musiknumre efter.
:::

Opdelingen skal egentlig foretages af en computer, som også selv kan analysere musiknumrene og finde featureværdier. Nogle af de features, der benyttes er: Lydniveau, Energi, Instrumentalitet, Dansbarhed, Positivitet og Tempo.

For at anvende K-means her, bør hver feature enten være angivet på samme skala, f.eks. fra 0 til 1, eller ændres ved [feature-skalering](../materialer/afstande/feature_scaling.html), så hver feature får lige stor betydning. 

Her ses på et mindre eksempel med 15 musiknumre, man ønsker at opdele i 3 grupper ud fra 3 features : danceabilty, energy og speechiness.

Numrene er placeret i en tilfældig af de 3 grupper fra start, så algoritmen har et sted at starte. Opgaven er så, at numrene skal inddeles på en måde, så rimeligt ens numre er i samme gruppe. Der behøver ikke være lige mange numre i hver gruppe i den færdige inddeling, men der skal være 3 grupper med numre i vores eksempel.

| nummer  | danceability  | energy | speechiness| gruppe|
|--------|--------|--------|--------|--------|
|Barbie Girl|	0,76|	0,95|	0,04| 1|
|Shape of You|	0,83|	0,65|	0,08|2|
|Set Fire to the Rain|	0,60|	0,67|	0,02|3|
|Wake Me Up|	0,53|	0,78|	0,05|1|
|Baby One More Time|	0,76|	0,70|	0,03|2|
|Just The Way You Are|	0,64|	0,84|	0,04|3|
|New Rules|	0,76|	0,72|	0,07|1|
|Stan|	0,78|	0,74|	0,21|2|
|In Da Club|	0,90|	0,71|	0,37|3|
|Blinding Lights|	0,51|	0,80|	0,06|1|
|Blank Space|	0,76|	0,70|	0,05|2|
|Dance Monkey|	0,82|	0,59|	0,09|3|
|Hotline Bling|	0,90|	0,62|	0,06|1|
|Die To Live|	0,42|	0,97|	0,14|2|
|White Iverson|	0,67|	0,52|	0,04|3|

Ideen er nu, at vi udregner et centrum (gennemsnit) for alle numrene i gruppe 1, et andet gennemsnit for alle numrene i gruppe 2 og et tredje gennemsnit for alle numrene i gruppe 3. Derefter ser vi på hvert enkelt nummer og afgør, hvilket af de tre centre, numret ligger tættest på. Hvis numret ligger tættet på cemtrum for den gruppe, numret allerede er i, sker der ikke noget. Hvis numret derimod ligger tættet på centrum for en af de andre grupper, bliver numret flyttet til den pågældende gruppe.


::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 2: Opdeling af musiknumre i 3 grupper - beregn centrum
Ud fra skemaet overnfor ønsker vi nu at få beregnet centrum for hver af de tre grupper.
I tabellen her er centrum for gruppe 1 allerede beregnet.

| gruppe  | danceability  | energy | speechiness|
|--------|--------|--------|--------|--------|
|1 |	0,692|	0,774|	0,056| 
|2||||
|3||||
 * Beregn gennemsnittet af værdierne for danceability for gruppe 1. Se at det passer med værdien i tabellen. 
 * Beregn også gennemsnit for energy og speechiness for gruppe 1. Se at det passer med tabellens værdier.
 * Beregn på samme måde centrum (de tre gennemsnitsværdier) for gruppe 2 og gruppe 3. 
:::

Vi skal nu for hvert enkelt nummer have undersøgt, hvilket af de tre centre, numret ligger tættet på. Du kender allerede formlen for afstand mellem to punkter i planen, hvor hver punkt har to koordinater.
$$|PQ|= \sqrt{(x_2 - x_1)^2+(y_2 - y_1)^2}$$
Når der er flere koordinater, udvides formlen blot med flere led under kvadratrodstegnet. I vores eksempel er der de tre værdier danceability, energy og speechiness, så der bliver tre led.
$$|PQ|= \sqrt{(x_2)^2+(y_2 - y_1)^2+(z_2 - z_1)^2}$$

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 3: Beregn afstande til centre
Nu skal vi igang med at finde afstanden fra hvert nummer til hvert centrum. Her skal du selvfølgelig bruge resultatet fra opgave 2, hvor du fandt de tre centre.

| nummer  | afstand centrum 1  | afstand centrum 2 | afstand centrum 3|
|--------|--------|--------|--------|--------|
|Barbie Girl|	0,189|	0,213|	0,295|
|Shape of You|	|	|	|

 * Beregn afstanden fra \"Barbie girl\" til hver af de 3 centre og tjek, at det er korrekt.
 * Beregn afstand fra \"Shape of You\" til hver af de 3 centre. 
:::


::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 4: Bestemmelse af nye grupper
Herunder er afstanden til de tre centre beregnet for alle numrene. 

| nummer  | afstand centrum 1  | afstand centrum 2 | afstand centrum 3|gruppe |ny gruppe|
|--------|--------|--------|--------|--------|--------|
|Barbie Girl|	0,189|	0,213|	0,295|1||
|Shape of You|	0,187|	0,159|	0,110|2||
|Set Fire to the Rain|	0,143|	0,160|	0,156|3||
|Wake Me Up|	0,162|	0,189|	0,235|1||
|Baby One More Time|	0,104|	0,102|	0,095|2||
|Just The Way You Are|	0,086|	0,128|	0,207|3||
|New Rules|	0,088|	0,067|	0,076|1||
|Stan	|0,181|	0,129|	0,134|2||
|In Da Club|	0,382|	0,331|	0,314|3||
|Blinding Lights|	0,184|	0,210|	0,259|1||
|Blank Space|	0,101|	0,089|	0,078|2||
|Dance Monkey|	0,227|	0,196|	0,123|3||
|Hotline Bling|	0,259|	0,235|	0,187|1||
|Die To Live|	0,346|	0,365|	0,432|2||
|White Iverson|	0,255|	0,243|	0,172|3||

 * Bestem ny gruppe for hvert nummer - det centrum, som numret er tættest på.
 * Overvej, hvorfor vi ikke dermed er færdige med at opdele numrene i de 3 ønskede grupper. 
:::

Beregningerne skal så gentages, typisk mange gange, indtil der ingen ændringer sker. Når algoritmen har fået inddelt alle numrene i tre grupper, så yderligere en omgang beregninger ikke flytter numre mellem grupperne, er algoritmen færdig. Men det kan godt kræve rigtigt mange beregninger, som vi derfor ikke vil lave manuelt.

Hvis du er god til regneark, f.eks. i Excel, kan du få Excel til smart at lave beregningerne. Her vil vi dog i stedet bruge det gratis program **Orange**, som vi også bruger til andre forløb på aimat.dk

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 5: Endelig opdeling med brug af Orange.

* Installer [Orange](https://orangedatamining.com/). Du kan få hjælp til at installere programmet [her](https://www.youtube.com/watch?v=g8-wIwVfAw0).

* Se denne video <<link mangler>>

* Lav selv samme løsning i Orange for at få den endelige opdeling i de tre ønskede grupper.

* Hvis du kender numrene, kan du overveje, om inddelingen er fornuftig. Sæt gerne en "titel" på hver af grupperne.

:::

Som et alternativ til Orange eller Excel, kan du også bede en AI chatbot om at lave K-means på vores data. Det er let, men giver heller ikke selv kontrol med, hvad der foregår, eller om det gøres korrekt. 


::: {.callout-note collapse="false" appearance="minimal"}
### Ekstraopgave : Beregning af SUMPAR (svær)

 * Læs [noten Clustering med K-means](../materialer/kmeans/kmeans.qmd) .
 * Beregn SAUMPAR ud fra grupperne fra starten. 
 * Beregn ligeledes SUMPAR ud fra de grupper de efterfølgende kom i.
 * Hvis man sammenligner de to resultater, viser det så det ønskede ?
:::
