---
title: "Valg af parti"
description: 'I dette forløb vil vi se på en metode til at forudsige, hvilket parti man vil stemme på ud fra svar på en række spørgsmål.'
image: ""
categories:
  - "01_A-niveau"
  - "04_Kort"
---

::: {.callout-caution collapse="true" appearance="minimal"}
### Forudsætninger og tidsforbrug

+ Eksponentialfunktioner, herunder $\mathrm{e}^x$.
+ Sandsynlighedsfelter.
+ Linjens ligning på formen $a \cdot x + b \cdot y + c = 0$.

Hvis man forinden har arbejdet med det korte forløb [Sengetester i IKEA](https://aimat.dk/undervisningsforlob/sengetester.html), vil det være en fordel, men det er ikke en forudsætning.

På tilsvarende vis vil det også gøre dette forløb lidt lettere, hvis man forinden har arbejdet med de første dele af det lange forløb om [Kunstige neuroner](https://aimat.dk/undervisningsforlob/kunstige_neuroner_langt_forlob/kunstige_neuroner_forside.html), men det er heller ikke en forudsætning.

Hvis man har arbejdet med det korte forløb [Hvilken politiker er du mest enig med](https://aimat.dk/undervisningsforlob/kandidattest.html), kan konteksten være mere tydelig, men det er igen heller ikke en forudsætning.

**Tidsforbrug:** Ca. 150 minutter.

:::

::: {.purpose}

### Formål

Formålet med dette forløb er 

* at lære **softmax** at kende som et værktøj til **multipel klassifikation**.
* at lære lidt om **kunstige neuroner**, samt at anvende en app til at træne en kunstig neuron.
* at undersøge, hvordan en kunstig neuron til multipel klassifikation kan bruges til at forudsige, hvilket parti man vil stemme på ud fra svar på en række spørgsmål, som det for eksempel gøres i kandidattests.

:::

## Softmax modellen

Vi vil gerne lave en model, som kan forudsige, hvilket parti man vil stemme på, baseret på svarene fra en række spørgsmål. Det er for eksempel det, der sker, når diverse medier laver kandidattests i forbindelse med valg. Testene fungerer som regel på
den måde, at man bliver stillet en række forskellige spørgsmål, og så
skal man svare på en skala fra \"helt uenig\" til \"helt enig\". Disse
kategorier af svar kan for eksempel oversættes til matematik[^overs] på denne måde:

| Helt uenig | Uenig | Hverken/eller | Enig | Helt enig |
|:---:|:---:|:---:|:---:|:---:|
| $-2$ | $-1$ | $0$ | $1$ | $2$ |
: {.bordered}

[^overs]: I nogle kandidattests kan man ikke vælge \"Hverken/eller\", men de resterende kategorier oversættes stadig til negative og positive værdier, som det er eksemplificeret i tabellen.

Vi starter med et meget lille fiktivt eksempel, hvor fire personer: Andy, Bella, Charlie og Doresa, har svaret på to spørgsmål samt angivet, hvilket parti de stemmer på. 

Vi forestiller os, at de to spørgsmål er:

* Spørgsmål 1:  Topskatten skal sættes op.

* Spørgsmål 2:  Danske virksomheder skal pålægges en CO2-afgift.

Vi vil så indføre to variable $x_1$ og $x_2$, hvor

- $x_1$: svaret på \"Topskatten skal sættes op\" angivet
på en skala fra $-2$ til $2$.

- $x_2$: svaret på \"Danske virksomheder skal pålægges en CO2-afgift\" angivet på en skala fra $-2$ til $2$.

Vi lader som om, at partierne er **S** (Socialdemokratiet), **E**(Enhedslisten) og **V** (Venstre). Det parti, som en given person vil stemme på, vil vi kalde for $t$ (som står for **targetværdi**). Andy, Bella, Charlie og Doresa har nu svaret følgende:

| Navn | Spørgsmål 1 $(x_1)$ | Spørgsmål 2 $(x_2)$ | Parti ($t$) |
|-------|:-----------|:-----------|:-----------:|
| Andy | $\color{#F288B9}{\textrm{Helt uenig } (-2)}$ |  $\color{#F288B9}{\textrm{ Helt uenig } (-2)}$ | **V** |
| Bella | $\color{#F288B9}{\textrm{Uenig } (-1)}$ | $\color{#8086F2}{\textrm{Enig } (1)}$ | **S** |
| Charlie | $\color{#F288B9}{\textrm{Uenig } (-1)}$ |  $\color{#F288B9}{\textrm{Uenig } (-1)}$ | **S** |
| Doresa | $\color{#8086F2}{\textrm{Enig } (1)}$ |  $\color{#8086F2}{\textrm{Helt enig } (2)}$ | **E**|
: {.bordered}

Bemærk her, at svarene \"Helt uenig\" og \"Uenig\" er farvet lyserøde, mens \"Helt enig\" og \"Enig\" er farvet lyseblå.

Vi vil nu lave en model, hvor man ud fra de svar, man giver på de to spørgsmål, kan forudsige, hvor sandsynligt det er, at man stemmer på hvert af de tre partier. Vi vil træne modellen, så den passer godt til svarene fra de fire personer og derefter håbe, at den også vil passe godt til andre personer. Naturligvis er to spørgsmål og fire personer alt for lidt, men det gør vi noget ved senere.

Vi udregner så for enhver kombination af person og parti en score:

$$
\textrm{score}(\textrm{person, parti}) = w_0 + w_1 \cdot x_1+ w_2 \cdot x_2
$$

hvor $w_0$ kaldes for bias og $w_1$ og $w_2$ kaldes for vægte.

Bias og vægte kan være forskellige for hvert parti, så vi kalder dem for $s_0, s_1, s_2$ (Socialdemokratiet), $e_0, e_1, e_2$ (Enhedslisten) og $v_0, v_1, v_2$ (Venstre). 

Vi sætter disse bias og vægte til nogle lidt tilfældige værdier til at starte med.

| Parti | $w_0$ | $w_1$ | $w_2$ |
|:---:|:---:|:---:|:---:|
| **V** | $v_0 = 0$ | $v_1 = -1$ | $v_2 = 0$ | 
| **S** | $s_0 = 0$ | $s_1 = 1$ | $s_2 = 0$ |
| **E**| $e_0 = 0$ | $e_1 = 0$ | $e_2 = 0$ |
: {.bordered}

For Andy kan vi så udregne:

$$
\begin{aligned}
&\textrm{score}(\textrm{Andy, V}) = 0 + (-1) \cdot (-2) + 0 \cdot (-2) = 2 \\
&\textrm{score}(\textrm{Andy, S}) = 0 + 1 \cdot (-2) + 0 \cdot (-2) = -2 \\
&\textrm{score}(\textrm{Andy, E}) = 0 + 0 \cdot (-2) + 0 \cdot (-2) = 0
\end{aligned}
$$

Så lige nu er den højeste score for Andy for **V**, hvilket er godt, da han faktisk stemmer på Venstre. 

Men modellen skulle jo ikke kun give en score, men faktisk give en sandsynlighed for hvert parti. Så vi skal have fundet en metode til at få sandsynlighed i stedet for scores. Om sandsynlighederne ved vi, at de skal være positive, ligge mellem $0$ og $1$ og tilsammen give $1$.

En simpel måde at få tallene positive på er at opløfte $\mathrm{e}$ i scoren. 

$$
\begin{aligned}
\mathrm{e}^2 & \approx  7.389 \\ 
\mathrm{e}^{-2} & \approx 0.135 \\ 
\mathrm{e}^0 &=1
\end{aligned}
$$

Så lægges de tre tal sammen og hvert af tallene divideres med summen:

$$
\textrm{sum}=7.389 + 0.135 + 1 = 8.524
$$

For Andy giver det følgende:

| Parti | Score | $\mathrm{e}^{\textrm{score}}$ | Sandsynlighed |
|:---:|:---:|:---:|:---:|
| **V** | $2$ | $7.389$ | $\frac{7.389}{8.524} \approx 86.68 \%$ |
| **S** | $-2$ | $0.135$ | $\frac{0.135}{8.524} \approx 1.59 \%$ |
| **E**| $0$ | $1$ | $\frac{1}{8.524} \approx 11.73 \%$ |
: {.bordered}

Så med de valgte værdier af bias og vægte, angiver modellen en sandsynlighed på $86.68 \%$ for **V**, $1.59 \%$ for **S** og $11.73 \%$ for **E** for Andy. Da han faktisk stemte på **V**, er det jo rigtigt fint, uden dog at være helt perfekt, da vi helst ville have endnu større sandsynlighed for Venstre for Andy.

Denne metode til at omregne fra score til sandsynligheder kaldes for **softmax**.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 1

- Lav de tilsvarende udregninger for Bella, Charlie og Doresa.
- Overvej derefter, om de valgte vægte er fornuftige -- i den betydning, at modellen giver størst sandsynlighed for det parti, som personen faktisk stemmer på.

:::

Det var åbenlyst ikke så godt for Bella, Charlie og Doresa, da modellen for alle tre peger på et forkert parti. Idéen er nu, at vi skal ændre bias og vægte, så modellen bliver bedre. 

Lad os i første omgang se på $w_1$ og dermed $x_1$. Bemærk, at $x_1 = -2$ for Andy, at $x_1 = -1$ for Bella og Charlie, og at $x_1 = 1$ for Doresa. Da vi gerne vil have Andy til at få en høj score, og dermed en høj sandsynlighed for Venstre, giver det mening at lade $v_1$ være en negativ værdi, så $v_1 \cdot x_1$ bliver positiv. Før havde vi sat $v_1=-1$, men lad os forstærke effekten med $v_1 = -3$, så scoren for Andy bliver højere. 

Det giver Andy en positiv score $v_1 \cdot x_1 = -3 \cdot (-2) = 6$ for Venstre, hvilket er godt, da vi gerne vil have, at modellen peger på Venstre for ham.

Det giver Doresa en negativ score $v_1 \cdot x_1 = -3 \cdot 1= -3$, hvilket også er godt, da vi gerne vil have, at modellen ikke peger på Venstre for hende.

Det giver så desværre både Bella og Charlie en positiv score, da $v_1 \cdot x_1 = -3 \cdot (-1) = 3$, hvilket ikke er så godt, da vi gerne vil have, at modellen ikke peger på Venstre for dem. Det venter vi lige med at gøre noget ved, da vi starter med at få modellen til at pege på Enhedslisten for Doresa.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 2

- Overvej hvilken værdi $e_1$ kan gives, så Doresa får en positiv score for Enhedslisten, mens de øvrige tre får en negativ score? 
- Vælg vægten, så scoren for Doresa for Enhedslisten bliver $6$, som scoren for Andy blev for Venstre.
- Beregn score og sandsynlighed for hver af de tre partier for Doresa med den værdi, du har valgt (husk, at vi har sat $v_1=-3$).

:::

Samlet ser det nu således ud, hvor både (score) og sandsynlighed er angivet for hvert parti.

| Person  | Venstre | Socialdemokratiet | Enhedslisten |
|:-:|:-:|:-:|:-:|
| Andy | ($6$) $99.97 \%$ | ($-2$) $0.03 \%$ | ($-12$) $0.00 \%$ |
| Bella | ($3$) $98.19 \%$ | ($-1$) $1.80 \%$ | ($-6$) $0.01 \%$ |
| Charlie | ($3$) $98.19 \%$ | ($-1$) $1.80 \%$ | ($-6$) $0.01 \%$ |
| Doresa | ($-3$) $0.01 \%$ | ($1$) $0.67 \%$ | ($6$) $99.32 \%$ |
: {.bordered}

Vi skal nu have modellen til at vælge Socialdemokratiet for Bella og Charlie, men uden at ødelægge, at modellen vælger Venstre til Andy og Enhedslisten til Doresa. 

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 3

- Overvej, hvilken værdi biaset $s_0$ kan gives, så Bella og Charlie scorer højst for Socialdemokratiet (scoren skal over $3$, da de allerede har scoren $3$ for parti Venstre), men uden at scoren for Andy eller Doresa bliver højst for Socialdemokratiet (de har begge $6$ som højst score til henholdsvis Venstre og Enhedslisten).

:::

Med en fornuftig værdi af bias for Socialdemokratiet (for eksempel på $4.5$) kan tabellen komme til at se således ud:

| Person | Venstre | Socialdemokratiet | Enhedslisten |
|:-:|:-:|:-:|:-:|
| Andy | ($6$)  $97.07 \%$ | ($2.5$) $2.93 \%$ | ($-12$) $0.00 \%$ |
| Bella | ($3$) $37.75 \%$ | ($3.5$) $62.24 \%$ | ($-6$) $0.00 \%$ |
| Charlie | ($3$) $37.75 \%$ | ($3.5$) $62.24 \%$ | ($-6$) $0.00 \%$ |
| Doresa | ($-3$) $0.01 \%$ | ($5.5$) $37.75 \%$ | ($6$) $62.24 \%$ |
: {.bordered}

Men det kan stadig gøres bedre, blandt andet ved også at tage $w_2$ i brug.


## Brug af app til træning af kunstig neuron
Med det meget lille, simple eksempel kunne vi altså godt justere vægtene manuelt og få et nogenlunde resultat. Men hvis der bliver $100$, $1000$ eller millioner af vægte, så er det næppe en god idé. Det kræver noget lidt mere avanceret matematik, som vi ikke vil gennemgå i dette forløb. Du kan læse mere om dette i noten om [Kunstige neurale netværk til multipel klassifikation](https://aimat.dk/noter/softmax/softmax.html).

I stedet vil vi bruge en app til formålet. Du finder appen [her](https://apps01.math.aau.dk/ai/multi-neuron/) og datasættet som Excel fil [her](valg_af_parti/datasæt_4_personer.xlsx).


::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 4

- Åbn app'en og indlæs datasættet.
- Vælg $t$ som target-variabel og både $x_1$ og $x_2$ som feature-variable.
- Sæt learning rate til $0.1$ og antal iterationer til $1000$.
- Træn modellen.
- Sammenlign de værdier til bias og vægte, som app'en er nået frem til, med de værdier, som vi manuelt nåede frem til. Meget ligner det, vi fandt manuelt, men noget er også lidt anderledes.

:::

Med app'ens værdier ser tabellen endelig således ud, hvilket må siges at være meget tilfredsstillende.

| Person  | Venstre | Socialdemokratiet | Enhedslisten |
|:-:|:-:|:-:|:-:|
| Andy | ($6.56$)  $97.72 \%$ | ($2.80$) $2.28 \%$ | ($-9.36$) $0.0 \%$ |
| Bella | ($-4.06$) $0.02 \%$ | ($4.48$) $99.23 \%$ | ($-0.41$) $0.75 \%$ |
| Charlie | ($0.01$) $3.21 \%$ | ($3.42$) $96.68 \%$ | ($-3.43$) $0.10 \%$ |
| Doresa | ($-15.12$) $0.00 \%$ | ($5.18$) $0.85 \%$ | ($9.94$) $99.15 \%$ |
: {.bordered}

## 16 politiske kandidaters svar
Lad os se på et lidt større eksempel, nu med autentiske data fra en kandidattest til folketingsvalget i 2026. Vi ser på 16 kandidater og deres svar på 2 spørgsmål.

| Parti | Navn | Spørgsmål 1 | Spørgsmål 2 |
|-------|:---------------------------|:-----------:|:-----------:|
| Soc | Ane Halsboe-Jørgensen | $\color{#8086F2}{\textbf{Enig}}$ | $\color{#8086F2}{\textbf{Enig}}$ |
| Soc | Flemming Møller Mortensen | $\color{#F288B9}{\textbf{Uenig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |
| Soc | Kiki Bille Bach | $\color{#8086F2}{\textbf{Enig}}$ | $\color{#8086F2}{\textbf{Enig}}$ |
| Soc | Morten Ryom | $\color{#8086F2}{\textbf{Enig}}$ | $\color{#8086F2}{\textbf{Enig}}$ |
| Ven | Anita Vivi Lilholt | $\color{#F288B9}{\textbf{Meget uenig}}$ | $\color{#8086F2}{\textbf{Enig}}$ |
| Ven | Anne Honoré Østergaard | $\color{#F288B9}{\textbf{Meget uenig}}$ | $\color{#8086F2}{\textbf{Enig}}$ |
| Ven | Marie Bjerre | $\color{#8086F2}{\textbf{Enig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |
| Ven | Mikkel Bisgaard | $\color{#F288B9}{\textbf{Uenig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |
| Enh | Peder Hvelplund | $\color{#8086F2}{\textbf{Meget enig}}$ | $\color{#8086F2}{\textbf{Meget enig}}$ |
| Enh | Runa Friis Hansen | $\color{#8086F2}{\textbf{Enig}}$ | $\color{#8086F2}{\textbf{Meget enig}}$ |
| Enh | Lasse P. N. Olsen | $\color{#8086F2}{\textbf{Meget enig}}$ | $\color{#8086F2}{\textbf{Enig}}$ |
| Enh | Filippa Emilie Vittrup | $\color{#8086F2}{\textbf{Meget enig}}$ | $\color{#8086F2}{\textbf{Meget enig}}$ |
| DD | Inger Støjberg | $\color{#F288B9}{\textbf{Meget uenig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |
| DD | Kristian Bøgsted | $\color{#F288B9}{\textbf{Uenig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |
| DD | Kim Edberg Andersen | $\color{#F288B9}{\textbf{Meget uenig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |
| DD | Liselotte Lynge | $\color{#F288B9}{\textbf{Meget uenig}}$ | $\color{#F288B9}{\textbf{Uenig}}$ |

: {tbl-colwidths="[10, 50, 20, 20]" .bordered}

De to spørgsmål er

* Spørgsmål 1: De boligejere, der tjener mest på prisstigninger, skal betale mere i skat. 

* Spørgsmål 2: Reglerne for dyrevelfærd skal strammes, selv om det kan gøre fødevarer fra Danmark dyrere.

Datasættet som Excelfil med værdier fra $-2$ (helt uenig) til $2$ (helt enig) er   [her](/undervisningsforlob/valg_af_parti/datasæt_16_personer.xlsx).

For at skabe lidt overblik, vil et punktplot med $x_1$ på førsteaksen og $x_2$ på andenaksen, hvor punkterne har forskellige farver efter parti, være en god idé. Det er dog en udfordring, at flere punkter er ens.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 5

- Overvej, hvordan du vil håndtere de punkter, som har samme koordinater, så alle punkterne alligevel bliver synlige.
- Tegn punktplottet.

:::

Det skulle gerne være tydeligt, at de fire partiers kandidater ligger delvist opdelt efter parti. Vi vil nu gerne bruge samme type model som tidligere i en kunstig neuron til at undersøge, hvordan vi kan inddele $xy$-planen i områder til hvert parti. Først skal vi have trænet modellen på data for de 16 politikere, så vi kender bias og vægte.


::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 6

- Brug kunstig neuron appen på datasættet med samme indstillinger som i opgave 4.
- Noter værdierne for bias og vægte for hvert parti, så $s_0, s_1, s_2$ for Socialdemokratiet, $v_0, v_1, v_2$ for Venstre og så videre.

:::

Vi vil nu bruge disse vægte til at bestemme, hvor i koordinatsystemet modellen vil trække en grænse mellem Socialdemokratiet og Enhedslisten. Grænsen skal netop være der, hvor de to partier har ens score og derfor er lige sandsynlige, så

$$
\mathrm{e}^{s_0 + s_1 \cdot x_1 + s_2 \cdot x_2} = \mathrm{e}^{e_0 + e_1 \cdot x_1 + e_2 \cdot x_2}
$$

Hvis vi tager den naturlige logaritme på begge sider og samler alt på den ene side, giver det

$$
(s_0 - e_0) + (s_1-e_1) \cdot x_1 + (s_2-e_2) \cdot x_2=0
$$

Vi bemærker, at det svarer til ligningen for en ret linje på formen 

$$ 
a \cdot x + b \cdot y + c = 0
$$


::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 7

- Indsæt værdierne for bias og vægte i linjens ligning.
- Indtegn linjen i samme koordinatsystem som punktplottet.

:::

Det var en opdeling mellem Socialdemokratiet og Enhedslisten. Lad os se på de øvrige par af partier også.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 8

- Hvor mange forskellige par af partier er der, og hvor mange andre ligninger for linjer bør derfor bestemmes?
- Bliver alle disse linjer en grænse mellem områder, hvor de to partier er de mest sandsynlige?

:::

Hvis du vil, kan du selv beregne ligningerne for de øvrige linjer -- ellers er alle ligningerne angivet i denne tabel.

| Partier | Ligning |
|-------|:---------------------------|
| **S** og **E**| $-5.39979 \cdot x - 5.95406 \cdot y + 14.0861 = 0$ |
| **S** og **V** | $1.00714 \cdot x + 0.58677 \cdot y + 0.1452 = 0$ |
| **S** og **D**| $5.40031 \cdot x + 4.88754 \cdot y + 9.2446 = 0$ |
| **E**og **V** | $-6.40693 \cdot x - 6.54083 \cdot y + 13.9409 = 0$ |
| **E**og **D**| $10.8001 \cdot x + 10.8416 \cdot y - 4.8415 = 0$ |
| **V** og **D**| $4.39317 \cdot x + 4.30077 \cdot y + 9.0994 = 0$ |
: {.bordered}

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 9

- Indtegn alle seks linjer i punktplottet.
- Overvej hvilke af linjerne, der giver en grænse mellem to partier som mest sandsynlige, og hvilke linjer, der blot er mellem to lige sandsynlige partier, hvor et tredje parti er mere sandsynligt.

:::

De tre linjer for Socialdemokratiet & Venstre, Socialdemokratiet & Danmarksdemokraterne og Venstre & Danmarksdemokraterne skærer hinanden i samme punkt (eventuelt ikke helt perfekt på grund af afrunding).

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 10

- Bestem koordinaterne til dette punkt.
- Beregn derefter sandsynligheden for hvert af de fire partier (brug vægtene fra app'en) i punktet.
- Forklar, hvad det fortæller om modellen.

:::


## Det helt store eksempel med 877 politikere

Til sidst vil vi tage et kig på et autentisk datasæt af en mere relevant størrelse. Vi har $877$ politikere fordelt på $12$ partier, som inden folketingsvalget i 2026 har svaret på $24$ spørgsmål til TV2's kandidattest.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 11

- Beregn hvor mange bias og vægte modellen nu har.

:::

Datasættet kan downloades [her](/undervisningsforlob/valg_af_parti/datasæt_877_personer.xlsx).

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 12

- Brug app'en til at træne en kunstig neuron ud fra datasættet. Vælg partibogstav som target-variabel og alle 24 spørgsmål som feature-variable. 
- Se på \"Confusion matrix\" og \"Klassifikationsnøjagtigheden\" i app'en. Overvej, hvad det siger om den trænede model.
- Prøv at ændre på antal iterationer og på learning rate. Vi vil gerne have klassifikationsnøjagtigheden så høj som mulig.

:::

Hvis du har haft om [krydsvalidering](https://aimat.dk/noter/krydsvalidering/krydsvalidering.html), kan du desuden lave opgave 13.

::: {.callout-note collapse="false" appearance="minimal"}
### Opgave 13

- Træn modellen med krydsvalidering med 5 fold i app'en.
- Tag en snak om, hvordan resultatet bliver sammenlignet med svarene i opgave 12, og hvorfor det er tilfældet.

:::


## Delvis facitliste

[Facitliste](valg_af_parti/valg_af_parti_facit.qmd){target="_blank"}.

