---
title: 'Facit til forløbet \"Cambridge Analytica skandalen - informatik\"'
description: ''
image: ""
categories:
---


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 1


### Openness

* I have a vivid imagination.
* I am not interested in abstract ideas. 
* I have difficulty understanding abstract ideas. 
* I do not have a good imagination.

### Conscientiousness

* I get chores done right away. 
* I often forget to put things back in their proper place.
* I like order.
* I make a mess of things.


### Extraversion

* I don't talk a lot.
* I talk to a lot of different people at parties.
* I keep in the background.
* I am the life of the party.

### Agreeableness

* I sympathize with others' feelings.
* I am not interested in other people's problems.
* I feel others' emotions.
* I am not really interested in others.


### Neuroticism

* I have frequent mood swings.
* I am relaxed most of the time. 
* I get upset easily.
* I seldom feel blue.

:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 2

Numrene i parentes svarer til den rækkefølge, spørgsmålene kan stilles i.

### Neuroticism

<table class="tabel-kanter">
  <tr>
    <td> &plus; keyed </td> 
    <td class="table-left"> <span>(1)</span> I have frequent mood swings. <br>
         <span>(3)</span> I get upset easily.
 </td> 
  </tr>
  <tr>
    <td> &minus; keyed </td> 
    <td class="table-left"> <span>(2)</span> I am relaxed most of the time. <br>
         <span>(4)</span> I seldom feel blue.
 </td> 
  </tr>
</table>

\

### Agreeableness

<table class="tabel-kanter">
  <tr>
    <td> &plus; keyed </td> 
    <td class="table-left"> <span>(5)</span> I sympathize with others' feelings. <br>
         <span>(7)</span> I feel others' emotions.
 </td> 
  </tr>
  <tr>
    <td> &minus; keyed </td> 
    <td class="table-left"> <span>(6)</span> I am not interested in other people's problems. <br>
         <span>(8)</span> I am not really interested in others.
 </td> 
  </tr>
</table>

\

### Extraversion

<table class="tabel-kanter">
  <tr>
    <td> &plus; keyed </td> 
    <td class="table-left"> <span>(10)</span> I talk to a lot of different people at parties. <br>
         <span>(12)</span> I am the life of the party.
 </td> 
  </tr>
  <tr>
    <td> &minus; keyed </td> 
    <td class="table-left"> <span>(9)</span> I don't talk a lot. <br> 
         <span>(11)</span> I keep in the background.
 </td> 
  </tr>
</table>

\


### Conscientiousness

<table class="tabel-kanter">
  <tr>
    <td> &plus; keyed </td> 
    <td class="table-left"> <span>(13)</span> I get chores done right away. <br>
         <span>(15)</span> I like order.
 </td> 
  </tr>
  <tr>
    <td> &minus; keyed </td> 
    <td class="table-left"> <span>(14)</span> I often forget to put things back in their proper place. <br>
         <span>(16)</span> I make a mess of things.
 </td> 
  </tr>
</table>

\


### Openness

<table class="tabel-kanter">
  <tr>
    <td> &plus; keyed </td> 
    <td class="table-left"> <span>(17)</span> I have a vivid imagination.
 </td> 
  </tr>
  <tr>
    <td> &minus; keyed </td> 
    <td class="table-left"> <span>(18)</span> I am not interested in abstract ideas. <br>
         <span>(19)</span> I have difficulty understanding abstract ideas. <br>
         <span>(20)</span> I do not have a good imagination.
 </td> 
  </tr>
</table>


:::