---
title: "Del 1: Simple sprogmodeller"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

::: {.estimeret_tid}

Forventet tid ca. 60 min.

:::

{{< include ../space.qmd >}}

## Aktivitet 1 - Introduktion {.aimat}

Læs noten om [introduktion til sprogmodeller](../../noter/sprogmodeller/intro.qmd) eller se videoen her:

{{< video https://www.youtube.com/embed/zbtxV5DNqV4 >}}

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 1: Arbejdsspørgsmål til noten
Forklar med dine egne ord, hvad følgende betyder:

  - Syntaks
  - Semantik
  - Prædiktion
  - Tekstkorpus

:::

{{< include ../space.qmd >}}

## Aktivitet 2 - Simple sprogmodeller {.aimat}

Læs noten [simple sprogmodeller](../../noter/sprogmodeller/simple.qmd) eller se videoen her:

{{< video https://www.youtube.com/embed/OiRUJsJdOtQ >}}

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 2: N-gram sprogmodeller

* Forklar, hvad en bigram- og en trigram sprogmodel er.

:::

I noten om [simple sprogmodeller](../../noter/sprogmodeller/simple.qmd) findes nedestående tabel, som viser hyppigheden af det lille tekstkorpus, som noten tog udgangspunkt i. Vi får brug for tabellen i næste opgave.

{{< include ../../noter/sprogmodeller/simple_trigram_tabel.qmd >}}


::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 3: Prædiktion af næste ord

Du skal prøve at prædiktere næste ord i en sætning på 8 ord, som starter med \"en hund\" ved hjælp af @tbl-hyp_trigram. Det kan være en fordel at printe [dette klip-selv ark](trigram_klipselv.pdf) og klippe de forskellige ord ud.

Ved hjælp af @tbl-hyp_trigram kan vi se, at efter \"en hund\" er der mulighed for følgende ord: \"en\", \"løber\" og \"efter\" med sandsynlighed $1/4$, $1/4$ og $1/2$. 

* Læg derfor følgende ord i en bunke på bordet:

::: {.llm_saetninger}
[  en  ]{.boxed_inline} [ løber ]{.boxed_inline} [ efter ]{.boxed_inline} [ efter ]{.boxed_inline}  
:::

* Træk et tilfældigt ord fra bunken. 
   
Nu har du prædikteret det næste ord. Afhængigt af, hvilket ord du trak, skal du finde den relevante linje i tabellen, lægge de mulige næste ord op, og trække et tilfældigt ord igen, så du har 4 ord i sætningen. Fortsæt på denne måde, indtil du har prædikteret 6 nye ord, og dermed har 8 ord i alt.
   
* Giver din sætning mening? Hvis din sætning ikke giver mening, hvor i sætningen ryger meningen så (i starten, i midten, til slut, i hele sætningen)? Kan du komme med et bud på, hvorfor det forholder sig sådan?


:::

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 4: Prædiktion af næste ord på mobiltelefonen

De fleste mobiltelefoner kommer med et bud på, hvad det næste ord i en sætning kan være, når man for eksempel skriver en sms. Hvis din lærer giver lov, så prøv din telefons sprogmodel af:

* Skriv en sms, hvor du starter med et valgfrit første ord. Herefter må du kun vælge de ord, som din mobil foreslår. Skriv gerne en længere sætning.

* Giver din sætning mening? 

* Hvis din sætning ikke giver mening, hvor i sætningen ryger meningen så (i starten, i midten, til slut, i hele sætningen)? Kan du komme med et bud på, hvorfor det forholder sig sådan?

:::

{{< include ../space.qmd >}}

[$\leftarrow$ Forrige](sprogmodeller_forside.qmd){.prev}
[Næste $\rightarrow$](sprogmodeller_del2.qmd){.next}

