---
title: "Del 4: Transformeren"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

::: {.estimeret_tid}

Forventet tid ca. 90-120 min.


:::

{{< include ../space.qmd >}}

## Aktivitet 1 - Vektorregning {.aimat}

Læs afsnittene [Opmærksomhed](../../materialer/sprogmodeller/transformeren.qmd#opmærksomhed) og [Vektorregning](../../materialer/sprogmodeller/transformeren.qmd#vektorregning). 

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 1: Vektorregning

Lad $\vec{v}_1 = \begin{pmatrix} 1\\ 3\end{pmatrix}$ og $\vec{v}_2 = \begin{pmatrix} 3\\1\end{pmatrix}$.

* Beregn vektorerne 
  $$
  \begin{aligned}
  \vec{w}_1 = \frac{1}{3} \vec{v}_1 + \frac{2}{3} \vec{v}_2 \\ \\
  \vec{w}_2 = \frac{1}{2} \vec{v}_1 + \frac{1}{2} \vec{v}_2 \\ \\
  \vec{w}_3 = \frac{2}{3} \vec{v}_1 + \frac{1}{3} \vec{v}_2 \\
  \end{aligned}
  $$

* Indtegn $\vec{w}_1$, $\vec{w}_2$ og $\vec{w}_3$ i et koordinatsystem sammen med $\vec{v}_1$ og $\vec{v}_2$.

* Passer resultatet med, at vektoren
  $$
  c_1\vec{v}_1 + c_2\vec{v}_2
  $$ 
  med
  $c_1,c_2\geq 0$ ligger tættere på $\vec{v}_1$ jo større $c_1$ er?

Lad $\vec{v}_1 = \begin{pmatrix} 1\\ 2\\ 0\\ -3\end{pmatrix}$ og $\vec{v}_2 = \begin{pmatrix} 1\\-1\\2\\ 4\end{pmatrix}$.
    
* Beregn
  $$
  2\vec{v}_1+\vec{v}_2 
  $$

:::



{{< include ../space.qmd >}}

## Aktivitet 2 - Et opmærksomhedslag  {.aimat}

Læs afsnittet [Et opmærksomhedslag](../../materialer/sprogmodeller/transformeren.qmd#et-opmærksomhedslag). 

::: {.callout-note collapse="false" appearance="minimal"}

### Opgave 2: Vektorrepræsentationer

Betragt sætningen \"Der svømmer marsvinet\". Her har \"svømmer\" stor betydning for vores opfattelse af ordet \"marsvinet\", mens \"der\" ikke giver os ret meget ny information. Lad os sige, at de tre ord har vektorrepræsentationerne 

$$
\begin{aligned}
&\text{der}&&
\vec{q}_1 = \begin{pmatrix}0\\-5\end{pmatrix},&& \vec{k}_1=\begin{pmatrix}4\\-1\end{pmatrix},&&\vec{v}_1= \begin{pmatrix} -1\\ -1\end{pmatrix}\\
&\text{svømmer}&&
\vec{q}_2 = \begin{pmatrix}3\\-7\end{pmatrix},&& \vec{k}_2=\begin{pmatrix}1\\2\end{pmatrix},&&\vec{v}_2= \begin{pmatrix} -2\\ 2\end{pmatrix}\\
&\text{marsvinet}&&
\vec{q}_3 = \begin{pmatrix}0\\1\end{pmatrix}, &&\vec{k}_3=\begin{pmatrix}-1\\2\end{pmatrix},&&\vec{v}_3= \begin{pmatrix} 1\\ 2\end{pmatrix}\\
\end{aligned}
$$

Vi vil nu se, at den opdaterede vektor $\vec{w}_3$ for \"marsvinet\" bliver trukket meget i retning af \"svømmer\", men i mindre grad i retning af \"der\".

-   Beregn $\vec{w}_3$ ved at følge nedenstående skridt:

    -   Beregn skalarprodukterne
        $\vec{k}_1\cdot \vec{q}_3$,
        $\vec{k}_2\cdot \vec{q}_3$ og
        $\vec{k}_3\cdot \vec{q}_3$.

    -   Brug softmax til at beregne konstanterne $c_{1,3}$, $c_{2,3}$ og
        $c_{3,3}$.

    -   Beregn
        $$\vec{w}_3 = c_{1,3}\vec{v}_1 + c_{2,3}\vec{v}_2 + c_{3,3}\vec{v}_3$$

-   Tegn vektorerne $\vec{v}_1$, $\vec{v}_2$,     $\vec{v}_3$ og $\vec{w}_3$ ind i et koordinatsystem og overvej, hvordan $\vec{w}_3$ ligger i forhold til $\vec{v}_1$, $\vec{v}_2$ og $\vec{v}_3$.

-   Tegn vektorerne $\vec{k}_1$, $\vec{k}_2$, $\vec{k}_3$ og $\vec{q}_3$ ind i et koordinatsystem. Passer det med, at kontekstvektoren for de ord, der har mest at sige om betydningen af ordet \"marsvinet\", peger mest i retning af $\vec{q}_3$?

::: 

{{< include ../space.qmd >}}

## Aktivitet 3 - En transformerblok  {.aimat}

Læs afsnittet [En transformerblok](../../materialer/sprogmodeller/transformeren.qmd#en-transformerblok). 

Opgaver...???


{{< include ../space.qmd >}}


## Aktivitet 4 - Transformernetværk  {.aimat}

Læs afsnittet [Transformernetværk](../../materialer/sprogmodeller/transformeren.qmd#transformernetværket). 

Opgaver...???


{{< include ../space.qmd >}}


## Aktivitet 5 - Træning af netværket  {.aimat}

Læs afsnittet [Træning af netværket](../../materialer/sprogmodeller/transformeren.qmd#træning-af-netværket). 

Opgaver...???

{{< include ../space.qmd >}}

[$\leftarrow$ Forrige](sprogmodeller_del3.qmd){.prev}
[Næste $\rightarrow$](sprogmodeller_eksamen.qmd){.next}
