---
title: 'Facit til forløbet \"Hvad skal du se på Netflix?\"'
description: ''
image: ""
categories:
---


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 2

$$
\begin{aligned}
& H_{\{\text{computer}\}}  \approx 0.235\\
& H_{\{\text{mus}\}}  \approx 0.424\\
& H_{\{\text{tastatur}\}}  \approx 0.114\\
& H_{\{\text{computer,mus}\}}  \approx 0.023 \\
& H_{\{\text{computer, tastatur}\}}  \approx 0.052
\end{aligned}
$$

$$
\begin{aligned}
& \hat{P}( H_{\{\text{mus}\}} \mid H_{\{\text{computer}\}}) \approx 0.098 \\
& \hat{P}(H_{\{\text{tastatur}\}} \mid H_{\{\text{computer}\}} ) \approx 0.219
\end{aligned}
$$

:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 3

$$
\begin{aligned}
&H_{\{\text{Blinkende Lygter}\}} = 0.75\\
&H_{\{\text{Olsen-banden}\}} =0.25 \\
&H_{\{\text{Blinkende Lygter, Olsen-banden}\}} =0.25\\
\end{aligned}
$$



$$
\begin{aligned}
& \hat{P}(H_{\{\text{Olsen-banden}\}}\mid H_{\{\text{Blinkende lygter}\}} ) \approx 0.33 \\
& \hat{P}( H_{\{\text{Hævnen}\}}\mid H_{\{\text{Blinkende lygter}\}}) \approx 0.67
\end{aligned}
$$


:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 4

* Hvis $x_2=0$ er
   $$
   \hat{r} = 2-0.02 x_1
   $$
   hvilket er en lineær funktion med hældning $-0.02$ og skæring $2$.
   
   Hvis indholdet af romantik stiger med $1$, så falder ratings med $0.02$.

* Hvis $x_2=50$ er
   $$
   \hat{r} = 4.5-0.02 x_1
   $$
   Det vil sige, at skæringen nu er $4.5$, mens hældningen er uændret.
   
   De to linjer er parallelle.
   
* Hvis indholdet af action stiger med $1$, så stiger ratings med $0.05$.


:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 5

* Bruger 1 med $b=2.8$, $a_1=-0.01$, $a_2=-0.1$ og $a_3= 0.1$.
* Bruger 2 med $b=-4$, $a_1=0$, $a_2=0$ og $a_3=1$.

Ratings:

|                   | \"Titanic\" | \"Olsen-banden ser rødt\" | \"Jagten\" |
|:-----------------:|:---------:|:-----------------------:|:--------:|
| Bruger 1  |   $1.95$ | $4.92$    | $1.28$  |
| Bruger 2  |   $3.9$ | $3.7$    | $4.3$  |
: {.bordered}


:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 7

* Vægte 1: $b=3.8$, $a_1=-0.02$, $a_2=-0.05$ og $a_3=0.3$.

   |                   | \"Titanic\" | \"Olsen-banden ser rødt\" | \"Jagten\" |
   |:-----------------:|:---------:|:-----------------------:|:--------:|
   | Faktiske ratings $r$ |     $2$   |         $5$          |   $4$  |
   | Prædikterede ratings $\hat{r}$  |  $2.44$  |  $5.21$   | $3.39$   |
   | Prædiktionsfejl $r-\hat{r}$  | $-0.44$   |  $-0.21$   | $0.61$   |
   : {.bordered}
   
   Værdi af tabsfunktionen: $0.6098$.


* Vægte 2: $b=1.8$, $a_1=0.01$, $a_2=-0.1$ og $a_3=0$.

   |                   | \"Titanic\" | \"Olsen-banden ser rødt\" | \"Jagten\" |
   |:-----------------:|:---------:|:-----------------------:|:--------:|
   | Faktiske ratings $r$ |     $2$   |         $5$          |   $4$  |
   | Prædikterede ratings $\hat{r}$  |  $4.04$  |  $5.25$   | $1.75$   |
   | Prædiktionsfejl $r-\hat{r}$  | $-2.04$   |  $-0.25$   | $2.25$   |
   : {.bordered}
   
   Værdi af tabsfunktionen: $9.2866$.
   


:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 9

Streamingtjeneste med $n=1.000.000$ brugere og $p=10.000$ film.

* Alle kombinationer af film og brugere: $10000000000=10^{10}$ (altså 10 milliader) ratings. 

* Matrixfaktorisering med $M=5$: $M \cdot p + n \cdot M = 5050000$ vægte.

* Regressionsmodel med $M=5$ features: $n \cdot (1+M) = 6000000$ vægte.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 10

* Prædikterede ratings $\hat{r}_{ij}$:

   |                   | \"Titanic\" | \"Ringenes Herre\" | \"Jurassic park\" |
   |:-----------------:|:---------:|:-----------------------:|:--------:|
   | Bruger 1  |   $2$ | $1$  | $4$  |
   | Bruger 2  |   $2$ | $1$  | $7$  |
   | Bruger 3  |   $6$ | $3$  | $3$  |
   : {.bordered}

* Prædiktionsfejl $r_{ij}-\hat{r}_{ij}$


   |                   | \"Titanic\" | \"Ringenes Herre\" | \"Jurassic park\" |
   |:-----------------:|:---------:|:-----------------------:|:--------:|
   | Bruger 1  |   $-1$ | NA  | $0$  |
   | Bruger 2  |   $1$ | NA  | $-2$  |
   | Bruger 3  |   NA | $0$  | $-1$  |
   : {.bordered}
   
* Værdi af tabsfunktionen: $7$.

:::

