---
title: 'Facit til forløbet \"Test for sygdomme\"'
description-meta: ''
image: ""
categories:
---

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 1

* Det er nemt at lave en test, hvor sensitiviteten er $100 \%$ -- den skal bare altid være positiv. Til gengæld bliver specificiteten $0 \%$!

* På tilsvarende måde er det nemt at lave en test med en specificiteten på $100 \%$ -- den skal altid være negativ. Her bliver sensitiviteten så $0 \%$.


:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 3

|       | Syg   | Rask   | I alt |
|:-------:|:--------:|:--------:|:--------:|
| Positiv test   | $430$ | $760$ | $1190$ | 
| Negativ test   | $70$ | $8740$ | $8810$ |
| I alt | $500$ | $9500$ | $10000$ |
: {.bordered}


:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 4

* $P(\textrm{syg } | \textrm{ positiv test}) \approx 36.1 \%$

* $P(\textrm{rask } | \textrm{ negativ test}) \approx 99.2 \%$

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 5

[Prævalens på $1 \%$]{.fremhaev}

|       | Syg   | Rask   | I alt |
|:-------:|:--------:|:--------:|:--------:|
| Positiv test   | $86$ | $792$ | $878$ | 
| Negativ test   | $14$ | $9108$ | $9122$ |
| I alt | $100$ | $9900$ | $10000$ |
: {.bordered}

\
\

[Prævalens på $5 \%$]{.fremhaev}

|       | Syg   | Rask   | I alt |
|:-------:|:--------:|:--------:|:--------:|
| Positiv test   | $430$ | $760$ | $1190$ | 
| Negativ test   | $70$ | $8740$ | $8810$ |
| I alt | $500$ | $9500$ | $10000$ |
: {.bordered}

\
\

[Prævalens på $20 \%$]{.fremhaev}

|       | Syg   | Rask   | I alt |
|:-------:|:--------:|:--------:|:--------:|
| Positiv test   | $1720$ | $640$ | $2360$ | 
| Negativ test   | $280$ | $7360$ | $7640$ |
| I alt | $2000$ | $8000$ | $10000$ |
: {.bordered}

\
\

[Prævalens på $40 \%$]{.fremhaev}

|       | Syg   | Rask   | I alt |
|:-------:|:--------:|:--------:|:--------:|
| Positiv test   | $3440$ | $480$ | $3920$ | 
| Negativ test   | $560$ | $5520$ | $6080$ |
| I alt | $4000$ | $6000$ | $10000$ |
: {.bordered}

\
\

[Positiv og negativ prædiktiv værdi]{.fremhaev}

| Prævalens  | Positiv prædiktiv værdi   | Negativ prædiktiv værdi   |
|:-------:|:--------:|:--------:|
| $1 \%$ | $9.8 \%$ | $99.8 \%$ | 
| $5 \%$ | $36.1 \%$ | $99.2 \%$ | 
| $20 \%$| $72.9 \%$ | $96.3 \%$ |
| $40 \%$| $87.8 \%$ | $90.8 \%$ |
: {.bordered}

:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 6

|       | Syg   | Rask   | I alt |
|:-------:|:--------:|:--------:|:--------:|
| Positiv test   | $2159$ | $1766$ | $3925$ | 
| Negativ test   | $1910$ | $111835$ | $113745$ |
| I alt | $4069$ | $113601$ | $117670$ |
: {.bordered}

* Sensitivitet: $P(\textrm{positiv test } | \textrm{ syg}) = 53.1 \%$

* Specificitet: $P(\textrm{negativ test } | \textrm{ rask}) =98.4  \%$ 

* Prævalens: $P(\textrm{syg})= 3.5 \%$

* Positiv prædiktiv værdi:  $P(\textrm{syg } | \textrm{ positiv test}) = 55.0 \%$ 

* Negativ prædiktiv værdi: $P(\textrm{rask } | \textrm{ negativ test}) = 98.3 \%$

:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 7

* Se resultatet i opgave 5. 

:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 8


* Negativ prædiktiv værdi:
  $$
  \begin{aligned}
  P(\textrm{rask } &| \textrm{ negativ test})  \\ &=
  \frac{\textrm{specificitet} \cdot (1- \textrm{prævalens})}{(1- \textrm{sensitivitet}) \cdot \textrm{prævalens} + \textrm{specificitet} \cdot (1- \textrm{prævalens})}
  \end{aligned}
  $$

* Se resultatet i opgave 5. 

:::