---
title: "Sandsynlighed og mængdeteori"
description-meta: "test"
image: ""
---


## Sandsynlighed og mængdeteori

## Indledning
I det følgende ses på Sandsynlighedsteori. Alle har selvfølgelig en fornemmelse for hvor sandsynligt det er, at nogle hændelser indtræffer – for eksempel at man slå en sekser med en terning eller trække et rødt kort fra et spil kort. 
Hurtigt kan det dog blive mere besværligt og for at kunne arbejde systematisk med sandsynligheder, er det nødvendigt først at forstå mængdeteori, som kan være med til at give overblik over hændelser. 


## Mængdeteori
En mængde er blot en samling af elementer. Det kunne være en samling der indeholder bogstaverne $b$, $d$ og $k$. Denne mængde noteres som $\{b,d,k\}$. Vi siger at mængden indeholder elementerne deri, og hvis vi kalder mængden for $M$ betyder $a\in M$ netop at $M$ indeholder elementet $a$ (eller at $a$ er indeholdt i $M$). At et element $x$ ikke er i mængden $M$ kan skrives som $x\not \in M$.

Bemærk at en mængde kan indeholde alt muligt, det kunne også være en mængde med tal som $\{1,3,5\}$ eller en mængde med personer.


Hvis man har to mængder $A$ og $B$, da siger vi at de to mængder er ens hvis det er sådan, at ethvert element der er i $A$ også er i $B$ og ethvert element der er i $B$ også er i $A$. Hvis $A$ og $B$ er ens skrives det som $A=B$. 

::: {.callout-note collapse="false" appearance="minimal"}
### Ens mængder?
Overvej hvilke af følgende mængder der er ens:
$A=\{1,2,3,5\}$
$B=\{1,4,5\}$
$C=\{1,3,2,5\}$
$D=\{1,3,5,2,1,1\}$
:::

Her er det faktisk de tre mængder $A$, $C$ og $D$ som er ens, hvilket viser at rækkefølgen ved opskrivningen af elementerne ikke er vigtig og heller ikke om et element skrives flere gange ved mængden. Det vigtige er altså blot om et element er med i mængden eller ej.

Ofte vil man arbejde med flere mængder og kombinere disse til at lave nye mængder. 

Givet to mængder $A$ og $B$, da indføres foreningsmængden af $A$ og $B$ betegnet med $A\cup B$ som mængden som netop indeholder de elementer som er i $A$ eller $B$ eller begge af disse. 

Desuden indføres fællesmængden af $A$ og $B$ betegnet med $A\cap B$ som mængden som netop indeholder de elementer som er indeholdt i både $A$ og $B$.

::: {.callout-note collapse="false" appearance="minimal"}
### Foreningsmængde og fællesmængde
Hvis $A=\{1,2,3,4,5,6\}$ og
$B=\{2,4,6,8\}$ bestem da de to mængder $A\cup B$ og $A\cap B$.
:::
Igen svar til opgaverne (måske skjult).

$A\cup B=\{1,2,3,4,5,6,8\}$ og $A\cap B=\{2,4,6\}$



En af de vigtige mængder er den tomme mængde som betegnes med  $\emptyset$. 
Hvis to mængder $A$ og $B$ opfylder at $A\cap B=\emptyset$ siges at $A$ og $B$ er disjunkte. Disjunkte mængder har derved ikke nogen elementer til fælles, og man kunne også sige at der ikke er noget overlap mellem de to mængder.

::: {.callout-note collapse="false" appearance="minimal"}
### Disjunkte mængder
Overvej hvilke af følgende mængder der er disjunkte med hinanden:
$A=\{1,2,3,5\}$
$B=\{1,4,6\}$
$C=\{3,5,7\}$
:::
Svar : Her er det mængderne $A$ og $B$ samt $B$ og $C$ som er disjunkte.


Ofte når man betragter mængder vil man udelukkende have elementer af en bestemt slags. Som tidligere kunne det være at alle elementer er heltal. Her tænker vi at vi arbejder indenfor et Univers $U$ som er alle mulige tænkelige elemeter, og de mængder vi ellers ser på indeholder så elementer som er i mængden $U$. 

Givet et univers $U$ og en mængde $A$ som kun indeholder elementer som også er i $U$, da indføres komplementærmængden for $A$ noteret $\overline{A}$ som mængden indeholdende netop de elementer fra $U$ som ikke er i $A$.

Hvis vi arbejder med et univers $U=\{1,2,3,4,5,6,7,8\}$ og har at $A=\{1,2,3\}$ da er $\overline{A}= \{4,5,6,7,8\}$.

Den følgende figur viser såkaldte veen-diagrammer for foreningsmængde, fællesmængde og komplementærmængde

Figur mangler.


Givet en mængde $A$, så kaldes $A_1,A_2,...,A_n$ en opdeling af $A$ hvis 
$A_1,A_2,...,A_n$ er mængder som er parvis disjunkte og hvor 
$$A=A_1\cup A_2\cup \cdots \cup A_n.$$
Hvis man har mængden $A=\{1,2,3,4,5,6,7,8\}$ kan man lave en opdeling af $A$ i to mængder $A_1$ og $A_2$ hvor $A_1$ indeholder de lige tal fra $A$ mens $A_2$ indeholder de uligetal fra $A$.

Hvis det var en mængde indeholdende elever på et gymnasie, kunne man lave en opdeling efter klasser man kommer fra.

 
## Sandsynlighed

Ved sandsynlighedsregning tænker man, at man udfører et forsøg/eksperiment og der så er nogle mulige udfald. Mængden af disse udfald kaldes udfaldsrummet.

På forhånd ved man ikke hvad udfaldet bliver, men ofte kender man sandsynligheden for hvert udfald sker. Rent matematisk svarer det til en såkaldt sandsynlighedfunktion.

En sandsynlighedsfunktion $P$ er en funktion, der til hvert udfald $u_i$ i et udfaldsrum $U=\{u_1,u_2,\ldots,u_n\}$ knytter et reelt tal $P(u_i)$, hvor der gælder, at $P(u_i)\geq 0$ og hvor $$P(u_1)+P(u_2)+\cdots + P(u_n)=1=100 \%.$$
$P(U_i)$ kaldes sandsynligheden for udfaldet $u_i$. 



Hvis vi tænker på et konkret eksempel kunne det være at man slår med en almindelig terning hvor udfaldet kan være $1,2,3,4,5,6$.
Her vil sandsynligheden for at man slår $3$ være $P(3)=\frac{1}{6}$. Ved dette eksempel er sandsynligheden for hvert udfald ens.


Hvis sandsynligheden for hvert udfald er den samme kaldes sandsynlighedsfeltet for symmetrisk.
Hvis der ialt er $n$ udfald vil sandsynligheden for et udfald $u\in U$ ved et symmetrisk sandsynlighedsfelt være
$$P(u)=\frac{1}{n}.$$

Ofte vil vi ikke kun se på sandsynligheden for et udfald, men derimod for noget som kan dække over flere forskellige udfald, dette kaldes en hændelse. Ved en terning kunne det være sandsynligheden for at slå noget lige.

Hvis vi igen arbejder med et symmetrisk sandsynlighedfelt og $A$ er en hændelse som ialt består af $k$ udfald bliver sandsynligheden for $A$
$$P(A)=\frac{k}{n}.$$
I forhold til en hændelse $A$ kan man også tænke på de udfald som er i $A$ som gunstige udfald, hvorved vi kan bruge formlen
$$P(A)=\frac{antal\ gunstige \ udfald}{antal \ mulige \ udfald}.$$

Hvis man ser på sandsynligheden for at slå noget lige med en almindelig terning, har vi da at hændelsen svarer til udfaldene $2,4$ og $6$. Derved bliver sandsynligheden $P=\frac{antal\ gunstige}{antal \ mulige}=\frac{3}{6}=\frac{1}{2}$.

Det er selvfølgelig ikke altid man har et symmetrisk sandsynlighedfelt. Hvis man se på et eksempel med en maskine der producerer bolde, og for hver gang der bliver lavet en bold er der $20 \%$ chance for den bliver rød, $40 \%$ chance for den bliver blå, $10 \%$ chance for den bliver grøn og $30 \%$ chance for den bliver gul. 

Her Har vi udfaldsrummet $\{rød, blå, grøn , gul\}$. Desuden er $P(rød)=20 \%$ $P(blå)=10 \% og $P(grøn)=30 \%.


Hvis vi ser på hændelsen at der laves en rød eller blå bold, da bliver sandsynligheden.
$$P=P(rød)+P(blå)=20\%+40\%=60\%.$$
Altså bliver der blot summen af sandsynlighederne for hvert af udfaldene fra hændelsen.

Hvis man ser på hændelser som mængder kan man nu finde resultater for hændelser som kan laves vha. foreningsmængde og fællesmængde. Her får man følgende resultat:

$$P(A\cup B)=P(A)+P(B)-P(A\cap B).$$
Dette resultat ses ud fra veen-diagrammet fra figur ??. Hvis man tager alle udfald fra $A$ og bagefter tager alle udfald fra $B$, vil de udfald som er i begge, svarende til fællesmængden, blive taget to gange. 

Hvis de to hændelser $A$ og $B$ er disjunkte, hvorved $A\cap B$ er den tomme mængde, bliver
$$P(A\cup B)=P(A)+P(B).$$
Når man ser på hændelsen $\overline{A}$ svarende til komplementærmængden af en mændelse $A$ er det oplagt at 
$$P(\overline{A})=1-P(A).$$

Eksempel:
Hvis man kaster to gange med en ganske almindelig terning og ønsker at finde sandsynligheden for at man mindst en af gangene får en 6'er. Hvis man $A$ og $B$ svarer til hændelsen at man slår en 6'er ved hhv. første og andet kast (og det ved det modsatte kast er ligemeget hvad man slår), da er den ønskede sandsynlighed:
$$P(A\cup B)=P(A)+P(B)-P(A\cap B).$$
Her må $P(A)=P(B)=\frac{1}{6}$  og  $P(A\cap B)=\frac{1}{36}$ da $A\cap B$ må svare til at man får en 6'er ved begge kast.
Derved er 
$$P(A\cup B)=P(A)+P(B)-P(A\cap B)=\frac{1}{6}+\frac{1}{6}-\frac{1}{36}=\frac{11}{36}.$$
Her bemærkes at udfaldet hvor man ved begge kast får en 6'er både er i hændelsen $A$ og $B$.

## Estimat for sandsynlighed.
Ofte vil man støde på tilfælde hvor man ikke kender en sandsynlighed, og heller ikke bare kan regne sandsynligheden ud.
Det kunne f.eks. være sandsynligheden for at vinde ved lykkehjul ved et reklamespil. Her vil firmaer ofte få det til at fremgå som om det er let at vinde et større beløb ved at alle felter er lige store.
For at få et estimat for sandsynligheden for at vinde kunne man prøve lykkehjulet en del gange og finde et estimat,$\hat{p}$, for sandsynligheden for at vinde ved at benytte formlen
$$\hat{p}=\frac{antal\ gunstige}{antal \ mulige}.$$
Her har vi blandt andet antaget at der er uafhængighed mellem udfaldet ved hvert forsøg, og sandsynligheden ikke ændres. Estimatet for sandsynlighed fås på denne måde ved en stikprøve hvor man prøver nogle gange.


## Betinget sandsynlighed, uafhængighed og betinget sandsynlighed.
Givet to hændelser $A$ og $B$ så benyttes notationen $P(A|B)$ for sandsynligheden for, at $B$ sker, når det er givet, at $B$
 er sket. Det læses derfor også som sandsynligheden for $A$
 givet $B$.

Lad os se på et par eksempler:

Eksempel 1: 
Vi ser igen på at man slår med en gaske almindelig terning. Her ønsker vi at bestemme sandsynligheden for at man slår noget lige givet at man slår mindst $4$.
Hvis $A=\{2,4,6\}$ svarer til at slå noget lige og $B=\{4,5,6\}$ svarer til at slå mindst $4$, da er det netop sandsynlighden $P(A|B)$ vi skal have fundet.
Her kan vi tænke på det som om at udfaldrummet kun består af $B=\{4,5,6\}$ og ved hændelsen $A$ skal vi kun se på den del som også er i $B$. Da det samtidigt er et symmetrisk snadsynlighedsfelt vil vi få sandsynligheden ved
$$P(A|B)=\frac{antal\ gunstige}{antal \ mulige}=\frac{2}{3}.$$
I denne formel prøve vi lige at dele med antal udfald i tæller og nævner.
$$P(A|B)=\frac{antal\ gunstige}{antal \ mulige}=\frac{\frac{2}{6}}{\frac{3}{6}}.$$
Ved tælleren så vi egentlig på fællesmængden for de to hændelser og her er $P(A\cap B)=\frac{2}{6}$ mens nævneren svarer til $P(B)=\frac{3}{6}$.

Altså er $$P(A|B)=\frac{P(A\cap B)}{P(B)}$$

Eksempel 2:
Her udvælger vi en tilfældig gymnasieelev og ser på om den udvalgte er interesseret i fodbold.

Her kunne man se på Sandsynligheden for at den udvalgte er interesseret i fodbold givet at den udvalgte er en dreng. 

Alle vil nok tænke at en information om køn af den udvalgte vil ændre sandsynligheden for om den udvalgte er interesseret i fodbold.


Lad os sige at der ialt er $500$ gymnasieelever, hvoraf $200$ er drenge og $300$ piger. Desuden er 120 drenge interesseret i fodbold mens $90$ piger er interesseret i fodbold.

Vi kan nu beregne $P(Fodbold)$, $P(Fodbold| dreng)$ og $P(Fodbold| pige)$.

$$P(Fodbold)=\frac{antal\ gunstige}{antal \ mulige}=\frac{210}{500}=42\%.$$
Hvis vi skal finde $P(Fodbold| dreng)$ er det sandsynligheden for at den udvalgte er interesseret i fodbold givet at den udvalgte er en drenge. Med denne formulering giver det meningen kun at se på drengene og om en udvalgt der vil være interesseret i fodbold for at bestemme $P(Fodbold| dreng)$.
$$P(Fodbold| dreng)=\frac{antal\ gunstige}{antal \ mulige}=\frac{120}{200}=60\%.$$
Her ses at informationen med at det er en dreng der er udvalgt har betydning for om den udvalgte er interesseret i fodbold.

Ved beregningen af $P(Fodbold| dreng)$ kunne vi i tæller og nævner dividere med antallet af gymnasierelever ialt og få
$$P(Fodbold| dreng)=\frac{\frac{120}{500}}{\frac{200}{500}}.$$

Her svarer nævneren til sandsynligheden for at den udvalgte er en dreng, men nævneren svarer til at den udvalgte både er en dreng og han er interesseret i fodbold, hvorved det er en fællesmængde. Altså 
$$P(Fodbold| dreng)=\frac{P(Fodbold \cap dreng)}{P(dreng)}$$

sætning:

Givet to hændelser $A$ og $B$, da er den betingede sandsynlighed $P(A|B)$ givet ved
$$P(A|B)=\frac{P(A\cap B)}{P(B)}$$ og sandsynligheden for $A\cap B$ er
$$P(A\cap B)=P(B)\cdot P(A|B)$$
Beregningen med formlen svarer til at man begrænser sig til udfald hvor $B$ indtræffer og ser hvor sandsynligt det er at $A$ indtræffer der.


Man siger to hændelser er uafhængige, hvis viden om at den ene hændelse indtræffer ikke påvirker sandsynligheden for den anden.

Det vil sige at to hændelser $A$ og $B$ er uafhængige hvis $P(A|B)=P(A)$.

Ved eksempel 2 fra tidligere er der ikke uafhængighed mellem hændelserne med at den udvalgte er en dreng og hændelsen at den udvalgte er interesseret i foldbold. Ved eksemplet var $P(Fodbold)=42\%$ mens $P(Fodbold|dreng)=60\%$.


opgaver : 
På et gymnasie ønsker man at se på om der er sammenhæng mellem om elever har fået morgenmad og om de føler sig motiveret i 1. lektion.

Man har ialt fået svar fra $700$ elever, hvoraf $600$ havde fået morgenmad og $100$ ikke have fået morgenmad. Af dem som havde fået morgenmad var der $500$ der svarede at de var motiveret i 1.lektion, og af dem som ikke havde fået morgenmad var der $55$ der svarede at de var motiveret i 1.lektion.
Hvis $A$ svarer til hændelsen at en elev har fået morgenmad og $B$ svarer til at en elev er motiveret i 1.lektion, bestem da følgende

a) Bestem sandsynligheden for at en tilfældig udvalgt elev får morgenmad.
b) Bestem sandsynligheden for at en tilfældigt udvalgt elev både har fået morgenmad og er motiveret i 1. lektion.
c) bestem sandsynligheden for at en elev er motiveret i 1. lektion givet at eleven har fået morgenmad.
d) bestem sandsynligheden for at en elev er motiveret i 1. lektion givet at eleven ikke har fået morgenmad.
e) er der uafhængighed mellem hændelserne A og B.


Et af de helt centrale resultater for betingede sandsynligheder er Bayes sætning.

Bayes Sætning/Formel:
Givet to hændelser $A$ og $B$ da gælder at

$$P(A|B)=\frac{P(B|A)\cdot P(A)}{P(B)}.$$

Bevis:
Givet to mængder $A$ og $B$ så ved vi at $A\cap B=B\cap A$, og derved er $P(A\cap B)=P(B\cap A)$.
Ved at benytte formel ?? for at finde begge disse sandsynligheder får vi: 
$P(A)\cdot P(B|A)=P(B)\cdot P(A|B)$. Her isoleres $P(A|B)$ ved at gange med $P(B)$, hvorved 
$$\frac{P(B|A)\cdot P(A)}{P(B)}=P(A|B).$$

Ofte benyttes Bayes sætning til at bestemme den betingede sandsynlighed $P(A|B)$ ud fra den betingede sandsynlighed $P(B|A)$.


Eksempel fortsat.
Her arbejder vi videre med eksemplet med køn og interesse for fodbold.

Vi ønsker at finde sandsynligheden for at en udvalgt er en dreng givet at det er en som er interesseret i fodbold. Vi ønsker altså sandsynligheden $P(dreng|fodbold)$. Fra bayes sætning får vi

$$P(dreng|fodbold)=\frac{P(fodbold|dreng)\cdot P(dreng)}{P(fodbold)}.$$
Fra eksemplet har vi udregnet alle sandsynligheder og får så
$$P(dreng|fodbold)=\frac{60 \% \cdot 40 \%}{42\%}=57,14\%.$$
Her skal vi huske at ved eksmplet var det 40 % som var drenge, men der var samtidigt en større del af dem som var interesseret i fodbold end piger. Derved er det forventet at den udregnede sandsynlighed blev over 40 %.


Opgave:
Fortsættelse af opgaven fra tidligere med motivation i 1. lektion og morgenmad.

f) Bestem sandsynligheden for at en elev har fået morgenmad givet at eleven er motiveret i 1. lektion. 



## Opdeling og sandsynlighed
Ud fra formel ......  følger det at 
hvis $A_1,A_2,...,A_n$ er en opdeling for en hændelse $U$ så er
$$P(A)=P(A_1)+P(A_2)+\cdots+P(A_n).$$
Når vi skal finde sandsynligheden for en hændelse $B$ kan det til tider være en ide at benytte en opdeling af ens univers $U$.

Sætning/bevis.

Hvis $B$ er en hændelse og $A_1,A_2,...,A_n$ en opdeling af ens univers $U$, så er 
$$P(B)=P(B|A_1)\cdot P(A_1)+P(B|A_2)\cdot P(A_2)+\cdots +P(B|A_n)\cdot P(A_n).$$
Fra figur ....  ses at B kan opdeles i mængderne $$B\cap A_1,B\cap A_2,\ldots,B\cap A_n.$$
Derved er
$$P(B)=P(B\cap A_1)+P(B\cap A_2)+\cdots+P(B\cap A_n).$$
Ved at benytte ???? for hvert led på højresiden får vi derfor at
$$P(B)=P(B|A_1)\cdot P(A_1)+P(B|A_2)\cdot P(A_2)+\cdots +P(B|A_n)\cdot P(A_n).$$


Lad os tage eksepmlet fra tidligere med fodbold, men hvor vi lige glemmer antallet af elever, men blot tænker vi har oplysning om at $40\%$ er drenge, $60\%$ er piger, $60\%$ af drengene er interesseret i fodbold og $30\%$ af pigerne er interesseret i fodbold.

Hvis man ønsker at beregne sandsynligheden for at en tildældig udvalgt er interesseret i fodbold kan vi lave en opdeling af alle gymnasieeleverne med henholdsvis drenge og piger.
Derved får vi:
$$P(Fodbold)=P(Fodbold|dreng)\cdot P(dreng)+P(Fodbold|pige)\cdot P(pige)$$
$$=60\%\cdot 40\%+30\% \cdot 60 \%=42\%.$$
Hvis vi ved .... ligeledes kun have haft de angivne procenter og ikke antal kunne vi have beregnet 

$$P(dreng|fodbold)=\frac{P(fodbold|dreng)\cdot P(dreng)}{P(Fodbold|dreng)\cdot P(dreng)+P(Fodbold|pige)\cdot P(pige)}.$$

Opgave:
Fortsættelse af opgaven fra tidligere med motivation i 1. lektion og morgenmad. Nu arbejder vi dog med følgende tal:
$80\%$ af alle elever har fået morgenmad. $85 \%$ af dem der har fået morgemad er motiveret i 1. lektion. $55\%$ af dem der ikke har fået morgenmad er motiveret i 1.lektion.


g) Benyt opdeling og bayes formel til at bestemme sandsynligheden for at en elev har fået morgenmad givet at eleven er motiveret i 1.lektion. 


eksempel med sygdom klippes ind.


## Eksamensspørgsmål
betinget sandsynlighed.
Bayes formel + bevis
opdeling og sandsynlighed for hændelse.
Benyt ved AI/ sygdom

