---
title: "Facit til forløbet hvem ligner du mest"

description-meta: ''
image: ""
categories:
---

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 1
Der er overvægt at røde punkter omkring punktet, så det vil være mest rimeligt at vælge rød.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 2
Med 9 røde, 7 blå og 4 grønne, er rød det mest rimelige valg, men det er ikke et tydeligt valg.

Med halv radius er det lidt uklart, om der er 2 eller 3 blå punkter, da ét af de blå punkter ligger lige på grænsen. Så måske rød overvægt med 3 røde mod 2 blå eller måske lige mange røde og blå.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 3
Afstandene beregnes med Pythagoras sætning.

Det mest interessant punkt er det blå punkt lige på grænsen fra opgave 2.
Der er afstanden $$\sqrt{(15-13.8)^2+(15-19.9)^2} \approx 5.04$$, så punktet ligger altså ikke indenfor en afstand på 5 fra $P$.


:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 4
Hvis radius vælges meget lille, er der måske slet ingen punkter i nærheden, og så kan farven ikke afgøres, eller meget få punkter, så det alene er de helt tætte naboer, der bestemmer farven.

Hvis radius vælges meget stor, så bliver det ikke så meget naboerne, der afgør farven, men majoriteten i datasættet.
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 5
Der er ikke noget tydeligt bedste resultat. Hvis radius er meget lille, er der flest blå, for lidt større radius er der flest røde og for størst radius er der flest grønne. 

Rent matematisk er der ikke en radius, som er bedst, så det vil i givet fald afhænge af den kontekst, som opgaven handler om. 
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 6
Den almindelige afstand mellem A og B er $\sqrt{13} \approx 3.6$, mens Manhatten afstanden er $5$. 
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 7
Manhatten afstanden kan ikke bliver mindre end den almindelige afstand.
Hvis punkterne ligger enten lodret eller vandret i forhold til hinanden, bliver de to afstande ens.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 8
Manhatten afstanden giver en "ruder form" $\diamondsuit$.

Den betyder, at 6 røde og 1 grønt punkter, som var indenfor den almindelige afstand, ikke er indenfor Manhattenafstanden. Så valget af afstand kan gøre en stor forskel. 

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 9
Den almindelige afstand
$$\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$
Manhatten afstand
$$|x_2 - x_1| + |y_2 - y_1|$$
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 11
Afstandene er 3, 4 og 2. Så det sidste ord ligner mest. 

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 15
Den samlede afstand er $19$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 16
Min er $0$.

Max er $4 \cdot 23 = 92$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit til opgave 17
Eksempel: $25$ spørgsmål og en afstand på $17$

Så er uenigheden $\frac{17}{4\cdot 25} = 0.17$, og dermed er enighed $83$ procent.


:::