---
title: 'Facit til forløbet \"Hvilken politiker er du mest enig med?\"'
description-meta: ''
image: ""
categories:
---

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 1
Der er overvægt at røde punkter omkring punktet $P$, så det vil være mest rimeligt at vælge rød.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 2
Med 9 røde, 7 blå og 4 grønne, er rød det mest rimelige valg, men det er ikke et tydeligt valg.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 3

Med halv radius kan det være lidt svært at se, om der er 2 eller 3 blå punkter inde i cirklen, da ét af de blå punkter ligger lige på grænsen. Der er til gengæld tydeligt 3 røde punkter (og kun ét grønt) i cirklen. Så enten er der med halv radius lige mange røde og blå eller også er der 3 røde mod 2 blå.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 4
Afstandene beregnes med Pythagoras sætning.

Det mest interessant punkt er det blå punkt lige på grænsen fra opgave 3.
Der er afstanden 

$$\sqrt{(15-13.8)^2+(15-19.9)^2} \approx 5.04,$$ 

så punktet ligger altså ikke indenfor en afstand på 5 fra $P$.


:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 5
Hvis radius vælges meget lille, er der måske slet ingen punkter i nærheden, og så kan farven ikke afgøres, eller meget få punkter, så det alene er de helt tætte naboer, der bestemmer farven.

Hvis radius vælges meget stor, så bliver det ikke så meget naboerne, der afgør farven, men majoriteten i datasættet.
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 6
Der er ikke noget tydeligt bedste resultat. Hvis radius er meget lille, er der flest blå, for lidt større radius er der flest røde og for størst radius er der flest grønne. 

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 7
Den almindelige afstand mellem $A$ og $B$ er $\sqrt{13} \approx 3.6$, mens Manhattan-afstanden er $5$. 
:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 8
Manhattan-afstanden kan ikke bliver mindre end den almindelige afstand.
Hvis punkterne ligger enten lodret eller vandret i forhold til hinanden, bliver de to afstande ens.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 9
Manhattan-afstanden giver en \"ruder form\": $\diamondsuit$.

Den betyder, at der er 6 røde og 1 grønt punkt, som var indenfor den almindelige afstand, men som ikke er indenfor Manhattan-afstanden. Med Manhattan-afstanden skal det grå punkt altså farves blåt. Så valget af afstand kan gøre en stor forskel. 

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 10
Den almindelige afstand:
$$\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$
Manhattan-afstanden:
$$|x_2 - x_1| + |y_2 - y_1|$$
:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 12
Den samlede afstand er $19$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 13
Den mindst mulige afstand er $0$.

Den størst mulige afstand er $4 \cdot 23 = 92$.

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 14
Eksempel: $25$ spørgsmål og en afstand på $17$.

Så er uenigheden $\frac{17}{4\cdot 25} = 0.17 = 17 \%$, og dermed er der en enighed på $83 \%$.


:::