#### [Evaluering]{.fremhaev}


{{< include eval_pred_generel_indledning.qmd >}}

Vælges **Evaluering på træningsdata** beregnes følgende: 

* [Root Mean Squared Error (RMSE)](/noter/vurdering_model/vurdering_model.qmd#root-mean-squared-error-rmse){target="_blank"}
* [Mean Absolute Error (MAE)](/noter/vurdering_model/vurdering_model.qmd##mean-absolute-error-mae){target="_blank"}
* [$R^2$-værdien](/noter/vurdering_model/vurdering_model.qmd#forklaringsgraden-r2-værdien){target="_blank"}

Endelig er det muligt at downloade et datasæt, hvor træningsdatasættet er udvidet med en ekstra kolonne, hvor den prædikterede outputværdien $o$ er beregnet for hvert træningseksempel.

Vælges **Evaluering på bruger-uploadet testdata** beregnes det samme som for **Evaluering på træningsdata** blot med udgangspunkt i et uploadet testdatasæt.

Endelig kan **Evaluering via krydsvalidering** vælges. Her beregnes RMSE og MAE baseret på [krydsvalidering](/noter/krydsvalidering/krydsvalidering.qmd#sec-krydsvalidering){target="_blank"}. Bemærk, at $R^2$-værdien *ikke* beregnes, da det viser sig, at denne værdi ikke giver mening i forbindelse med krydsvalidering. For eksempel kan værdien gå hen og blive negativ.

\
