<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simple kunstige neruale netværk til regression – AI MAT - matematikken bag magien</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../logo/SVG/Bomaerke_05_AIMAT_2024.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-29a8fc30aeae3523cf8e4255cd85b7fd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-Y219BCPS45"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
 
  gtag('consent', 'default', {
    'ad_storage': 'denied',
    'analytics_storage': 'denied'
  });
gtag('config', 'G-Y219BCPS45', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="floating nav-fixed slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../logo/PNG/Logo_multi_AIMAT_RGB_2024.png" alt="" class="navbar-logo light-content">
    <img src="../../logo/PNG/Logo_multi_AIMAT_RGB_2024.png" alt="" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../undervisningsforlob/index.html"> 
<span class="menu-text">Undervisningsforløb</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../noter/index.html"> 
<span class="menu-text">Noter</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../srp/index.html"> 
<span class="menu-text">SRP</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../apps/index.html"> 
<span class="menu-text">Apps</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../til_laererne.html"> 
<span class="menu-text">Til lærerne</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> <i class="bi bi-envelope" role="img" aria-label="Om os">
</i> 
<span class="menu-text">Om os</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.youtube.com/@ai-mat" target="_blank"> <i class="bi bi-youtube" role="img" aria-label="YouTube">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indhold</h2>
   
  <ul>
  <li><a href="#hvad-koster-min-lejlighed" id="toc-hvad-koster-min-lejlighed" class="nav-link active" data-scroll-target="#hvad-koster-min-lejlighed">Hvad koster min lejlighed?</a>
  <ul class="collapse">
  <li><a href="#fortolkning-af-vægtene" id="toc-fortolkning-af-vægtene" class="nav-link" data-scroll-target="#fortolkning-af-vægtene">Fortolkning af vægtene</a></li>
  </ul></li>
  <li><a href="#vurdering-af-modellens-anvendelighed" id="toc-vurdering-af-modellens-anvendelighed" class="nav-link" data-scroll-target="#vurdering-af-modellens-anvendelighed">Vurdering af modellens anvendelighed</a>
  <ul class="collapse">
  <li><a href="#krydsvalidering" id="toc-krydsvalidering" class="nav-link" data-scroll-target="#krydsvalidering">Krydsvalidering</a></li>
  </ul></li>
  <li><a href="#prædiktion-af-lejlighedspriser-nu-med-skjulte-lag" id="toc-prædiktion-af-lejlighedspriser-nu-med-skjulte-lag" class="nav-link" data-scroll-target="#prædiktion-af-lejlighedspriser-nu-med-skjulte-lag">Prædiktion af lejlighedspriser – nu med skjulte lag!</a>
  <ul class="collapse">
  <li><a href="#relu-aktiveringsfunktionen" id="toc-relu-aktiveringsfunktionen" class="nav-link" data-scroll-target="#relu-aktiveringsfunktionen">ReLu aktiveringsfunktionen</a></li>
  <li><a href="#feedforward-udtryk" id="toc-feedforward-udtryk" class="nav-link" data-scroll-target="#feedforward-udtryk">Feedforward udtryk</a></li>
  <li><a href="#backpropagation" id="toc-backpropagation" class="nav-link" data-scroll-target="#backpropagation">Backpropagation</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simple kunstige neruale netværk til regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Hvis du har læst nogle af vores andre noter om kunstige neurale netværk, så har de alle handlet om <strong>klassifikation</strong>. Det kunne for eksempel være: aktiverer en kunde et tilbud i en app? (ja/nej), bliver det regnvejr i morgen? (ja/nej), har en patient en bestemt sygdom? (ja/nej), hvilket af fire valg skal jeg træffe? De tre første eksempler er eksempler på det, som man kalder for <strong>binær klassifikation</strong> (fordi der kun er to muligheder), mens det sidste eksempel er et eksempel på <strong>multipel klassifikation</strong> (fordi der er mere end to muligheder). I denne note vil vi se på, hvordan man kan bruge kunstige neurale netværk til at forudsige en såkaldt numerisk variabel – mere konkret vil vi her se på, hvordan man kan lave et kunstigt neuralt netværk, som kan bruges til at prædiktere salgsprisen på en lejlighed i Aalborg.</p>
<section id="hvad-koster-min-lejlighed" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="hvad-koster-min-lejlighed">Hvad koster min lejlighed?</h2>
<p>Vi forestiller os helt generelt en række inputvariable eller features: <span class="math inline">\(x_1, x_2, \dots, x_n\)</span> på baggrund af hvilke vi gerne vil kunne forudsige en såkaldt targetvariabel <span class="math inline">\(t\)</span>, som her er salgsprisen på en lejlighed i Aalborg.</p>
<div id="exm-lejlighed1" class="theorem example">
<p><span class="theorem-title"><strong>Eksempel 1 (Lejlighedspriser – Home datasættet)</strong></span> <img src="images/lejlighed.jpg" class="img-fluid" style="float:right;;width:30.0%"></p>
<p>Ejendomsmæglerkæden "Home" har stillet information om salg af ejendomme i perioden fra 2010 til 2022 til rådighed. Vi har i dette eksempel valgt at se på salget af lejligheder beliggende i 9000 Aalborg. Du kan downloade denne del af datasættet <a href="data/home_Aalborg9000_lejlighed.xlsx">her</a>.</p>
<p>Targetvariablen <span class="math inline">\(t\)</span> står i kolonnen <code>pris</code> og angiver salgsprisen af en given lejlighed. Derudover indeholder det oprindelige datasættet en lang række oplysninger, men vi har her valgt kun at fokusere på en delmængde af disse.</p>
<p>Vi vil specielt se på følgende features:</p>
<ul>
<li><code>areal</code>: boligens areal målt i kvadratmeter (<span class="math inline">\(x_1\)</span>)</li>
<li><code>alder</code>: boligens alder i år (<span class="math inline">\(x_2\)</span>)</li>
</ul>
<p>Og vi vil lade targetvariablen <span class="math inline">\(t\)</span> være</p>
<ul>
<li><span class="math inline">\(t\)</span>: boligens pris i kroner</li>
</ul>
<p>I eksemplet her har vi information om <span class="math inline">\(1140\)</span> salg af lejligheder og i <span class="math inline">\(4\)</span> tilfælde har vi ikke information om lejlighedens alder, vi vil derfor i det følgende begrænse os til <span class="math inline">\(1136\)</span> salg.</p>
</div>
<p>Lad os starte simpelt og opstille en kunstig neuron til formålet. Så vil vi sige, at vores prædiktion af salgsprisen skal være en outputværdi <span class="math inline">\(o\)</span>, som helt generelt er den vægtede sum af vores inputvariable:</p>
<p><span class="math display">\[
o = w_0 + w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n
\]</span></p>
<p>Her kaldes <span class="math inline">\(w_0, w_1, w_2, \dots, w_n\)</span> for vægte.</p>
<p>Hvis du har læst noten om <a href="../../noter/kunstige_neuroner/kunstige_neuroner.html">kunstige neuroner</a>, så er den eneste forskel her, at vi ikke længere bruger sigmoid-funktionen som aktiveringsfunktion<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, fordi vi ikke her har brug for at få en outputværdi, som ligger mellem <span class="math inline">\(0\)</span> og <span class="math inline">\(1\)</span>.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;Vi bruger sådan set stadig en aktiveringsfunktion – det bare den funktion, som kaldes for <em>identiteten</em> med forskrift <span class="math inline">\(f(x)=x\)</span>.</p></div></div><p>Vi ønsker nu, at bestemme vægtene <span class="math inline">\(w_0, w_1, w_2, \dots, w_n\)</span> sådan at vores prædikterede salgspris <span class="math inline">\(o\)</span> kommer så tæt som muligt på den faktiske salgspris <span class="math inline">\(t.\)</span></p>
<p>Det vil sige, at vi ønsker, at forskellen</p>
<p><span class="math display">\[
t-o = t - \left ( w_0 + w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \right )
\]</span></p>
<p>bliver så lille som mulig.</p>
<p>Da denne differens både kan være positiv og negativ, men vi egentlig ikke er interesseret i fortegnet – blot om differensen er lille eller stor, så vælger vi i stedet at se på den kvadrerede forskel:</p>
<p><span class="math display">\[
\left ( t - \left ( w_0 + w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \right ) \right )^2
\]</span></p>
<p>Vi får en sådan kvadreret differens for hvert eneste salg i vores træningsdatasæt, og vi vælger derfor blot at lægge alle disse størrelser sammen:</p>
<p><span class="math display">\[
E = \frac{1}{2}\sum \left ( t - \left ( w_0 + w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \right ) \right )^2
\]</span></p>
<p>Størrelsen <span class="math inline">\(E\)</span> kaldes for en <strong>tabsfunktion</strong>. Læg mærke til, at hvis vores kunstige neuron er god til at forudsige salgspriser, så får vi en lille værdi af tabsfunktionen, mens vi får en stor værdi af <span class="math inline">\(E\)</span>, hvis modellen er dårlig til at forudsige salgspriser. Vi har her valgt at gange med <span class="math inline">\(\frac{1}{2}\)</span>, fordi det senere kommer til at forkorte ud, men det er faktisk ikke så afgørende.</p>
<p>Idéen er så bare at bestemme værdier af vægtene <span class="math inline">\(w_0, w_1, w_2, \dots, w_n\)</span>, sådan at tabsfunktionen minimeres.</p>
<p>Inden vi forklarer, hvordan det gøres, så lad os lige blive lidt mere specifikke i forhold til notationen af vores træningsdata. Vi forestiller os, at vi har information om <span class="math inline">\(M\)</span> lejlighedssalg (i eksemplet er <span class="math inline">\(M=1136\)</span>). Så vil vi nummere vores træningsdata på denne måde:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{Træningseksempel 1:} \quad (x_1^{(1)}, x_2^{(1)}, \dots, x_n^{(1)}, t^{(1)}) \\
&amp;  \quad \quad \quad \quad \vdots \\
&amp;\text{Træningseksempel m:} \quad (x_1^{(m)}, x_2^{(m)}, \dots, x_n^{(m)}, t^{(m)}) \\
&amp;  \quad \quad \quad \quad \vdots \\
&amp;\text{Træningseksempel M:} \quad (x_1^{(M)}, x_2^{(M)}, \dots, x_n^{(M)}, t^{(M)}) \\
\end{aligned}
\]</span></p>
<p>Gør vi det, bliver tabsfunktionen:</p>
<p><span class="math display">\[
\begin{aligned}
E(w_0, w_1, &amp;\dots, w_n) \\ &amp;= \frac{1}{2} \sum_{m=1}^{M} \left (t^{(m)}-
(w_0 + w_1 \cdot x_1^{(m)} + \cdots + w_n \cdot x_n^{(m)}) \right)^2.
\end{aligned}
\]</span></p>
<p>Hvis vi samtidig indfører, at vi kalder outputværdien for det <span class="math inline">\(m\)</span>’te lejlighedssalg for <span class="math inline">\(o^{(m)}\)</span>:</p>
<p><span class="math display">\[
o^{(m)} = w_0 + w_1 \cdot x_1^{(m)} + \cdots + w_n \cdot x_n^{(m)}
\]</span> Så kan tabsfunktionen udtrykkes kort på denne måde:</p>
<p><span class="math display">\[
\begin{aligned}
E(w_0, w_1, &amp;\dots, w_n) \\ &amp;= \frac{1}{2} \sum_{m=1}^{M} \left (t^{(m)}-
o^{(m)} \right)^2
\end{aligned}
\]</span></p>
<p>hvor det nu så bare ikke er helt så tydeligt, at <span class="math inline">\(E\)</span> jo faktisk afhænger af alle vægtene.</p>
<p>For at bestemme de værdier af vægtene, som minimerer tabsfunktionen, vil vi bruge en metode, som kaldes for gradientnedstigning. Vi har lavet videoer om både <a href="https://youtu.be/tlq2UYWF2Rw" target="blank">funktioner af to variable</a> og <a href="https://youtu.be/WcM8aEoPzf8" target="blank">gradientnedstigning</a>, hvis du vil vide mere.</p>
<p>Idéen i gradientnedstigning er, at vi opdaterer alle vægtene ved at gå et lille stykke i den negative gradients retning. Det kommer til at se sådan her ud:</p>
<p><span class="math display">\[
\begin{aligned}
w_0^{(\textrm{ny})} \leftarrow &amp; w_0 - \eta \cdot \frac{\partial E }{\partial w_0} \\
w_1^{(\textrm{ny})} \leftarrow &amp; w_1 - \eta \cdot \frac{\partial E }{\partial w_1} \\
&amp;\vdots  \\
w_n^{(\textrm{ny})} \leftarrow &amp; w_n - \eta \cdot \frac{\partial E }{\partial w_n} \\
\end{aligned}
\]</span></p>
<p>hvor <span class="math inline">\(\eta\)</span> kaldes for en <strong>learning rate</strong>.</p>
<p>Vi får derfor brug for alle de partielle afledede af <span class="math inline">\(E\)</span> med hensyn til <span class="math inline">\(w_i\)</span> for <span class="math inline">\(i \in \{0, 1, 2, \dots, n\}\)</span>. Det er ikke svært at vise, at</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial E}{\partial w_i} &amp;= - \sum_{m=1}^M \left (t^{(m)}-
(w_0 + w_1 \cdot x_1^{(m)} + \cdots + w_n \cdot x_n^{(m)}) \right) \cdot x_i^{(m)} \\
&amp;= - \sum_{m=1}^M \left (t^{(m)}- o^{(m)} \right) \cdot x_i^{(m)}
\end{aligned}
\]</span> for <span class="math inline">\(i \in \{1, 2, \dots, n\}\)</span> og</p>
<p><span class="math display">\[
\frac{\partial E}{\partial w_0} = - \sum_{m=1}^M \left (t^{(m)}- o^{(m)} \right)
\]</span> Opdateringsreglerne for vægtene bliver derfor:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Opdateringsregler for kunstige neuroner til regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\begin{aligned}
w_0^{(\textrm{ny})} \leftarrow &amp; w_0 + \eta \cdot \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right)\\
w_1^{(\textrm{ny})} \leftarrow &amp; w_1 + \eta \cdot \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right)\cdot x_1^{(m)}\\
&amp;\vdots  \\
w_n^{(\textrm{ny})} \leftarrow &amp; w_n + \eta \cdot \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right)\cdot x_n^{(m)}
\end{aligned}
\]</span></p>
<p>hvor <span class="math inline">\(o^{(m)} = w_0 + w_1 \cdot x_1^{(m)} + \cdots + w_n \cdot x_n^{(m)}\)</span>.</p>
</div>
</div>
</div>
<p>At opstille en kunstig neuron til regression, som vi har gjort her, svarer til det, man kalder for <strong>multipel lineær regression</strong>, som egentlig bare er en udvidelse af lineær regression, som I kender det, blot med flere inputvariable/features.</p>
<p>Det gode ved at opstille en kunstig neuron til regression, som vi her har gjort det, er at man kan give en fortolkning af vægtene.</p>
<section id="fortolkning-af-vægtene" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="fortolkning-af-vægtene">Fortolkning af vægtene</h3>
<p>Lad os sige, at vi har bestemt vægtene <span class="math inline">\(w_0, w_1, \dots, w_n\)</span>, så tabsfunktionen er blevet minimeret, og at <span class="math inline">\(x_1\)</span> fortsat angiver boligarealet. Vi vil her forklare, hvordan vi kan fortolke <span class="math inline">\(w_1\)</span>.</p>
<p>Vi forstiller os, at vi har to lejligheder med præcis samme værdier af de <span class="math inline">\(n\)</span> features <span class="math inline">\(x_1, x_2, \dots, x_n\)</span> bortset fra, at den ene lejlighed er præcis <span class="math inline">\(1 \, m^2\)</span> større end den anden. Så den ene lejlighed har en størrelse på <span class="math inline">\(x_1 \, m^2\)</span>, mens det andet har en størrelse på <span class="math inline">\(x_1+1 \, m^2\)</span> – de resterende features er ens.</p>
<p>Det giver følgende prædikterede salgspriser <span class="math inline">\(o_1\)</span> og <span class="math inline">\(o_2\)</span> for de to lejligheder:</p>
<p><span class="math display">\[
\begin{aligned}
o_1 &amp;= w_0 + w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \\
\\
o_2 &amp;= w_0 + w_1 \cdot (x_1 + 1) + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \\
&amp;= w_0 + w_1 \cdot x_1 + w_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n
\end{aligned}
\]</span></p>
<p>Da bliver forskellen mellem de to prædikterede salgspriser:</p>
<p><span class="math display">\[
\begin{aligned}
o_2 - o_1 &amp;= w_0 + w_1 \cdot x_1 + w_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \\
&amp; \quad \quad - \left ( w_0 + w_1 \cdot x_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \right) \\
&amp;= w_0 + w_1 \cdot x_1 + w_1 + w_2 \cdot x_2 + \cdots + w_n \cdot x_n \\ &amp; \quad \quad - w_0 - w_1 \cdot x_1 - w_2 \cdot x_2 - \cdots - w_n \cdot x_n \\
&amp; = w_1
\end{aligned}
\]</span></p>
<p>Det vil sige, at hvis alt andet er holdt ens, så vil en forøgelse i boligarealet på <span class="math inline">\(1 \, m^2\)</span> give en forøgelse i den prædikterede salgspris på <span class="math inline">\(w_1\)</span> kroner.</p>
<p>Da <span class="math inline">\(x_2\)</span> angiver lejlighedens alder, så vil <span class="math inline">\(w_2\)</span> helt tilsvarende kunne fortolkes som den størrelse, den prædikterede salgspris vil stige med, hvis en lejlighed er præcis ét år ældre end en anden tilsvarende lejlighed (det vil her sige en lejlighed med samme areal).</p>
<p>Vi illustrerer dette med et eksempel:</p>
<div id="exm-lejlighed2" class="theorem example page-columns page-full">
<p><span class="theorem-title"><strong>Eksempel 2 (Lejlighedspriser – fortolkning af vægtene)</strong></span> Træner vi en kunstig neuron på datasættet om lejlighedssalg, hvor vi sætter alle startvægte til <span class="math inline">\(0\)</span>, vælger en learning rate på <span class="math inline">\(0.0001\)</span> og antal iterationer til <span class="math inline">\(500\)</span>, får vi følgende værdier af vægtene</p>
<table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(w_0\)</span> <br> <br></th>
<th style="text-align: center;"><span class="math inline">\(w_1\)</span> <br> (<code>areal</code>)</th>
<th style="text-align: center;"><span class="math inline">\(w_2\)</span> <br>(<code>alder</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(0.0637521\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.0195118\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.0023493\)</span></td>
</tr>
</tbody>
</table>
<p>For eksempel kan vi se, at <span class="math inline">\(w_1 = 0.0195118\)</span>. Det vil sige, at ifølge modellen vil prisen på en lejlighed, som er præcis én kvadratmeter større end en anden tilsvarende<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> lejlighed, være cirka <span class="math inline">\(19512\)</span> kroner højere (husk på at prisen er målt i millioner, så vi skal lige gange med en million, hvis vi skal have værdien oversat til kroner).</p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;En tilsvarende lejlighed vil her mere præcist betyde en lejlighed med den samme alder.</p></div></div><p>Vi ser også, at <span class="math inline">\(w_2=-0.0023493\)</span>, som betyder, at hvis vi står med to tilsvarende lejligheder, hvor den ene er præcis et år ældre end den anden, så vil salgsprisen på den ældste lejlighed ifølge modellen være <span class="math inline">\(2349\)</span> kroner lavere.</p>
<p>I det nedenstående har vi plottet den faktiske pris (i millioner) ud af <span class="math inline">\(x\)</span>-aksen og den prædikterede pris op af <span class="math inline">\(y\)</span>-aksen.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-pred_versus_price" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-pred_versus_price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="simple_neurale_net_regression_files/figure-html/fig-pred_versus_price-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-pred_versus_price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;1: Den faktiske lejlighedspris (i millioner) ud af <span class="math inline">\(x\)</span>-aksen og den prædikterede pris op af <span class="math inline">\(y\)</span>-aksen.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hvis vi har en perfekt model, så vil den prædikterede pris være lig med den faktiske pris. Det vil svare til, at alle punkterne i <a href="#fig-pred_versus_price" class="quarto-xref">figur&nbsp;1</a> vil ligge på linjen med ligning <span class="math inline">\(y=x\)</span> (som er indtegnet med lyseblå i figuren). På figuren kan vi derfor se, at for lejligheder, som koster under <span class="math inline">\(3\)</span> millioner er modellen ikke helt dårlig. Til gengæld er modellen ikke super god til at prædiktere salgsprisen for de dyrere lejligheder: For nogle lejligheder er den prædikterede salgspris for høj, mens det omvendte også gør sig gældende – specielt de meget dyre lejligheder, som koster over <span class="math inline">\(5\)</span> millioner, prædikterer modellen for lavt.</p>
</div>
</section>
</section>
<section id="vurdering-af-modellens-anvendelighed" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="vurdering-af-modellens-anvendelighed">Vurdering af modellens anvendelighed</h2>
<p>Når man træner en kunstig neuron, har man brug for et mål for, hvor god modellen er. Du kender nok allerede <span class="math inline">\(R^2\)</span>-værdien fra lineær regression, som et tal mellem <span class="math inline">\(0\)</span> og <span class="math inline">\(1\)</span>, hvor vi gerne vil have tallet så tæt på <span class="math inline">\(1\)</span> som muligt (og så alligevel ikke helt – det kommer vi tilbage til senere). Et andet mål, som kan bruges til at sammenligne modeller, er <strong>root mean squared error (RMSE)</strong>. For at forstå dette mål starter vi med at se på alle de kvadrerede fejl:</p>
<p><span class="math display">\[
\left (t^{(m)}-o^{(m)} \right)^2
\]</span> Det er <strong>squared error (SE)</strong>. Så udregner vi den gennemsnitlige værdi af alle disse kvadrerede fejl:</p>
<p><span class="math display">\[
\frac{1}{M} \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right)^2
\]</span> På den måde får vi et mål, som ikke er afhængig af datasættets størrelse. Det er <strong>mean squared error (MSE)</strong>. Endelig tager vi kvadratroden af det (for at få målet ned på samme skala<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, som vores targetværdi):</p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;Hvis man for eksempel har en targetværdi, som er målt i meter (<span class="math inline">\(m\)</span>), så vil enheden af MSE være meter i anden (<span class="math inline">\(m^2\)</span>). Tager vi derfor kvadratroden af MSE, kommer vi tilbage til en enhed i meter.</p></div></div><p><span class="math display">\[
\mathrm{RMSE} = \sqrt{\frac{1}{M} \sum_{m=1}^{M} \left (t^{(m)}-o^{(m)} \right)^2}
\]</span></p>
<p>Det er altså denne størrelse, som er <strong>root mean squared error (RMSE)</strong>. Da vi ønsker så lille en fejl som muligt, vil vi gerne have, at RMSE er så tæt på <span class="math inline">\(0\)</span> som muligt.</p>
<div id="exm-lejlighed3" class="theorem example">
<p><span class="theorem-title"><strong>Eksempel 3 (Lejlighedspriser – RMSE og <span class="math inline">\(R^2\)</span>)</strong></span> Ser vi på den kunstige neuron fra <a href="#exm-lejlighed2" class="quarto-xref">eksempel&nbsp;2</a> kan man udregne RMSE. Gør man det får man</p>
<p><span class="math display">\[
\mathrm{RMSE} = 0.497
\]</span></p>
<p>Uden sammenligning med andre modeller er det svært at vide, om det tal er godt eller skidt. Til gengæld kan vi udregne <span class="math inline">\(R^2\)</span>-værdien, som er</p>
<p><span class="math display">\[
R^2 = 0.596
\]</span> Du er måske vant til at se <span class="math inline">\(R^2\)</span>-værdier, som er meget større, men for en model baseret på et datasæt fra den virkelige verden er det såmen ikke helt tosset!</p>
</div>
<section id="krydsvalidering" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="krydsvalidering">Krydsvalidering</h3>
<p>Når en models anvendelighed vurderes ved hjælp af mål som RMSE og <span class="math inline">\(R^2\)</span>-værdi, så vil det altid være sådan, at jo mere kompliceret en model, man bruger, desto bedre mål vil man få (det vil sige en lille værdi af RMSE og en værdi af <span class="math inline">\(R^2\)</span>, som er tæt på <span class="math inline">\(1\)</span>). Hvorfor det er tilfældet, kan du læse meget mere om i noten <a href="../../noter/krydsvalidering/krydsvalidering.html" target="_blank">Overfitting, modeludvælgelse og krydsvalidering</a>). Kort fortalt går det ud på, at en meget kompliceret model kan fange tendenser i data, som i virkeligheden ikke er reelle – det er bare støj. Et eksempel ses i <a href="#fig-overfitting" class="quarto-xref">figur&nbsp;2</a>:</p>
<div id="fig-overfitting" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-overfitting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/overfitting.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-overfitting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;2: Ti punkter hvor der er anvendt lineær regression (den lyseblå linje) og 9. grads polynomiel regression (den lyserøde kurve).
</figcaption>
</figure>
</div>
<p>Det kan her tydeligt ses, at en ret linje beskriver punkterne udmærket. Et 9. grads polynomium har til gengæld så meget fleksibilitet, at grafen for polynomiet kan gå igennem alle ti punkter. Det ses tydeligt på <a href="#fig-overfitting" class="quarto-xref">figur&nbsp;2</a>, at det bliver alt for mærkeligt, og vi har ingen forventninger om, at dette polynomium vil kunne bruges til at beskrive nye punkter, som ikke kommer fra datasættet. Men bruger vi for eksempel <span class="math inline">\(R^2\)</span>-værdien til at sammenligne de to modeller, så får vi:</p>
<table class="table-bordered table">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: center;"><span class="math inline">\(R^2\)</span>-værdi</th>
<th style="text-align: center;">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lineær regression</td>
<td style="text-align: center;"><span class="math inline">\(0.916\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.603\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">9. grads polynomiel regression</td>
<td style="text-align: center;"><span class="math inline">\(1.000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.000\)</span></td>
</tr>
</tbody>
</table>
<p>Så ser vi alene på <span class="math inline">\(R^2\)</span>-værdien og RMSE, kunne vi blive foranlediget til at tro, at vi skulle vælge polynomiel regression. Man skal altså være utrolig varsom med uden videre at sammenligne den type mål! Men hvad gør man så? Ét bud er at bruge noget, som kaldes for <strong>krydsvalidering</strong>. Princippet er illustreret i <a href="#fig-krydsvalidering" class="quarto-xref">figur&nbsp;3</a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-krydsvalidering" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-krydsvalidering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="simple_neurale_net_regression_files/figure-html/fig-krydsvalidering-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-krydsvalidering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;3: Illustration af idéen ved <span class="math inline">\(5\)</span>-fold krydsvalidering.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Man starter med at inddele data tilfældigt i <span class="math inline">\(5\)</span> lige store dele: del 1, 2, 3, 4 og 5. Så træner man en model (lad os sige, at man laver lineær regression) baseret på del 2, 3, 4 og 5. Det giver en ret linje. Hefter bruger man del 1 til at udregne for eksempel RMSE baseret på den model, man lige har bestemt.</p>
<p>Har man for eksempel et datasæt med <span class="math inline">\(500\)</span> dataeksempler så udregnes RMSE på denne måde:</p>
<p><span class="math display">\[
\mathrm{RMSE} = \sqrt{\frac{1}{100} \sum_{m \in \textrm{del 1}}\left (t^{(m)}-o^{(m)} \right)^2}
\]</span></p>
<p>Her summerer vi altså over alle træningseksempler i del 1. Husk på, at outputværdien <span class="math inline">\(o^{(m)}\)</span> findes ved</p>
<p><span class="math display">\[
o^{(m)} = w_0 + w_1 \cdot x_1^{(m)} + \cdots + w_n \cdot x_n^{(m)}
\]</span></p>
<p>Her stammer inputværdierne <span class="math inline">\(x_1^{(m)}, x_2^{(m)}, \dots, x_n^{(m)}\)</span> fra del 1, men vægtene <span class="math inline">\(w_0, w_1, w_2, \dots, w_n\)</span> er fundet ved at bruge data fra del 2, 3, 4 og 5. Man undersøger altså, hvor god modellen er til at prædiktere data i del 1, hvis den kun er trænet på data fra del 2, 3, 4 og 5. Derfor kalder man del 1 for <strong>testdata</strong> og del 2, 3, 4 og 5 for <strong>træningsdata</strong>. Det er helt essentielt her, at man tester sin model på en del af data, som <em>ikke</em> har været brugt til at træne modellen på. Dette gentager man så, men næste gang er det del 2, som er testdata og del 1, 3, 4 og 5 som er træningsdata. Igen udregnes RMSE. Denne proceduren gentages i alt 5 gang. Det giver 5 forskellige RMSE værdier. Herefter tager man gennemsnittet af dem for at få et samlet mål for modellens anvendelighed.</p>
<p>Det viser sig, at det ikke giver så meget mening, at udregne <span class="math inline">\(R^2\)</span>-værdien i forbindelse med krydsvalidering. For eksempel kan værdien gå hen og blive negativ. Vi vil derfor i det følgende nøjes med at se på RMSE.</p>
<div id="exm-lejlighed4" class="theorem example">
<p><span class="theorem-title"><strong>Eksempel 4 (Lejlighedspriser – RMSE med krydsvalidering)</strong></span> Vi vil nu udregne RMSE baseret på <span class="math inline">\(5\)</span>-folds krydsvalidering. Det giver</p>
<p><span class="math display">\[
\mathrm{RMSE} = 0.502
\]</span></p>
<p>Bemærk, at hvis vi sammenligner med RMSE, som ikke er baseret på krydsvalidering fra <a href="#exm-lejlighed3" class="quarto-xref">eksempel&nbsp;3</a>, så er RMSE her blevet en smule højere her. Det er helt forventeligt, at modellen vil klare sig bedre, når den er testet på de data, som den også er trænet på.</p>
</div>
</section>
</section>
<section id="prædiktion-af-lejlighedspriser-nu-med-skjulte-lag" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="prædiktion-af-lejlighedspriser-nu-med-skjulte-lag">Prædiktion af lejlighedspriser – nu med skjulte lag!</h2>
<p>Når man skal sælge en lejlighed, skal der helst ikke være skjulte fejl og mangler. Det kan til gengæld være en rigtig god idé med nogle skjulte lag, når man skal prædiktere lejlighedspriser! Det vil vi se på nu.</p>
<p>I det ovenstående kommer den prædikterede pris til at afhænge lineært af inputvariablene. Men verden er sjældent lineær – og en af styrkerne ved kunstige neurale netværk er netop, at de kan prædiktere størrelser eller kategorier ved hjælp af funktioner, som ikke er lineære. Vi skal derfor nu opstille et simpelt kunstigt neuralt netværk til prædiktion af lejlighedspriser. Vi vil lave et netværk med to features <span class="math inline">\(x_1, x_2\)</span> men nu med noget, som vi vil kalde for et skjult lag, som her består af fem såkaldte neuroner. Det kan illustreres, som vist i <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a>:</p>
<div id="fig-neuralt_net_regression" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-neuralt_net_regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/neuralt_net_regression.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-neuralt_net_regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;4: Simpelt kunstigt neuralt netværk til prædiktion af lejlighedspriser. Netværket har inputvariable <span class="math inline">\(x_1, x_2\)</span> og ét skjult lag med to neuroner (her vist som de to grønne cirkler i midten).
</figcaption>
</figure>
</div>
<p>Som det ses i <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a>, er der til hver pil knyttet en vægt (for eksempel <span class="math inline">\(v_1, u_1, w_1\)</span> og så videre), som skal bruges til at udregne outputværdien <span class="math inline">\(o\)</span>. Hvis vi for en stund forestiller os, at vi kender alle vægtene, så udregner vi outputværdien <span class="math inline">\(o\)</span> på følgende måde:</p>
<p>Ved hjælp af inputvariablene og <span class="math inline">\(v\)</span>-vægtene (de lysegrønne pile på <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a>) beregner vi <span class="math inline">\(z_1\)</span>:</p>
<p><span class="math display">\[
z_1 = f(v_0 + v_1 \cdot x_1 + v_2 \cdot x_2)
\]</span> som selvfølgelig kan generaliseres til</p>
<p><span class="math display">\[
z_1 = f(v_0 + v_1 \cdot x_1 + \cdots + v_n \cdot x_n)
\]</span></p>
<p>Her er <span class="math inline">\(f\)</span> en funktion, som kaldes for en <strong>aktiveringsfunktion</strong>, og det er den, der gør, at vi ender med at prædiktere lejlighedspriser på en ikke-lineær måde. Den kommer vi tilbage til lige om lidt.</p>
<p>På tilsvarende vis udregner vi <span class="math inline">\(z_2\)</span> ved at bruge <span class="math inline">\(u\)</span>-vægtene (de mørkegrønne pile på <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a>):</p>
<p><span class="math display">\[
z_2 = f(u_0 + u_1 \cdot x_1 + u_2 \cdot x_2)
\]</span></p>
<p>Når vi nu har <span class="math inline">\(z_1\)</span> og <span class="math inline">\(z_2\)</span> beregnes outputværdien <span class="math inline">\(o\)</span>, som vi gjorde det tidligere (her er <span class="math inline">\(w\)</span>-vægtene vist som de lyseblå pile på <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a>):</p>
<p><span class="math display">\[
o = w_0 + w_1 \cdot z_1 + w_2 \cdot z_2
\]</span></p>
<section id="relu-aktiveringsfunktionen" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="relu-aktiveringsfunktionen">ReLu aktiveringsfunktionen</h3>
<p>Lad os se nærmere på aktiveringsfunktionen <span class="math inline">\(f\)</span>. Hvis du har læst nogle af vores andre noter, ved du, at en ofte anvendt aktiveringsfunktion er sigmoid-funktionen med forskrift:</p>
<p><span class="math display">\[
\sigma (x) = \frac{1}{1+\mathrm{e}^{-x}}
\]</span> Grafen for sigmoid-funktionen ses i <a href="#fig-sigmoid" class="quarto-xref">figur&nbsp;5</a>.</p>
<div id="fig-sigmoid" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-sigmoid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../kunstige_neuroner/images/sigmoid.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-sigmoid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;5: Grafen for sigmoid-funktionen.
</figcaption>
</figure>
</div>
<p>Denne aktiveringsfunktion er super god at bruge, når outputværdien skal beregnes, <em>hvis</em> man skal lave binær klassifikation, fordi funktionsværdien ligger mellem <span class="math inline">\(0\)</span> og <span class="math inline">\(1\)</span> og derfor kan fortolkes som en sandsynlighed. I alle andre sammenhænge er den faktisk ikke super anvendelig!</p>
<p>En aktiveringsfunktion som til gengæld ofte anvendes i de skjulte er ReLu-funktionen<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Den er defineret således:</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;relu</p></div><div id="fn5"><p><sup>5</sup>&nbsp;relu</p></div></div><p><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>: ReLU står for Rectified Linear Unit.</p>
<p><span class="math display">\[
\textrm{ReLu}(x) =
\begin{cases}
0 &amp; \textrm {hvis } x &lt; 0 \\
x &amp; \textrm {hvis } x \geq 0
\end{cases}
\]</span></p>
<p>Grafen for ReLu-funktionen ses i <a href="#fig-relu" class="quarto-xref">figur&nbsp;6</a>.</p>
<div id="fig-relu" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-relu-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/relu.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-relu-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;6: Grafen for ReLu-funktionen.
</figcaption>
</figure>
</div>
<p>ReLu-funktionen transformerer altså alle negative inputværdier til <span class="math inline">\(0\)</span> og alle positive inputværdier forbliver uændret. Det ser jo næsten lineært ud, men det er altså nok til, at man kan modellere nogle meget ikke-lineære funktioner, hvis bare man har nok skjulte lag med nok neuroner i hver.</p>
</section>
<section id="feedforward-udtryk" class="level3">
<h3 class="anchored" data-anchor-id="feedforward-udtryk">Feedforward udtryk</h3>
<p>Ovenstående udtryk for beregning af <span class="math inline">\(z_1\)</span>, <span class="math inline">\(z_2\)</span> og <span class="math inline">\(o\)</span>, hvor <span class="math inline">\(f\)</span> nu beregner ReLu-funktionen, kaldes for <strong>feedforward</strong> ligninger, fordi man laver beregninger "fremad" i netværket i <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a> fra venstre mod højre. Hvis vi samtidig holder styr på, hvilket træningseksempel vi står med, får vi følgende:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Feedforward-udtryk
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>På baggrund af inputværdierne <span class="math inline">\(x_1\)</span> og <span class="math inline">\(x_2\)</span> beregnes outputværdien <span class="math inline">\(o\)</span> på følgende måde.</p>
<p>Først beregnes:</p>
<p><span id="eq-z_1"><span class="math display">\[
z_1^{(m)} = \textrm{ReLu} \left (v_0 + v_1 \cdot x_1^{(m)} + v_2 \cdot x_2^{(m)} \right)
\tag{1}\]</span></span></p>
<p>og</p>
<p><span id="eq-z_2"><span class="math display">\[
z_2^{(m)} = \textrm{ReLu} \left (u_0 + u_1 \cdot x_1^{(m)} + u_2 \cdot x_2^{(m)} \right)
\tag{2}\]</span></span></p>
<p>Herefter beregnes outputværdien:</p>
<p><span id="eq-o"><span class="math display">\[
o^{(m)} = w_0 + w_1 \cdot z_1^{(m)} + w_2 \cdot z_2^{(m)}
\tag{3}\]</span></span></p>
</div>
</div>
</div>
<p>Tabsfunktionen definerer vi nu som før</p>
<p><span class="math display">\[
\begin{aligned}
E(v_0, v_1, \dots, v_4, &amp; u_0, u_1, \dots, u_4,w_0, w_1, w_2) \\ &amp;= \frac{1}{2} \sum_{m=1}^{M} \left (t^{(m)}-
o^{(m)} \right)^2
\end{aligned}
\]</span></p>
<p>hvor <span class="math inline">\(o^{(m)}\)</span> er givet ved udtrykket i (<a href="#eq-o" class="quarto-xref">3</a>). Læg mærke til, at tabsfunktionen afhænger af alle <span class="math inline">\(u\)</span>-, <span class="math inline">\(v\)</span>- og <span class="math inline">\(w\)</span>-vægte, men for nemheds skyld vil vi blot skrive <span class="math inline">\(E\)</span> i det følgende.</p>
</section>
<section id="backpropagation" class="level3">
<h3 class="anchored" data-anchor-id="backpropagation">Backpropagation</h3>
<p>Man kan nu igen bruge gradientnedstigning til at bestemme de værdier er <span class="math inline">\(v\)</span>-, <span class="math inline">\(u\)</span>- og <span class="math inline">\(w\)</span>-vægtene, som minimerer tabsfunktionen. Det er her en vigtig beregningsfinte, at man bevæger sig "bagud" i netværket i <a href="#fig-neuralt_net_regression" class="quarto-xref">figur&nbsp;4</a> og først opdaterer <span class="math inline">\(w\)</span>-vægtene (som er tættest på outputlaget) og dernæst <span class="math inline">\(u\)</span>- og <span class="math inline">\(v\)</span>-vægtene, som er tættest på inputlaget. Dette kaldes for <strong>backpropagation</strong>.</p>
<p>Gør man det, ender man med følgende opdateringsregler:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Backpropagation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Backpropagation foregår samlet set på denne måde:</p>
<ol type="1">
<li><p>Sæt alle vægtene til en tilfældig værdi og vælg en værdi for learning raten <span class="math inline">\(\eta\)</span>.</p></li>
<li><p>For alle træningsdataeksempler udregnes <span class="math inline">\(z_1^{(m)}\)</span>, <span class="math inline">\(z_2^{(m)}\)</span> og <span class="math inline">\(o^{(m)}\)</span> ved hjælp af feedforward-udtrykkene:</p>
<p><span class="math display">\[
\begin{aligned}
z_1^{(m)} &amp;= \textrm{ReLu} \left (v_0 + v_1 \cdot x_1^{(m)} + v_2 \cdot x_2^{(m)} \right ) \\
z_2^{(m)} &amp;= \textrm{ReLu} \left (u_0 + u_1 \cdot x_1^{(m)} + u_2 \cdot x_2^{(m)} \right ) \\
o^{(m)} &amp;= w_0 + w_1 \cdot z_1^{(m)} + w_2 \cdot z_2^{(m)}
\end{aligned}
\]</span></p></li>
<li><p>Vægtene opdatereres:</p>
<p><strong><span class="math inline">\(w\)</span>-vægtene:</strong> <span class="math display">\[
\begin{aligned}
w_0^{\textrm{(ny)}} &amp;\leftarrow w_0 + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \\
w_1^{\textrm{(ny)}} &amp;\leftarrow w_1 + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \cdot z_1^{(m)} \\
w_2^{\textrm{(ny)}} &amp;\leftarrow w_2 + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \cdot z_2^{(m)}
\end{aligned}
\]</span> hvor</p>
<p><span class="math display">\[
\delta^{(m)} = t^{(m)}-o^{(m)}
\]</span> <strong><span class="math inline">\(v\)</span>-vægtene:</strong> <span class="math display">\[
\begin{aligned}
v_0^{\textrm{(ny)}} &amp;\leftarrow v_0 + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \cdot w_1  \\
v_i^{\textrm{(ny)}} &amp;\leftarrow v_i + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \cdot w_1  \cdot x_i^{(m)}\\
\end{aligned}
\]</span> for <span class="math inline">\(i \in \{1, 2\}\)</span>.</p>
<p><strong><span class="math inline">\(u\)</span>-vægtene:</strong> <span class="math display">\[
\begin{aligned}
u_0^{\textrm{(ny)}} &amp;\leftarrow u_0 + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \cdot w_2  \\
u_i^{\textrm{(ny)}} &amp;\leftarrow u_i + \eta \cdot \sum_{m=1}^{M} \delta^{(m)} \cdot w_2  \cdot x_i^{(m)}\\
\end{aligned}
\]</span> for <span class="math inline">\(i \in \{1, 2\}\)</span>.</p></li>
</ol>
<p>Alle vægtene er nu opdateret, og vi kan gentage punkt 2 og 3, hvor feedforward i 2 hver gang er baseret på de netop opdaterede vægte fra det foregående gennemløb. Opdateringen af vægtene fortsætter, indtil værdien af tabsfunktionen næsten ikke ændrer sig. Håbet er nu, at vi har fundet et minimum (eventuelt kun lokalt) for tabsfunktionen.</p>
</div>
</div>
</div>
<p>Bemærk her, at vi kender <span class="math inline">\(z_1^{(m)}\)</span>, <span class="math inline">\(z_2^{(m)}\)</span> og <span class="math inline">\(o^{(m)}\)</span> på grund af feedforward, mens alle <span class="math inline">\(u-\)</span>, <span class="math inline">\(v-\)</span> og <span class="math inline">\(w-\)</span>værdierne er de nuværende værdier af vægtene (<em>inden</em> opdatering).</p>
<p>I alle opdateringsreglerne indgår faktoren</p>
<p><span class="math display">\[
\delta^{(m)} = t^{(m)}-o^{(m)}
\]</span></p>
<p>Denne størrelse er et udtryk for den fejl, netværket begår med de nuværende værdier af vægtene (nemlig forskellen på den ønskede targetværdi <span class="math inline">\(t^{(m)}\)</span> og den prædikterede outputværdi <span class="math inline">\(o^{(m)}\)</span>). Der er to ting, som er værd at bemærke i den forbindelse:</p>
<ul>
<li>Hvis fejlen er stor, bliver vægtene opdateret forholdsvis meget – og omvendt hvis fejlen er lille.</li>
<li>Når vi har opdateret <span class="math inline">\(w\)</span>-vægtene, har vi allerede beregnet fejlen <span class="math inline">\(\delta^{(m)}\)</span>. Denne "fejlfaktor" indgår også i opdateringsreglerne for <span class="math inline">\(v\)</span>- og <span class="math inline">\(u\)</span>-vægtene, og den allerede beregnede fejl kan altså genbruges, når <span class="math inline">\(v\)</span>- og <span class="math inline">\(u\)</span>-vægtene skal opdateres.</li>
</ul>
<p>Det kan her virke fuldstændig ligegyldigt, om vi skal beregne fejlen et par ekstra gange eller ej, men i virkelighedens anvendelser af kunstige neurale netværk, er det lige præcis denne beregningsmæssige finte, som gør, at det overhovedet kan lade sig gøre at bruge gradientnedstigning. Det sparer nemlig både tid og lagringsplads på computeren, at tidligere beregnede størrelser kan genbruges i de næste opdateringer.</p>
<p>Hvis du gerne vil bevise ovenstående, er der lidt hjælp at hente i nedenstående boks.</p>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Hjælp til at udlede opdateringsreglerne
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Husk på, at vores tabsfunktion ser sådan her ud:</p>
<p><span class="math display">\[
\begin{aligned}
E &amp;= \frac{1}{2} \sum_{m=1}^{M} \left (t^{(m)}-
o^{(m)} \right)^2 \\
&amp;= \sum_{m=1}^{M} \frac{1}{2} \left (t^{(m)}-
(w_0 + w_1 \cdot z_1^{(m)} + w_2 \cdot z_2^{(m)}) \right)^2 \\
&amp;= \sum_{m=1}^{M} E^{(m)},
\end{aligned}
\]</span></p>
<p>hvor vi her har sat</p>
<p><span id="eq-Em"><span class="math display">\[
E^{(m)}= \frac{1}{2} \left (t^{(m)}-
(w_0 + w_1 \cdot z_1^{(m)} + w_2 \cdot z_2^{(m)}) \right)^2
\tag{4}\]</span></span></p>
<p>Vi ved fra sumreglen, at vi skal differentiere ledvist. Det vil sige, når <span class="math inline">\(E\)</span> skal differentieres med hensyn til én af vægtene, så kan vi bare differentiere <span class="math inline">\(E^{(m)}\)</span> med hensyn til den pågældende vægt og lægge alle disse partielle afledede sammen. For eksempel er</p>
<p><span class="math display">\[
\frac{\partial E}{\partial w_i} = \sum_{m=1}^M \frac{\partial E^{(m)}}{\partial w_i}
\]</span> I det følgende får du derfor hints til at differentiere <span class="math inline">\(E^{(m)}\)</span>.</p>
<p>Når du skal bestemme</p>
<p><span class="math display">\[
\frac{\partial E^{(m)}}{\partial w_i}
\]</span></p>
<p>så skal du gøre fuldstændig, som vi gjorde i afsnittet <a href="#hvad-koster-min-lejlighed">HVad koster min lejlighed?</a>.</p>
<p>Når du skal finde</p>
<p><span class="math display">\[
\frac{\partial E^{(m)}}{\partial v_i}
\]</span></p>
<p>skal man egentlig bruge kædereglen for funktioner af flere variable, fordi <span class="math inline">\(E^{(m)}\)</span> både afhænger af <span class="math inline">\(z_1^{(m)}(v_i)\)</span> og <span class="math inline">\(z_2^{(m)}(v_i)\)</span>. Det ser sådan her ud:</p>
<p><span class="math display">\[
\frac{\partial E^{(m)}}{\partial v_i} = \frac{\partial E^{(m)}}{\partial z_1^{(m)}}\cdot\frac{\partial z_1^{(m)}}{\partial v_i} + \frac{\partial E^{(m)}}{\partial z_2^{(m)}}\cdot\frac{\partial z_2^{(m)}}{\partial v_i}
\]</span></p>
<p>Men vi ved fra feedforward udtrykkene, at</p>
<p><span id="eq-z_1m"><span class="math display">\[
z_1^{(m)} = \textrm{ReLu} \left (v_0 + v_1 \cdot x_1^{(m)} + v_2 \cdot x_2^{(m)} \right )
\tag{5}\]</span></span></p>
<p>og</p>
<p><span class="math display">\[
z_2^{(m)} = \textrm{ReLu} \left (u_0 + u_1 \cdot x_1^{(m)} + u_2 \cdot x_2^{(m)} \right )
\]</span></p>
<p>og her kan vi se, at det kun er <span class="math inline">\(z_1^{(m)}\)</span>, som afhænger af <span class="math inline">\(v_i\)</span>. Det betyder, at</p>
<p><span class="math display">\[
\frac{\partial z_2^{(m)}}{\partial v_i} = 0
\]</span></p>
<p>og derfor er</p>
<p><span class="math display">\[
\frac{\partial E^{(m)}}{\partial v_i} = \frac{\partial E^{(m)}}{\partial z_1^{(m)}}\cdot\frac{\partial z_1^{(m)}}{\partial v_i}
\]</span></p>
<p>Hvis du har brug for lidt mere information om kædereglen og den notation, som vi har anvendt ovenfor, kan du eventuelt se <a href="https://www.youtube.com/watch?v=nVaAIVXiUjs">denne video</a>.</p>
<p>Når du skal bestemme</p>
<p><span class="math display">\[
\frac{\partial E^{(m)}}{\partial z_1^{(m)}}
\]</span></p>
<p>skal du bruge udtrykket for <span class="math inline">\(E^{(m)}\)</span> i (<a href="#eq-Em" class="quarto-xref">4</a>). Og når <span class="math inline">\(z_1^{(m)}\)</span> skal differentieres med hensyn til <span class="math inline">\(v_i\)</span>, skal du bruge udtrykket i (<a href="#eq-z_1m" class="quarto-xref">5</a>).</p>
<p>Nu er det sådan, at ReLu-funktionen faktisk slet ikke er differentiabel i <span class="math inline">\(x=0\)</span>! Til gengæld er det ikke svært at overbevise sig selv om, at</p>
<p><span class="math display">\[
\textrm{ReLu}'(x) =
\begin{cases}
0 &amp; \textrm{hvis } x &lt; 0 \\
1 &amp; \textrm{hvis } x &gt; 0
\end{cases}
\]</span></p>
<p>Og så definerer vi os simpelthen ud af tilfældet, hvor <span class="math inline">\(x=0\)</span>:</p>
<p><span class="math display">\[
\textrm{ReLu}'(0) = 1.
\]</span></p>
<p>På helt tilsvarende vis kan</p>
<p><span class="math display">\[\frac{\partial E^{(m)}}{\partial u_i}
\]</span></p>
<p>findes.</p>
<p>Og så er der kun tilbage at ønske god arbejdslyst!</p>
</div>
</div>
</div>


</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aimat\.dk");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><img src="../../logo/SVG/Bomaerke_03_AIMAT_2024.svg" class="footer-logo"> aimat.dk er finansieret af Novo Nordisk Fonden</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script src="../../scripts/navbar-tooltips.js"></script>
<script src="../../scripts/trim-categories.js"></script>




</body></html>