---
title: 'Facit til forløbet \"Inddeling af musik i grupper\"'
description: ''
image: ""
categories:
---

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 1
Midterpunktet er i $\left ( 5, \frac{10}{3} \right ) \approx (5, 3.33)$.

:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 4
| Gruppe  | Danceability  | Energy | Speechiness|
|:--------:|:--------:|:--------:|:--------:|
| $1$ |	$0.692$ |	$0.774$ |	$0.056$ | 
| $2$ | $0.710$ | $0.752$ | $0.102$ |
| $3$ | $0.726$ | $0.666$ | $0.112$ |
: {.bordered}

\

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 6 
| Nummer  | Afstand midterpunkt 1  | Afstand midterpunkt 2 | Afstand midterpunkt 3| Opr. gruppe | Ny gruppe|
|--------|:--------:|:--------:|:--------:|:--------:|:--------:|
|Barbie Girl|	$0.189$ |	$0.213$ |	$0.295$ | $1$ | $1$ |
|Shape of You| $0.187$ | $0.159$ |	$0.110$ |$2$ | $3$ |
|Set Fire to the Rain|	$0.143$ |	$0.160$ |	$0.156$ | $3$ | $1$ |
|Wake Me Up|	$0.162$ |	$0.189$ |	$0.235$ | $1$ | $1$ |
|Baby One More Time|	$0.104$ |	$0.102$ |	$0.095$ | $2$ | $3$|
|Just The Way You Are|	$0.086$ |	$0.128$ |	$0.207$ | $3$ | $1$ |
|New Rules|	$0.088$ |	$0.067$ |	$0.076$ | $1$ | $2$ |
|Stan	| $0.181$ |	$0.129$ |	$0.134$ | $2$ | $2$ |
|In Da Club|	$0.382$ |	$0.331$ |	$0.314$ | $3$ | $3$ |
|Blinding Lights|	$0.184$ |	$0.210$ |	$0.259$ | $1$ | $1$ |
|Blank Space|	$0.101$ |	$0.089$ |	$0.078$ | $2$ | $3$ |
|Dance Monkey|	$0.227$ |	$0.196$ |	$0.123$ | $3$ | $3$ |
|Hotline Bling|	$0.259$ |	$0.235$ |	$0.187$ | $1$| $3$ |
|Die To Live|	$0.346$ |	$0.365$ |	$0.432$ | $2$ | $1$ |
|White Iverson|	$0.255$ |	$0.243$ |	$0.172$ | $3$ | $3$ |
: {.bordered}

\

:::

::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 8

Nedenstående er baseret på den løsning, som Orange finder med antal \"Re-runs\" sat til 200 og antal \"Maximum iterations\" sat til 500.

{{< include _geogebra/_geogebra.qmd >}}

::: {.ggbContainer style='width:90%; margin: auto'}
::: {#ggbApplet_musik}
:::
:::


:::


::: {.callout-note collapse="true" appearance="minimal"}  
### Facit -- opgave 9
$SUMPAR$ er ca. $1.1496$ for den oprindelige inddeling.

Efter en runde med opdateringer (resultatet fra opgave 6) er $SUMPAR$ ca. $0.6159$.

For den endelige inddeling (baseret på Orange) er $SUMPAR$ i stedet ca. $0.4481$.

Som forventet falder værdien, hvilket jo er meningen med K-Means.


:::

