---
title: "3-dages kursus i Aalborg: Gymnasiematematikken bag kunstig intelligens"
---

## Kursusbeskrivelse

Nu har du chancen for at finde ud af hvordan kernestof som vektorregning, differentialregning, sandsynlighedsregning og meget mere bruges i kunstig intelligens.
Dette 3-dages kursus klæder dig på til at kunne undervise i gymnasiematematikken bag kunstig intelligens på alle trin i gymnasieskolen.

- Vi tager udgangspunkt i noterne om AI-matematik fra <https://aimat.dk>
- Alle noter og forløb er dansksprogede og niveaumæssigt designet til gymnasieelever
- Vi veksler mellem faglige oplæg og afprøvning af elevrettede forløb
- Vi giver eksempler på hvordan noter og forløb kan sættes sammen til at dække kravet om 10% supplerende stof i læreplanerne med tilhørende eksamensspørgsmål.

Eksempler på emner:

+ Neurale netværk (store sammensatte funktioner)
+ Træning af neurale netværk (optimering)
+ Træningsdata, testdata og krydsvalidering
+ Klassifikation og regression
+ Vektorrepræsentationer af ord
+ Sprogmodeller og forudsigelse af næste ord

## Tid og sted

- 17.-19. november 2026 (om tirsdagen starter vi med ankomst, registrering og en sandwich kl. 12 - 13 og så starter det faglige program kl. 13. Om torsdagen vil der være sandwich i en pose med en flaske vand to go kl. 12)
- AAU Innovate, Aalborg Universitet, Thomas Manns Vej 25

## Kursusholdere

- Malene Cramer Engebjerg, Aalborghus Gymnasium
- Ege Rubak, Aalborg Universitet

## Pris og tilmelding

- Samlet pris **inkl. overnatning og forplejning:** 6.000 kr (+moms)
- Der kan søges støtte fra Novo Nordisk Fonden til at dække kursusgebyret samt vikartimer osv.
- Link til tilmelding og betaling (EAN, kreditkort eller MobilePay):  
<https://www.events.aau.dk/event/gymnasiematematikken-bag-kunstig-intelligens>

#### Inkluderet i kursusgebyr

- Tre kursusdage med oplæg og hands-on undervisningforløb
- To hotelovernatninger (deltagere der ikke ønsker hotel bedes notere det under tilmeldingen)
- Tre gange frokost (oplys evt. kosthensyn under tilmeldingen)
- En kursusmiddag sammen med kursusholdere og de øvrige deltagere (oplys evt. kosthensyn under tilmeldingen)
- Vand, kaffe, kage og frugt i løbet af kursusdagene

#### Ikke inkluderet i kursusgebyr

- Transport (vi anbefaler tog -- der en god busforbindelse mellem Aalborg banegård og universitetet)
- Middag den ene aften
