---
title: "Program"
---

Program for Gymnasiematematikken bag kunstig intelligens den 17. - 19. november 2026. Programmet opdateres løbende.

## Tirsdag den 17. november 2026

| Tid | Programpunkt |
|:---:|:----------------------------------|
| 12.00 - 13.00 | Ankomst, registrering og sandwich |
| 13.00-13.15| Præsentation af hjemmesiden og program for kurset |
| 13.15 - 14.00 | Kunstige neuroner, del 1 v/Malene |
| 14.00-15.30 | Hands-on med kaffe og kage: <br>
 * Langt forløb om kunstige neuroner (Hovedforløb) |
| 15.30-16.00 | Kunstige neuroner, del 2 (fokus på overfitting, modeludvælgelse og krydsvalidering) v/Malene |
| 16.00-17.30 |  Hands-on: <br>
* Langt forløb om kunstige neuroner (Valgfrie dele) |
| 17.30-18.00 | Opsamling |
| 18.00-20.00 | Middag |
: {.bordered}

	



## Onsdag den 18. november 2026

| Tid | Programpunkt |
|:---:|:----------------------------------|
| 9.00-9.30 | Simple kunstige neurale netværk til regression (herunder introduktion til ReLU-forløb) v/Malene |
|9.30-10.00 | Hands-on med kaffe: <br>
* Kan du bygge funktioner med ReLU? (opgave xx) |
| 10.00-10.30 | Simple kunstige neurale netværk til multipel klassifikation herunder softmax og cross-entropy v/Malene |
| 10.30-12.00 | Hands-on: <br> * Differentiation af softmax <br> * Kandidattest |
| 12.00-12.30 | Opsamling og perspektivering med Orange v/Malene |
| 12.30-13.15 | Frokost |
| 13.15-14.00 | Sprogmodeller, del 1 v/Ege |
| 14.00-15.30	| Hands-on med kaffe og kage: <br> * Langt forløb om sprogmodeller (del 1-3) |
| 15.30-16.00	| Sprogmodeller, del 2 v/ Ege |
| 16.00-17.00	| Hands-on: <br> * Langt forløb om sprogmodeller (del 4-5) |
| 17.00-17.30	| Opsamling og tak for i dag |
: {.bordered}

## Torsdag den 19. november 2026

| Tid | Programpunkt |
|:---:|:----------------------------------|
| 9.00-9.45 | Anbefalingssystemer |
| 9.45-10.30 | Hands-on: <br> * Hvad skal du se på Netflix? |
| 10.30-11.00	| Support Vector Machines |
| 11.00-11.30	| Idéer til forløb |
| 11.30-12.00	| Evaluering |
| 12.00	| Sandwich to-go og tak for denne gang |
: {.bordered}